import type { ExerciseSeed } from '../exerciseTypes';

export const caseExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-irab-concept', conceptCode: 'c-irab-concept', type: 'compare_analyses',
    objective: 'Track a single noun\'s case change across three sentences.',
    prompt: 'الطَّالِبُ (case-01), الطَّالِبَ (case-02), الطَّالِبِ (case-03) — the same word appears with three different endings. What changed in each sentence to explain each ending?', difficulty: 2,
    expectedAnswer: 'The word\'s grammatical role changed each time: فاعل (nominative) → مفعول به (accusative) → مجرور بحرف جر (genitive). The word itself and its meaning never changed.',
    hints: ['Identify each sentence\'s verb or preposition and what role الطالب plays relative to it.'],
    explanation: 'This triplet is the clearest possible demonstration that إعراب tracks role, not word identity or meaning.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-irab-concept', conceptCode: 'c-irab-concept', type: 'identify_role',
    objective: 'Distinguish معرب from مبني words.',
    prompt: 'Does هَذَا change its ending depending on its grammatical role? What is this category of word called?', difficulty: 2,
    expectedAnswer: 'No, it never changes — it is مبني (built).', acceptedVariants: ['مبني', 'built'],
    hints: ['Compare هذا across several different sentence roles you have seen it in.'],
    explanation: 'هذا is مبني: its case is still assigned and estimated, but never shown by a changing ending.',
    misconceptionTags: ['mis-case-on-indeclinables'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-three-cases', conceptCode: 'c-three-cases', type: 'identify_role',
    objective: 'Match grammatical roles to their default case home.',
    prompt: 'Which case is the default home for فاعل: رفع، نصب، or جر؟', difficulty: 1,
    expectedAnswer: 'رفع (nominative)', acceptedVariants: ['nominative', 'رفع'],
    hints: ['فاعل never needs an outside governor to explain its case.'],
    explanation: 'فاعل, like مبتدأ and خبر, lives in رفع by default.', estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-three-cases', conceptCode: 'c-three-cases', type: 'identify_role',
    objective: 'Match grammatical roles to their default case home.',
    prompt: 'Which case does a noun always take after a preposition?', difficulty: 1,
    expectedAnswer: 'جر (genitive)', acceptedVariants: ['genitive', 'جر'],
    hints: ['This is a fixed, exceptionless rule.'],
    explanation: 'Every noun governed by a preposition is genitive, with no exceptions to this specific rule.', estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-marker-types', conceptCode: 'c-marker-types', sentenceCode: 'case-06-sound-plural-predicate', type: 'identify_role',
    objective: 'Classify a case marker as visible, secondary, or estimated.',
    prompt: 'What type of marker is ـُونَ on الْمُعَلِّمُونَ?', difficulty: 2,
    expectedAnswer: 'secondary', acceptedVariants: ['secondary marker'],
    hints: ['Is this an ordinary short vowel, or a whole dedicated suffix?'],
    explanation: 'ـُونَ is a secondary marker: a dedicated suffix that entirely replaces the ordinary short-vowel case system for sound plurals.',
    misconceptionTags: ['mis-marker-type-confusion'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-marker-types', conceptCode: 'c-marker-types', sentenceCode: 'case-08-diptote-genitive', type: 'identify_role',
    objective: 'Classify a diptote\'s genitive marker.',
    prompt: 'مِصْرَ shows فتحة for the genitive, not كسرة. Is this a visible, secondary, or estimated marker?', difficulty: 3,
    expectedAnswer: 'It is still a visible marker (you can see and hear the vowel), but it is a substituted one — the diptote borrows the accusative vowel to stand in for the genitive.',
    hints: ['You can still hear a short vowel here — so it is not "estimated." What makes it unusual is which vowel appears.'],
    explanation: 'Diptote genitives are a special case: visibly marked, but with a borrowed vowel rather than the expected one — worth its own attention alongside the three main marker types.',
    estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-diptotes', conceptCode: 'c-diptotes', sentenceCode: 'case-08-diptote-genitive', type: 'select_ending',
    objective: 'Apply diptote case rules.',
    prompt: 'Complete: سَافَرْتُ إِلَى مِصْر___ — what ending, and why no تنوين?', difficulty: 3,
    expectedAnswer: 'فتحة (مِصْرَ), with no تنوين, because مصر is a diptote.', acceptedVariants: ['fatha, مصرَ'],
    hints: ['Diptotes never take تنوين, and use فتحة for both accusative and genitive.'],
    explanation: 'مِصْرَ takes فتحة instead of the expected كسرة, and no تنوين — the defining behavior of a diptote.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-diptotes', conceptCode: 'c-diptotes', type: 'explain_rule',
    objective: 'Explain the diptote rule in general terms.',
    prompt: 'In your own words, what makes a noun a diptote, and what are the two visible consequences?', difficulty: 3,
    expectedAnswer: 'Diptotes are a closed set of nouns (many proper names, the أفعل/فعلاء pattern family, certain broken plurals) that take فتحة for both accusative and genitive, and never take تنوين.',
    hints: ['Name at least one category of noun that is typically diptote.'],
    explanation: 'A full answer names the rule\'s two consequences (shared accusative/genitive vowel, no تنوين) and at least one triggering category.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-irab-concept', conceptCode: 'c-irab-concept', type: 'teach_back',
    objective: 'Explain the concept of إعراب to a beginner.',
    prompt: 'A learner asks: "So is إعراب just a list of endings I have to memorize?" How would you correct that framing?', difficulty: 2,
    expectedAnswer: 'إعراب is not a list to memorize — it is a system where the ending is evidence of a word\'s grammatical role. Once you know the role, the correct ending mostly follows from a small set of consistent rules.',
    hints: ['Contrast "memorizing endings" with "identifying roles."'],
    explanation: 'This reframing — role first, ending second — is the single most useful mental model this app tries to install early.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-marker-types', conceptCode: 'c-marker-types', type: 'compare_analyses',
    objective: 'Distinguish estimated markers from missing case.',
    prompt: 'A noun ending in a possessive ي (e.g. كِتَابِي, "my book") cannot show a short-vowel case ending at all. Does that noun therefore "have no case"?', difficulty: 4,
    expectedAnswer: 'No — it still has a case, which is simply estimated (مقدّرة) rather than pronounced, because the final ي physically blocks a short vowel from being heard.',
    hints: ['Recall the third marker category from this lesson.'],
    explanation: 'An estimated marker means the grammar still assigns a case; only the sound is blocked by the word\'s own shape.',
    misconceptionTags: ['mis-marker-type-confusion'], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-three-cases', conceptCode: 'c-three-cases', type: 'full_irab',
    objective: 'Perform full إعراب using role-first reasoning.',
    prompt: 'Perform full إعراب on فِي الْفَصْلِ (as it appears in الطُّلَّابُ فِي الْفَصْلِ).', difficulty: 3,
    expectedAnswer: 'فِي: حرف جر مبني لا محل له من الإعراب. الْفَصْلِ: اسم مجرور بـفي وعلامة جره الكسرة الظاهرة.',
    hints: ['Name the particle\'s category first, then the governed noun\'s case and marker.'],
    explanation: 'في is a built particle with no case of its own; الفصل is genitive, governed by في, with a visible kasrah marker.',
    estimatedSeconds: 40,
  },
];
