import type { ExerciseSeed } from '../exerciseTypes';

export const conjugationExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-perfect', conceptCode: 'c-perfect-tense', type: 'complete_conjugation',
    objective: 'Conjugate a sound Form I verb in the perfect for several persons.',
    prompt: 'Conjugate كتب ("to write") in the perfect for: هو، هي، أنتَ، أنا، هم.', difficulty: 2,
    expectedAnswer: 'هو: كَتَبَ. هي: كَتَبَتْ. أنتَ: كَتَبْتَ. أنا: كَتَبْتُ. هم: كَتَبُوا.',
    hints: ['The stem كتب stays constant; only the suffix changes per person.'],
    explanation: 'The perfect conjugates entirely through suffixes attached to the fixed stem كتب.', estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-perfect', conceptCode: 'c-perfect-tense', type: 'identify_role',
    objective: 'Recognize a fused subject pronoun.',
    prompt: 'كَتَبْتُ الدَّرْسَ. Where is this sentence\'s فاعل?', difficulty: 2,
    expectedAnswer: 'The attached suffix ـتُ ("I") — no separate word is needed.',
    hints: ['A perfect verb\'s person suffix can itself be the فاعل.'],
    explanation: 'ـتُ fully performs the فاعل role; there is no missing subject here.',
    misconceptionTags: ['mis-missing-embedded-pronoun'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-perfect', conceptCode: 'c-perfect-tense', type: 'repair_error',
    objective: 'Correct an under-conjugated verb.',
    prompt: 'Find the error: "أنا ذهب إلى المدرسة" (intended: "I went to school").', difficulty: 2,
    expectedAnswer: 'ذهب should be ذَهَبْتُ — the verb must carry the first-person suffix, not stay in its bare citation form.',
    hints: ['Arabic verbs must be conjugated for their subject — they cannot stay in a bare, unmarked shape.'],
    explanation: 'Correct: أنا ذَهَبْتُ إلى المدرسة. Leaving a verb unconjugated is a common transfer error from languages with less verbal inflection.',
    misconceptionTags: ['mis-verbs-no-person-gender'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-imperfect', conceptCode: 'c-imperfect-tense', sentenceCode: 'verb-06-imperfect-indefinite-object', type: 'transform_word',
    objective: 'Convert a perfect verb to its imperfect equivalent.',
    prompt: 'Convert كَتَبَ (he wrote) to the imperfect (he writes).', difficulty: 2,
    expectedAnswer: 'يَكْتُبُ', acceptedVariants: ['يكتب'],
    hints: ['Add the third-person prefix ي and adjust the stem vowel.'],
    explanation: 'يَكْتُبُ replaces the perfect\'s suffix-based person marking with a prefix, and gains a mood-sensitive final vowel.', estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-imperfect', conceptCode: 'c-imperfect-tense', type: 'identify_role',
    objective: 'Read person/gender off an imperfect prefix.',
    prompt: 'تَكْتُبُ can mean either "she writes" or "you (m., singular) write." What single feature of Arabic morphology creates this ambiguity, resolved only by context?', difficulty: 3,
    expectedAnswer: 'The prefix تَـ marks both third-person feminine singular and second-person masculine singular in the imperfect — the two overlap.',
    hints: ['List everyone تَـ could refer to.'],
    explanation: 'This built-in ambiguity is why context (or an explicit pronoun) often accompanies تَـ-prefixed verbs.', estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', type: 'transform_word',
    objective: 'Derive an imperative from an imperfect verb.',
    prompt: 'From يَكْتُبُ ("he writes"), derive the imperative "write!" addressed to a man.', difficulty: 3,
    expectedAnswer: 'اُكْتُبْ', acceptedVariants: ['اكتب'],
    hints: ['Strip the person prefix ي and, since a consonant cluster would otherwise start the word, add a helping أ.'],
    explanation: 'اكتب is derived, not memorized separately — it comes directly from the jussive form of يكتب.', estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', type: 'transform_word',
    objective: 'Derive a feminine imperative.',
    prompt: 'Derive the imperative "write!" addressed to a woman.', difficulty: 3,
    expectedAnswer: 'اُكْتُبِي', acceptedVariants: ['اكتبي'],
    hints: ['The feminine imperative keeps the ي ending that marks "you, feminine."'],
    explanation: 'اكتبي retains the ي that distinguishes a feminine addressee from a masculine one.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-mood', conceptCode: 'c-mood-jussive-subjunctive', type: 'identify_role',
    objective: 'Identify the mood-marking ending on an imperfect verb.',
    prompt: 'يَكْتُبُ ends in a ḍammah. What mood does that mark by default?', difficulty: 2,
    expectedAnswer: 'indicative (رفع)', acceptedVariants: ['رفع', 'indicative'],
    hints: ['This is the imperfect\'s baseline mood, used when no governing particle is present.'],
    explanation: 'A final ḍammah on the imperfect marks the default indicative mood.', estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-mood', conceptCode: 'c-mood-jussive-subjunctive', type: 'transform_word',
    objective: 'Apply the subjunctive after a governing particle.',
    prompt: 'أُرِيدُ أَنْ ___ الدَّرْسَ (I want to write the lesson) — conjugate يكتب correctly after أنْ.', difficulty: 3,
    expectedAnswer: 'أَكْتُبَ', acceptedVariants: ['اكتب فتحة', 'أكتب'],
    hints: ['أنْ triggers the subjunctive (نصب) on the following imperfect verb — what ending does that require?'],
    explanation: 'After أنْ, the imperfect verb takes a fatḥah ending: أَكْتُبَ — subjunctive, parallel to accusative for nouns.', estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-mood', conceptCode: 'c-mood-jussive-subjunctive', type: 'explain_rule',
    objective: 'Explain the parallel between verbal mood and nominal case.',
    prompt: 'Explain how the imperfect verb\'s mood system (رفع، نصب، جزم) parallels the noun\'s case system.', difficulty: 4,
    expectedAnswer: 'Both systems mark grammatical role/relationship through an ending; both have a default state (رفع) and states triggered by specific governing particles (نصب by أنْ/لنْ/كي, جزم by لمْ/لا الناهية, نصب on nouns by prepositions/إنّ etc.).',
    hints: ['Name the shared default state and at least one shared governing mechanism.'],
    explanation: 'This parallel is one of the most useful bridges in the whole course: verbal إعراب works on the same underlying logic as nominal إعراب.', estimatedSeconds: 50,
  },
  {
    lessonCode: 'l-perfect', conceptCode: 'c-perfect-tense', type: 'teach_back',
    objective: 'Explain why Arabic can form a one-word sentence.',
    prompt: 'Explain to a beginner why ذَهَبْتُ by itself is already a complete sentence in Arabic, while English "went" is not.', difficulty: 2,
    expectedAnswer: 'The suffix ـتُ fuses the subject ("I") directly into the verb, so no separate subject word is required — English marks person through a separate pronoun instead.',
    hints: ['Compare where person information lives in each language.'],
    explanation: 'A correct answer identifies fused pronoun suffixes as the mechanism.', estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-imperfect', conceptCode: 'c-imperfect-tense', type: 'complete_conjugation',
    objective: 'Conjugate an imperfect verb across several persons.',
    prompt: 'Conjugate كتب in the imperfect indicative for: هو، هي، أنا، نحن، هم.', difficulty: 3,
    expectedAnswer: 'هو: يَكْتُبُ. هي: تَكْتُبُ. أنا: أَكْتُبُ. نحن: نَكْتُبُ. هم: يَكْتُبُونَ.',
    hints: ['Change only the prefix (and, for هم, add a suffix too) — the stem كتب stays constant.'],
    explanation: 'The imperfect conjugates primarily through prefixes, with a suffix added for plural forms.', estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-imperfect', conceptCode: 'c-imperfect-tense', type: 'identify_role',
    objective: 'Name the imperfect prefix for "we."',
    prompt: 'Which prefix marks the imperfect verb for نحن ("we")?', difficulty: 1,
    expectedAnswer: 'نَـ', acceptedVariants: ['ن', 'na-'],
    hints: ['Compare نَدْرُسُ ("we study") to يَدْرُسُ ("he studies").'],
    explanation: 'نَـ marks first-person plural in the imperfect, one of the four core person-marking prefixes.',
    estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', type: 'transform_word',
    objective: 'Derive an imperative from a يَفْعِلُ-pattern imperfect.',
    prompt: 'From يَجْلِسُ ("he sits"), derive the imperative "sit!" addressed to a man.', difficulty: 3,
    expectedAnswer: 'اِجْلِسْ', acceptedVariants: ['اجلس'],
    hints: ['Strip the ي prefix and add the helping vowel that matches the imperfect\'s own middle vowel — here ِ, since the imperfect is يَجْلِسُ.'],
    explanation: 'اِجْلِسْ takes a helping اِ (kasrah) because the jussive stem جْلِسْ starts with two consonants — the same helping-hamza logic as اُكْتُبْ, with the vowel matching the imperfect\'s own.',
    estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', sentenceCode: 'verb-11-imperative', type: 'identify_role',
    objective: 'Identify the hidden subject of a bare imperative.',
    prompt: 'In اِفْتَحِ الْبَابَ ("Open the door!"), what is the hidden subject of افتحِ؟', difficulty: 2,
    expectedAnswer: 'أنتَ (an obligatorily hidden second-person pronoun)', acceptedVariants: ['أنت', 'you'],
    hints: ['An imperative always addresses "you" even when no separate pronoun word appears.'],
    explanation: 'Every plain imperative has أنتَ (or its gender/number variants) as an obligatorily hidden فاعل — it is never actually spoken as a separate word.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', type: 'explain_rule',
    objective: 'Explain why Form I imperatives need a helping hamza but derived-form imperatives do not.',
    prompt: 'اِفْتَحْ needs a helping همزة at the start, but عَلِّمْ (Form II, "teach!") does not. Why the difference?', difficulty: 3,
    expectedAnswer: "Form I's jussive stem, once the person prefix is stripped, would start with two consonants in a row (فْتَحْ) — disallowed in Arabic — so a helping vowel is added. Form II's stem already begins with a vowel-bearing consonant once the prefix is removed (عَلِّمْ), so nothing needs to be added.",
    hints: ['Strip the person prefix from each verb\'s jussive form and look at what letter is left at the very start.'],
    explanation: "This is a general rule, not a fact about فتح specifically: any Form I imperative whose jussive stem would start with a consonant cluster needs a helping hamza; derived-form imperatives (II–X) never do.",
    estimatedSeconds: 35,
  },
];
