import type { ExerciseSeed } from '../exerciseTypes';

export const foundationsExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف.',
    prompt: 'What word class is كَتَبَ?', difficulty: 1,
    expectedAnswer: 'فعل (verb)', acceptedVariants: ['verb', 'فعل'],
    hints: ['Does this word describe an action tied to a specific time?', 'Compare it to "wrote" in English — can you conjugate it for different people?'],
    explanation: 'كَتَبَ is a verb: it expresses the action of writing, locked to the past tense, and can be conjugated (كَتَبْتُ، كَتَبَتْ، كَتَبُوا...).',
    estimatedSeconds: 20, reviewPriority: 2,
  },
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف.',
    prompt: 'What word class is عَلَى?', difficulty: 1,
    expectedAnswer: 'حرف (particle)', acceptedVariants: ['particle', 'حرف'],
    hints: ['Does this word mean anything on its own, or only once attached to a noun?'],
    explanation: 'عَلَى ("on") is a particle: it has no independent meaning and only functions once attached to a following noun.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف, including a tricky case (adjective-as-noun).',
    prompt: 'What word class is مُجْتَهِدٌ, grammatically?', difficulty: 2,
    expectedAnswer: 'اسم (noun)', acceptedVariants: ['noun', 'اسم'],
    invalidPlausible: [{ answer: 'صفة (adjective) — a fourth category', why: 'English treats "adjective" as its own part of speech, but Arabic grammar files all describing words under اسم — there is no separate فعل/اسم/حرف/صفة four-way split.' }],
    hints: ['It takes تنوين (ـٌ) — a hallmark of nouns.', 'Arabic does not have a separate grammatical category for "adjective" the way English does.'],
    explanation: 'مُجْتَهِدٌ is grammatically a noun (specifically, an active-participle-shaped noun used descriptively). Arabic has no independent "adjective" word class — describing words are simply nouns used in an attributive or predicative role.',
    misconceptionTags: [], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-nominal-vs-verbal', type: 'identify_role',
    objective: 'Classify a sentence as nominal or verbal from its opening word.',
    prompt: 'Is كَتَبَ الطَّالِبُ الدَّرْسَ a nominal or verbal sentence?', difficulty: 1,
    expectedAnswer: 'verbal', acceptedVariants: ['verbal', 'جملة فعلية'],
    hints: ['Check only the very first word.', 'كَتَبَ is a verb.'],
    explanation: 'The sentence opens with the verb كَتَبَ, so it is verbal — regardless of what the sentence describes.',
    misconceptionTags: ['mis-first-noun-is-subject'], estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-nominal-vs-verbal', type: 'identify_role',
    objective: 'Classify a sentence as nominal or verbal from its opening word.',
    prompt: 'Is الطُّلَّابُ كَتَبُوا الدَّرْسَ a nominal or verbal sentence, even though it describes an action?', difficulty: 2,
    expectedAnswer: 'nominal', acceptedVariants: ['nominal', 'جملة اسمية'],
    hints: ['Check only the first word\'s word class, not the sentence\'s meaning.'],
    explanation: 'Despite describing an action (writing), this sentence opens with the noun الطلاب, making it structurally nominal — with an embedded verbal sentence as its خبر.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-complete-utterance', type: 'identify_role',
    objective: 'Tell a complete utterance apart from a bare phrase.',
    prompt: 'Does كِتَابُ الطَّالِبِ ("the student\'s book") leave a listener satisfied on its own, the way a full sentence does?', difficulty: 1,
    expectedAnswer: 'No — it is a bare phrase (idafa construction), not a complete utterance; it names something but asserts nothing about it.',
    acceptedVariants: ['no', 'not complete', 'incomplete'],
    hints: ['Ask: has anything actually been stated, or only named?', 'Compare it to الطَّالِبُ مُجْتَهِدٌ, which does assert something.'],
    explanation: 'كِتَابُ الطَّالِبِ is a noun phrase (an إضافة) — it identifies "the student\'s book" but says nothing about it, so it fails the الكلام test. Adding a خبر, e.g. كِتَابُ الطَّالِبِ جَدِيدٌ ("the student\'s book is new"), would complete it.',
    misconceptionTags: [], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-complete-utterance', type: 'repair_error',
    objective: 'Turn an incomplete phrase into a complete utterance.',
    prompt: 'فِي الْبَيْتِ ("in the house") is a prepositional phrase, not a complete utterance. Add the minimum needed to make it one, e.g. describing a book being there.', difficulty: 2,
    expectedAnswer: 'الْكِتَابُ فِي الْبَيْتِ ("the book is in the house") — adding a subject the prepositional phrase can serve as خبر for.',
    hints: ['A prepositional phrase alone never satisfies الكلام — it always needs to attach to a مبتدأ or a verb.'],
    explanation: 'فِي الْبَيْتِ only becomes a complete utterance once it is predicated of something, e.g. as the خبر of a مبتدأ like الكتاب.',
    misconceptionTags: [], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-demonstratives', conceptCode: 'c-demonstratives', type: 'transform_word',
    objective: 'Select the correct demonstrative for a given noun\'s gender.',
    prompt: 'Which demonstrative correctly completes: ___ مَدْرَسَةٌ (This is a school)?', difficulty: 1,
    expectedAnswer: 'هَذِهِ', acceptedVariants: ['هذه'],
    invalidPlausible: [{ answer: 'هَذَا', why: 'هذا is the masculine demonstrative; مدرسة is grammatically feminine (it ends in ة).' }],
    hints: ['Check مدرسة\'s final letter — what gender does that ending usually signal?'],
    explanation: 'مدرسة ends in ة, marking it feminine, so it takes the feminine demonstrative هذه.',
    misconceptionTags: [], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-pronouns', conceptCode: 'c-personal-pronouns', type: 'identify_role',
    objective: 'Recognize an attached subject pronoun and what it encodes.',
    prompt: 'In رَأَيْتُ الطَّالِبَ, what does the suffix ـتُ tell you?', difficulty: 2,
    expectedAnswer: 'first-person singular subject ("I")', acceptedVariants: ['I', 'first person singular', 'أنا'],
    hints: ['This suffix is attached directly to the verb stem.', 'Compare with the detached pronoun أنا.'],
    explanation: 'ـتُ is the attached first-person-singular subject pronoun — it means "I" and makes رَأَيْتُ a complete sentence by itself.',
    misconceptionTags: ['mis-missing-embedded-pronoun'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-questions-negation', conceptCode: 'c-negation-basic', type: 'explain_rule',
    objective: 'Explain why ليس changes case, unlike لا or ما.',
    prompt: 'Why is غَائِبًا accusative in لَيْسَ الطَّالِبُ غَائِبًا, when negation words like لا usually do not change case at all?',
    difficulty: 3, expectedAnswer: 'Because ليس is grammatically a verb (a sister of كان) that governs its predicate into the accusative, unlike لا or ما, which are plain negating particles with no case effect.',
    hints: ['Check ليس\'s grammatical category — is it really a particle, or something else?', 'Compare its case behavior to كان.'],
    explanation: 'ليس behaves exactly like كان: it takes a nominative subject (اسم ليس) and an accusative predicate (خبر ليس). This sets it apart from لا and ما, which negate without governing case at all.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', type: 'select_ending',
    objective: 'Apply genitive case after a preposition.',
    prompt: 'Vocalize the correct case ending: فِي الْفَصْل___ (in the classroom)', difficulty: 1,
    expectedAnswer: 'ـِ (kasrah) → الفَصْلِ', acceptedVariants: ['كسرة', 'kasrah', 'الفصلِ'],
    hints: ['What case does every preposition require of its noun?'],
    explanation: 'في governs الفصل into the genitive, marked by kasrah.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', type: 'repair_error',
    objective: 'Detect and correct a case error after a preposition.',
    prompt: 'Find and fix the error: "الكتابُ على الطاولةُ" (intended: "The book is on the table").', difficulty: 2,
    expectedAnswer: 'الطاولةِ (genitive, not nominative) — على governs the noun that follows it.',
    hints: ['Look at the last word — what governs it?', 'Prepositions always require genitive.'],
    explanation: 'الطاولة must be genitive (الطاولةِ) because it follows the preposition على — the sentence-final position does not exempt it from government.',
    estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-nominal-vs-verbal', sentenceCode: 'nom-21-definiteness-fronted-khabar', type: 'identify_role',
    objective: 'Classify a sentence as nominal even when a particle opens it.',
    prompt: 'Is فِي الْحَدِيقَةِ أَزْهَارٌ a nominal or verbal sentence, even though a preposition comes first?', difficulty: 3,
    expectedAnswer: 'nominal', acceptedVariants: ['nominal', 'جملة اسمية'],
    invalidPlausible: [{ answer: 'Neither / undefined, since it opens with a particle', why: 'A leading preposition phrase does not create a third sentence type — the true مبتدأ, أزهار, is a noun, which is what makes the whole sentence nominal even though it appears last.' }],
    hints: ['Ignore the fronted شبه جملة and find the real مبتدأ — the word the sentence is actually about.', 'أزهار is a noun.'],
    explanation: 'The mبتدأ here is أزهار (delayed because it is indefinite); since it is a noun, the sentence is nominal, regardless of في الحديقة appearing first.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-complete-utterance', type: 'repair_error',
    objective: 'Recognize that an idafa-plus-adjective phrase is still not a complete utterance.',
    prompt: 'Is كِتَابُ الطَّالِبِ الْجَدِيدُ ("the student\'s new book") by itself a complete utterance (كلام)?', difficulty: 2,
    expectedAnswer: 'No — it is still just a noun phrase (idafa plus an attributive adjective); it names something but asserts nothing.',
    acceptedVariants: ['no', 'not complete', 'incomplete'],
    hints: ['Ask: has anything actually been stated about the book, or only named?'],
    explanation: 'Every word here (كتاب، الطالب، الجديد) works together to name one thing more precisely — nothing predicates anything about it, so الكلام still fails until a خبر is added, e.g. كِتَابُ الطَّالِبِ الْجَدِيدُ مُفِيدٌ.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-pronouns', conceptCode: 'c-personal-pronouns', sentenceCode: 'nom-09-pronoun-mubtada-plural-khabar', type: 'identify_role',
    objective: 'Distinguish a detached (free-standing) pronoun from an attached one.',
    prompt: 'In نَحْنُ طُلَّابٌ مُجْتَهِدُونَ, what kind of pronoun is نحن, and what role does it play?', difficulty: 2,
    expectedAnswer: 'A detached pronoun (ضمير منفصل), functioning as the مبتدأ.',
    acceptedVariants: ['detached', 'ضمير منفصل', 'independent pronoun'],
    hints: ['Is نحن its own separate word, or fused onto another word?'],
    explanation: 'نحن stands entirely on its own as a separate word — a ضمير منفصل — unlike an attached pronoun such as the هُ in كتبَهُ.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-pronouns', conceptCode: 'c-personal-pronouns', type: 'transform_word',
    objective: 'Attach an object pronoun onto a Form I verb.',
    prompt: 'Attach the object pronoun for "them" (masculine) onto فَهِمَ ("he understood").', difficulty: 2,
    expectedAnswer: 'فَهِمَهُمْ', acceptedVariants: ['فهمهم'],
    hints: ['The masculine plural object pronoun is هُمْ.'],
    explanation: 'فَهِمَهُمْ fuses هُمْ directly onto the verb as its attached مفعول به, exactly like ـهُ does in فهمه.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-questions-negation', conceptCode: 'c-questions', type: 'identify_role',
    objective: 'Identify what an interrogative particle is asking about.',
    prompt: 'In مَتَى تَذْهَبُ إِلَى الْمَدْرَسَةِ؟ ("when do you go to school?"), what is متى asking about?', difficulty: 1,
    expectedAnswer: 'Time — "when."', acceptedVariants: ['time', 'when'],
    hints: ['متى is one of a family of question words, each asking about a different thing (مَن → who, مَاذَا → what, أَيْنَ → where).'],
    explanation: 'متى specifically asks about time, distinct from أين (place) or من (person).',
    estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-questions-negation', conceptCode: 'c-negation-basic', type: 'transform_sentence',
    objective: 'Negate a past-tense verb with ما instead of لم.',
    prompt: 'Negate كَتَبَ الطَّالِبُ الدَّرْسَ using ما instead of لم.', difficulty: 2,
    expectedAnswer: 'مَا كَتَبَ الطَّالِبُ الدَّرْسَ',
    acceptedVariants: ['ما كتب الطالب الدرس'],
    invalidPlausible: [{ answer: 'مَا يَكْتُبْ الطَّالِبُ الدَّرْسَ', why: 'ما negating a past event keeps the verb in the plain past (ماضٍ) tense — it does not switch to the imperfect or trigger jussive the way لم does.' }],
    hints: ['ما simply precedes the verb with no change to its tense or mood — unlike لم, which requires the jussive imperfect.'],
    explanation: 'ما + the plain past verb is the simplest way to negate a past event; لم + jussive imperfect is a stylistic alternative with the same meaning, not a requirement.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', sentenceCode: 'nom-15-khabar-zarf', type: 'identify_role',
    objective: 'Identify a prepositional phrase functioning as khabar.',
    prompt: 'In الْكِتَابُ فِي الْحَقِيبَةِ ("the book is in the bag"), what role does في الحقيبة play?', difficulty: 1,
    expectedAnswer: 'khabar (شبه جملة)', acceptedVariants: ['khabar', 'خبر'],
    hints: ['What is being predicated of الكتاب?'],
    explanation: 'The whole prepositional phrase في الحقيبة, not just في or الحقيبة alone, serves as the خبر — this is exactly the شبه جملة khabar pattern.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', sentenceCode: 'nom-15-khabar-zarf', type: 'identify_governor',
    objective: 'Identify what governs a noun into the genitive.',
    prompt: 'In الطَّائِرُ فَوْقَ الشَّجَرَةِ, what governs الشجرة into the genitive?', difficulty: 2,
    expectedAnswer: 'فَوْقَ (as a ẓarf in idafa with الشجرة)', acceptedVariants: ['فوق'],
    hints: ['فوق is a ظرف مكان that behaves like the first term of an idafa.'],
    explanation: 'فوق takes الشجرة as its مضاف إليه, governing it into the genitive exactly like a preposition would.',
    estimatedSeconds: 20,
  },
];
