import type { ExerciseSeed } from '../exerciseTypes';

export const foundationsExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف.',
    prompt: 'What word class is كَتَبَ?', difficulty: 1,
    expectedAnswer: 'فعل (verb)', acceptedVariants: ['verb', 'فعل'],
    hints: ['Does this word describe an action tied to a specific time?', 'Compare it to "wrote" in English — can you conjugate it for different people?'],
    explanation: 'كَتَبَ is a verb: it expresses the action of writing, locked to the past tense, and can be conjugated (كَتَبْتُ، كَتَبَتْ، كَتَبُوا...).',
    estimatedSeconds: 20, reviewPriority: 2,
  },
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف.',
    prompt: 'What word class is عَلَى?', difficulty: 1,
    expectedAnswer: 'حرف (particle)', acceptedVariants: ['particle', 'حرف'],
    hints: ['Does this word mean anything on its own, or only once attached to a noun?'],
    explanation: 'عَلَى ("on") is a particle: it has no independent meaning and only functions once attached to a following noun.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-word-classes', conceptCode: 'c-word-classes', type: 'identify_role',
    objective: 'Classify a word as اسم، فعل، or حرف, including a tricky case (adjective-as-noun).',
    prompt: 'What word class is مُجْتَهِدٌ, grammatically?', difficulty: 2,
    expectedAnswer: 'اسم (noun)', acceptedVariants: ['noun', 'اسم'],
    invalidPlausible: [{ answer: 'صفة (adjective) — a fourth category', why: 'English treats "adjective" as its own part of speech, but Arabic grammar files all describing words under اسم — there is no separate فعل/اسم/حرف/صفة four-way split.' }],
    hints: ['It takes تنوين (ـٌ) — a hallmark of nouns.', 'Arabic does not have a separate grammatical category for "adjective" the way English does.'],
    explanation: 'مُجْتَهِدٌ is grammatically a noun (specifically, an active-participle-shaped noun used descriptively). Arabic has no independent "adjective" word class — describing words are simply nouns used in an attributive or predicative role.',
    misconceptionTags: [], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-nominal-vs-verbal', type: 'identify_role',
    objective: 'Classify a sentence as nominal or verbal from its opening word.',
    prompt: 'Is كَتَبَ الطَّالِبُ الدَّرْسَ a nominal or verbal sentence?', difficulty: 1,
    expectedAnswer: 'verbal', acceptedVariants: ['verbal', 'جملة فعلية'],
    hints: ['Check only the very first word.', 'كَتَبَ is a verb.'],
    explanation: 'The sentence opens with the verb كَتَبَ, so it is verbal — regardless of what the sentence describes.',
    misconceptionTags: ['mis-first-noun-is-subject'], estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-complete-sentence', conceptCode: 'c-nominal-vs-verbal', type: 'identify_role',
    objective: 'Classify a sentence as nominal or verbal from its opening word.',
    prompt: 'Is الطُّلَّابُ كَتَبُوا الدَّرْسَ a nominal or verbal sentence, even though it describes an action?', difficulty: 2,
    expectedAnswer: 'nominal', acceptedVariants: ['nominal', 'جملة اسمية'],
    hints: ['Check only the first word\'s word class, not the sentence\'s meaning.'],
    explanation: 'Despite describing an action (writing), this sentence opens with the noun الطلاب, making it structurally nominal — with an embedded verbal sentence as its خبر.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-demonstratives', conceptCode: 'c-demonstratives', type: 'transform_word',
    objective: 'Select the correct demonstrative for a given noun\'s gender.',
    prompt: 'Which demonstrative correctly completes: ___ مَدْرَسَةٌ (This is a school)?', difficulty: 1,
    expectedAnswer: 'هَذِهِ', acceptedVariants: ['هذه'],
    invalidPlausible: [{ answer: 'هَذَا', why: 'هذا is the masculine demonstrative; مدرسة is grammatically feminine (it ends in ة).' }],
    hints: ['Check مدرسة\'s final letter — what gender does that ending usually signal?'],
    explanation: 'مدرسة ends in ة, marking it feminine, so it takes the feminine demonstrative هذه.',
    misconceptionTags: [], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-pronouns', conceptCode: 'c-personal-pronouns', type: 'identify_role',
    objective: 'Recognize an attached subject pronoun and what it encodes.',
    prompt: 'In رَأَيْتُ الطَّالِبَ, what does the suffix ـتُ tell you?', difficulty: 2,
    expectedAnswer: 'first-person singular subject ("I")', acceptedVariants: ['I', 'first person singular', 'أنا'],
    hints: ['This suffix is attached directly to the verb stem.', 'Compare with the detached pronoun أنا.'],
    explanation: 'ـتُ is the attached first-person-singular subject pronoun — it means "I" and makes رَأَيْتُ a complete sentence by itself.',
    misconceptionTags: ['mis-missing-embedded-pronoun'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-questions-negation', conceptCode: 'c-negation-basic', type: 'explain_rule',
    objective: 'Explain why ليس changes case, unlike لا or ما.',
    prompt: 'Why is غَائِبًا accusative in لَيْسَ الطَّالِبُ غَائِبًا, when negation words like لا usually do not change case at all?',
    difficulty: 3, expectedAnswer: 'Because ليس is grammatically a verb (a sister of كان) that governs its predicate into the accusative, unlike لا or ما, which are plain negating particles with no case effect.',
    hints: ['Check ليس\'s grammatical category — is it really a particle, or something else?', 'Compare its case behavior to كان.'],
    explanation: 'ليس behaves exactly like كان: it takes a nominative subject (اسم ليس) and an accusative predicate (خبر ليس). This sets it apart from لا and ما, which negate without governing case at all.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', type: 'select_ending',
    objective: 'Apply genitive case after a preposition.',
    prompt: 'Vocalize the correct case ending: فِي الْفَصْل___ (in the classroom)', difficulty: 1,
    expectedAnswer: 'ـِ (kasrah) → الفَصْلِ', acceptedVariants: ['كسرة', 'kasrah', 'الفصلِ'],
    hints: ['What case does every preposition require of its noun?'],
    explanation: 'في governs الفصل into the genitive, marked by kasrah.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-prepositional-phrase', conceptCode: 'c-prepositional-phrase', type: 'repair_error',
    objective: 'Detect and correct a case error after a preposition.',
    prompt: 'Find and fix the error: "الكتابُ على الطاولةُ" (intended: "The book is on the table").', difficulty: 2,
    expectedAnswer: 'الطاولةِ (genitive, not nominative) — على governs the noun that follows it.',
    hints: ['Look at the last word — what governs it?', 'Prepositions always require genitive.'],
    explanation: 'الطاولة must be genitive (الطاولةِ) because it follows the preposition على — the sentence-final position does not exempt it from government.',
    estimatedSeconds: 30,
  },
];
