import type { ExerciseSeed } from '../exerciseTypes';

export const morphologyExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-root-pattern', conceptCode: 'c-root-and-pattern', type: 'identify_role',
    objective: 'Extract a shared root from related words.',
    prompt: 'كَاتِب، مَكْتُوب، كِتَابَة، مَكْتَب all share what three-letter root?', difficulty: 1,
    expectedAnswer: 'ك ت ب', acceptedVariants: ['ktb', 'كتب'],
    hints: ['Strip away any prefixes (م) and look at the three consonants that remain in each word.'],
    explanation: 'All four words are built from ك ت ب ("writing") poured into different patterns.', estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-root-pattern', conceptCode: 'c-root-and-pattern', type: 'construct_from_root',
    objective: 'Apply a known pattern to a new root.',
    prompt: 'The pattern فَاعِل names "the one who does the action." Apply it to the root ل ع ب ("playing"). What word results, and what does it mean?', difficulty: 2,
    expectedAnswer: 'لَاعِب — player, one who plays.', acceptedVariants: ['لاعب'],
    hints: ['Slot ل، ع، ب into ف، ع، ل\'s three consonant slots.'],
    explanation: 'لاعب follows exactly the same فاعل template as كاتب, just with a different root.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'complete_paradigm',
    objective: 'Produce Form I\'s three main derived nouns from a root.',
    prompt: 'From the root ف ه م ("understanding"), give the Form I verb, its active participle, and its passive participle.', difficulty: 2,
    expectedAnswer: 'فَهِمَ (understood), فَاهِم (one who understands), مَفْهُوم (understood; a concept).',
    hints: ['Use the same three patterns you saw for ك ت ب: فَعَلَ، فَاعِل، مَفْعُول.'],
    explanation: 'Once you know Form I\'s three core patterns, you can generate this whole family for almost any sound root.', estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'identify_role',
    objective: 'Distinguish a Form I verb\'s active participle from its passive participle.',
    prompt: 'From root ف ت ح ("opening"): فَاتِح and مَفْتُوح are both derived nouns. Which one means "opened" (the thing acted upon), and which means "one who opens"?', difficulty: 2,
    expectedAnswer: 'فَاتِح = "one who opens" (active participle); مَفْتُوح = "opened" (passive participle).',
    invalidPlausible: [{ answer: 'Both mean the same thing', why: 'The فَاعِل pattern always names the doer; the مَفْعُول pattern always names the one acted upon — they are never interchangeable.' }],
    hints: ['فَاعِل-shaped words name who does the action.', 'مَفْعُول-shaped words name what receives the action.'],
    explanation: 'فَاتِح follows the فَاعِل (active participle) pattern — the doer. مَفْتُوح follows the مَفْعُول (passive participle) pattern — the thing done to.',
    misconceptionTags: [], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'explain_rule',
    objective: 'Explain why Form I\'s مصدر cannot be derived by a single formula.',
    prompt: 'Forms II–X each have one predictable مصدر pattern, but Form I does not — كَتَبَ gives كِتَابَة while فَهِمَ gives فَهْم. Why can\'t Form I\'s مصدر be produced by a formula the way the derived forms\' can?', difficulty: 3,
    expectedAnswer: 'Because Form I is the underived base form: several مصدر shapes (فَعْل، فِعَالَة، فُعُول، and others) are all independently possible for it, and which one a given root uses has to be learned per verb rather than predicted from the root\'s letters alone.',
    hints: ['Forms II–X are built on top of Form I by adding a fixed extra element — that extra element is what makes their مصدر predictable.', 'Form I has nothing extra added to it, so nothing forces one مصدر shape over another.'],
    explanation: 'Predictability in the derived forms comes from the extra prefix/infix/doubling each one adds, which fixes its مصدر shape. Form I has no such addition, so multiple مصدر patterns remain historically available and must be memorized per verb.',
    misconceptionTags: [], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-derived-forms', conceptCode: 'c-derived-forms', sentenceCode: 'morph-01-form2-causative', type: 'explain_rule',
    objective: 'Explain a Form II meaning shift.',
    prompt: 'دَرَسَ means "he studied." دَرَّسَ means "he taught." What did doubling the middle radical accomplish semantically?', difficulty: 3,
    expectedAnswer: 'Form II often adds a causative sense: "caused [someone] to study" → "taught."',
    hints: ['Think about who is doing what to whom in each version.'],
    explanation: 'This causative shift is one of Form II\'s most reliable meaning tendencies.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-derived-forms', conceptCode: 'c-derived-forms', sentenceCode: 'morph-02-form5-reflexive', type: 'compare_analyses',
    objective: 'Contrast Form II and Form V meanings on the same root.',
    prompt: 'عَلَّمَ (Form II) means "he taught." تَعَلَّمَ (Form V) means "he learned." What did adding the ت- prefix accomplish?', difficulty: 3,
    expectedAnswer: 'Form V often makes a Form II verb reflexive: "caused himself to know" → "learned."',
    hints: ['Compare who benefits from the action in each version.'],
    explanation: 'This II→V reflexive relationship recurs across many roots, not just علم.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-derived-forms', conceptCode: 'c-derived-forms', sentenceCode: 'morph-04-form7-vs-form1-transitivity', type: 'transform_word',
    objective: 'Derive a Form VII intransitive from a Form I transitive verb.',
    prompt: 'كَسَرَ الْوَلَدُ الْبَابَ ("The boy broke the door") — give the Form VII verb meaning "it broke" (intransitively), from the same root.', difficulty: 3,
    expectedAnswer: 'انْكَسَرَ', acceptedVariants: ['انكسر'],
    hints: ['Form VII is انْفَعَلَ — apply ك س ر to that template.'],
    explanation: 'انكسر lets you describe الباب undergoing the breaking without needing to restate an agent.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', type: 'identify_role',
    objective: 'Distinguish a word\'s pattern from its syntactic role.',
    prompt: 'الْكَاتِبُ حَاضِرٌ ("The writer is present"). كاتب is shaped like an اسم فاعل. What syntactic role does it actually play in this sentence?', difficulty: 3,
    expectedAnswer: 'مبتدأ (not فاعل) — this is a nominal sentence, and كاتب is simply its topic.',
    hints: ['Check the sentence type first: nominal or verbal?'],
    explanation: 'A word\'s pattern (اسم فاعل) never automatically tells you its syntactic role in a specific sentence — that always has to be checked separately.',
    misconceptionTags: ['mis-faail-vs-ism-al-faail', 'mis-pattern-vs-role'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', type: 'construct_from_root',
    objective: 'Produce both participles from a root.',
    prompt: 'Give the active and passive participles of the root س م ع ("hearing").', difficulty: 2,
    expectedAnswer: 'سَامِع (active, "hearer") and مَسْمُوع (passive, "heard; audible").',
    hints: ['Apply فَاعِل and مَفْعُول to س م ع.'],
    explanation: 'Both follow the standard Form I participle patterns.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-masdar', conceptCode: 'c-verbal-noun', type: 'identify_role',
    objective: 'Identify a مصدر and what it abstracts away.',
    prompt: 'كِتَابَة means "writing" with no doer and no time attached. What grammatical category is this word?', difficulty: 2,
    expectedAnswer: 'مصدر (verbal noun)', acceptedVariants: ['verbal noun', 'masdar'],
    hints: ['Compare it to كَتَبَ, which is locked to third-person past.'],
    explanation: 'المصدر names the bare action, stripped of person, gender, number, and tense — all of which the conjugated verb carries instead.', estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-masdar', conceptCode: 'c-verbal-noun', type: 'compare_analyses',
    objective: 'Recognize unpredictable Form-I مصدر shapes.',
    prompt: 'فَتَحَ\'s مصدر is فَتْح (فَعْل pattern), but دَرَسَ\'s مصدر is دِرَاسَة (فِعَالَة pattern) — different shapes for the same Form. Is Form I\'s مصدر pattern predictable the way its participles are?', difficulty: 3,
    expectedAnswer: 'No — Form I مصدر shapes must be learned per verb; unlike its active/passive participles (always فَاعِل/مَفْعُول), there is no single reliable Form I مصدر template.',
    hints: ['Compare how predictable فَاعِل is versus how many different مصدر shapes you have already seen.'],
    explanation: 'This unpredictability is a genuine, well-known irregularity of Form I specifically — later derived forms (II–X) are far more predictable in their مصدر shape.', estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-root-pattern', conceptCode: 'c-root-and-pattern', type: 'transform_word',
    objective: 'Apply the instrument-noun pattern to a familiar root.',
    prompt: 'The instrument-noun pattern مِفْعَال names "the tool used to do the action." Applied to ف ت ح ("opening"), what word results, and what does it mean?', difficulty: 2,
    expectedAnswer: 'مِفْتَاح — key (the tool of opening).', acceptedVariants: ['مفتاح'],
    hints: ['Slot ف، ت، ح into م، ف، ع، ا، ل\'s consonant slots.'],
    explanation: "This is the source of this app's own name: مِفْتَاح, \"key\" — the tool that opens something.", estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-derived-forms', conceptCode: 'c-derived-forms', type: 'explain_rule',
    objective: 'State a Form X meaning tendency.',
    prompt: 'عَلِمَ means "he knew." اسْتَعْلَمَ (Form X) means "he inquired." What meaning tendency does Form X often add?', difficulty: 3,
    expectedAnswer: 'Form X often means "to seek/ask for X" — here, "to seek to know."',
    hints: ['Think about the relationship between "knowing" and "asking to know."'],
    explanation: "Form X's \"seeking\" sense recurs across many roots (e.g. غفر → استغفر, \"to seek forgiveness\").", estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', sentenceCode: 'nom-07-idafa-passive-participle-khabar', type: 'identify_role',
    objective: 'Recognize a passive participle used as an ordinary adjective.',
    prompt: 'In بَابُ الْبَيْتِ مَفْتُوحٌ, what pattern is مفتوح, and what syntactic role does it play here?', difficulty: 2,
    expectedAnswer: 'It is a Form I passive participle (مَفْعُول pattern), and here it plays the role of خبر, used as an ordinary adjective meaning "open."',
    hints: ['Separate the two questions: what shape, and what job.'],
    explanation: 'مفتوح demonstrates that a passive participle behaves as a regular noun/adjective once formed — its case comes from its syntactic role, unrelated to its morphological shape.',
    misconceptionTags: ['mis-pattern-vs-role'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-masdar', conceptCode: 'c-verbal-noun', sentenceCode: 'morph-11-verbal-noun-reading', type: 'identify_role',
    objective: 'Contrast a مصدر with a conjugated verb from the same root.',
    prompt: 'الْقِرَاءَةُ مُفِيدَةٌ — what grammatical category is القراءة itself (independent of its role as مبتدأ here), and how does that differ from a conjugated verb like قَرَأَ؟', difficulty: 2,
    expectedAnswer: 'القراءة is a مصدر (verbal noun) — it names the action of reading without any person, gender, number, or tense, unlike قرأ, which is locked to third-person masculine singular past.',
    hints: ['Ask whether القراءة tells you who read, or when.'],
    explanation: 'Once formed, a مصدر behaves as an ordinary noun (here, as مبتدأ) even though it names an action.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', sentenceCode: 'morph-12-passive-participle-letter', type: 'identify_role',
    objective: 'Recognize a feminine passive participle used as an ordinary predicate.',
    prompt: 'In الرِّسَالَةُ مَكْتُوبَةٌ بِخَطٍّ جَمِيلٍ, what pattern is مكتوبة, and what syntactic role does it play?', difficulty: 2,
    expectedAnswer: 'It is a Form I passive participle (مَفْعُول pattern, feminine مَفْعُولة), and here it plays the role of خبر — an ordinary predicate adjective meaning "written."',
    hints: ['Separate the two questions: what shape is the word, and what job does it do in this specific sentence?'],
    explanation: 'Like مفتوح in nom-07, مكتوبة shows that a passive participle\'s case and role come from its syntactic position, not from its morphological shape.',
    misconceptionTags: ['mis-pattern-vs-role'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'transform_word',
    objective: 'Produce the imperfect of a فَعِلَ-type Form I verb.',
    prompt: 'فَهِمَ is a فَعِلَ-type Form I verb. Give its imperfect (يَفْعَلُ pattern).', difficulty: 2,
    expectedAnswer: 'يَفْهَمُ', acceptedVariants: ['يفهم'],
    hints: ['فَعِلَ verbs typically pair with a يَفْعَلُ imperfect.'],
    explanation: 'يَفْهَمُ follows the يَفْعَلُ pattern that tends to accompany a فَعِلَ-type Form I perfect.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'identify_role',
    objective: 'Name Form I\'s three middle-vowel subtypes.',
    prompt: 'Form I is not one single pattern but three vowel subtypes on its middle radical. What are they called?', difficulty: 2,
    expectedAnswer: 'فَعَلَ، فَعِلَ، فَعُلَ', acceptedVariants: ['fa\'ala, fa\'ila, fa\'ula'],
    hints: ['Compare كَتَبَ, فَهِمَ, and كَرُمَ — each has a different vowel on the middle letter.'],
    explanation: 'Which of the three a given root uses is not always predictable from the root alone, though it does tend to predict the imperfect\'s own middle vowel.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-form-i', conceptCode: 'c-form-i-verb', type: 'compare_analyses',
    objective: 'Recognize that the perfect-imperfect vowel link is a tendency, not a guarantee.',
    prompt: 'كَتَبَ (فَعَلَ-type) has imperfect يَكْتُبُ; فَهِمَ (فَعِلَ-type) has imperfect يَفْهَمُ. Does a Form I verb\'s perfect-tense vowel subtype reliably predict its imperfect vowel?', difficulty: 3,
    expectedAnswer: 'Only as a tendency, not a guaranteed rule — a فَعَلَ verb often has a يَفْعُلُ or يَفْعِلُ imperfect and a فَعِلَ verb often has a يَفْعَلُ imperfect, but exceptions exist and each verb\'s imperfect ultimately has to be confirmed, typically from a dictionary.',
    hints: ['Compare this to Form I\'s مصدر, which is also only partly predictable from the verb\'s shape.'],
    explanation: 'This mirrors Form I\'s مصدر unpredictability: Form I carries more irregularity than the derived forms precisely because it is the underived base.',
    estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', type: 'transform_word',
    objective: 'Produce an active participle from a Form I root.',
    prompt: 'Give the active participle (اسم الفاعل) of فَتَحَ ("to open").', difficulty: 1,
    expectedAnswer: 'فَاتِح', acceptedVariants: ['فاتح'],
    hints: ['Apply the فَاعِل pattern to ف ت ح.'],
    explanation: 'فَاتِح follows the standard Form I active-participle pattern فَاعِل.',
    estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-participles', conceptCode: 'c-active-passive-participle', type: 'compare_analyses',
    objective: 'Separate a participle\'s shape from any specific sentence role.',
    prompt: 'فَاتِح and فَتَحَ share the same root. Does فاتح, just by existing, mean it is functioning as فاعل in some sentence right now?', difficulty: 3,
    expectedAnswer: 'No — فاتح\'s shape only tells you it names "one who opens" in the abstract; whether it actually functions as فاعل, مبتدأ, or something else always depends on its position in a specific sentence.',
    hints: ['Compare to الكاتب حاضر, where كاتب (also فاعل-shaped) functions as مبتدأ, not فاعل.'],
    explanation: 'A word\'s pattern and its syntactic role are two separate questions — this is the single most-tested confusion in this unit.',
    misconceptionTags: ['mis-pattern-vs-role'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-masdar', conceptCode: 'c-verbal-noun', type: 'identify_role',
    objective: 'Recognize a مصدر functioning as mubtada inside an idafa.',
    prompt: 'In حُبُّ الْعِلْمِ مُهِمٌّ ("the love of knowledge is important"), what part of speech is حبّ, despite naming an emotion rather than a "thing"?', difficulty: 2,
    expectedAnswer: 'مصدر (verbal noun) — here functioning as the مبتدأ, and as مضاف in idafa with العلم.',
    hints: ['حبّ behaves exactly like any ordinary noun once formed, even though it names an action/state.'],
    explanation: 'المصدر is a full noun grammatically — it can be مبتدأ, مضاف, مفعول به, or anything else a noun can be, exactly as حبّ is here.',
    estimatedSeconds: 25,
  },
];
