import type { ExerciseSeed } from '../exerciseTypes';

export const nominalExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', sentenceCode: 'nom-01-mubtada-khabar-basic', type: 'identify_role',
    objective: 'Identify the مبتدأ in a nominal sentence.', prompt: 'In الطَّالِبُ مُجْتَهِدٌ, which word is the مبتدأ?',
    difficulty: 1, expectedAnswer: 'الطَّالِبُ', acceptedVariants: ['الطالب'],
    hints: ['The مبتدأ is what the sentence is about — usually the first, definite noun.'],
    explanation: 'الطَّالِبُ is the مبتدأ: definite, nominative, and the topic the rest of the sentence comments on.',
    estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', sentenceCode: 'nom-01-mubtada-khabar-basic', type: 'full_irab',
    objective: 'Perform full إعراب on a two-word nominal sentence.',
    prompt: 'Give the full إعراب of الطَّالِبُ مُجْتَهِدٌ (role + case + marker for each word).', difficulty: 2,
    expectedAnswer: 'الطالبُ: مبتدأ مرفوع وعلامة رفعه الضمة. مُجتهدٌ: خبر مرفوع وعلامة رفعه الضمة المنونة.',
    hints: ['Name each word\'s role first, then its case, then its marker.'],
    explanation: 'Both words are nominative — الطالب as مبتدأ (visible ḍammah), مجتهد as خبر (ḍammah + tanwīn since it is indefinite).',
    estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-khabar-types', conceptCode: 'c-khabar-types', sentenceCode: 'nom-04-khabar-shibh-jumla', type: 'compare_analyses',
    objective: 'Distinguish khabar types across sentences.',
    prompt: 'Is the خبر in الكِتَابُ عَلَى الطَّاولَةِ a single word, a prepositional phrase, or an embedded sentence? What about in الطَّالِبُ مُجْتَهِدٌ?', difficulty: 2,
    expectedAnswer: 'عَلَى الطَّاولَةِ is a prepositional-phrase khabar (شبه جملة); مُجْتَهِدٌ is a single-word khabar (مفرد).',
    hints: ['Count the words that make up each khabar and check whether one of them is a preposition.'],
    explanation: 'Recognizing which of the three khabar shapes you are looking at determines how to search for it inside longer sentences.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-definiteness', conceptCode: 'c-definiteness', type: 'identify_role',
    objective: 'Identify the source of a noun\'s definiteness.',
    prompt: 'What makes الطَّالِبِ definite in كِتَابُ الطَّالِبِ, since it takes no ال prefix issue here — wait, it does have ال. Rephrase: what makes كِتَابُ (the first word) definite, given it has no ال at all?', difficulty: 3,
    expectedAnswer: 'It inherits its definiteness from being the مضاف of an إضافة whose مضاف إليه (الطالب) is definite.',
    hints: ['Check the second noun\'s definiteness — idafa definiteness flows in one direction only.'],
    explanation: 'كتاب itself carries no ال and no تنوين; its definiteness is entirely borrowed from الطالب.',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-adjective-agreement', conceptCode: 'c-adjective-agreement', sentenceCode: 'nom-05-adjective-agreement-definite', type: 'complete_paradigm',
    objective: 'Produce all four agreement features for a نعت.',
    prompt: 'List all four features that المجتهد must match in الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ, and confirm each one.', difficulty: 3,
    expectedAnswer: 'Gender: masculine (matches). Number: singular (matches). Definiteness: definite via ال (matches). Case: nominative (matches).',
    hints: ['Go through gender, number, definiteness, and case one at a time — do not skip any.'],
    explanation: 'A نعت must match on all four features simultaneously; skipping even one check is the most common source of small، self-correctable errors at this stage.',
    misconceptionTags: ['mis-forgetting-adjective-agreement'], estimatedSeconds: 50,
  },
  {
    lessonCode: 'l-adjective-agreement', conceptCode: 'c-adjective-agreement', type: 'repair_error',
    objective: 'Detect a broken agreement feature.',
    prompt: 'Find the error: "طالبٌ المجتهدُ حاضرٌ" (intended: "The diligent student is present").', difficulty: 3,
    expectedAnswer: 'طالبٌ should be الطالبُ — you cannot mix an indefinite noun with a definite نعت.',
    invalidPlausible: [{ answer: 'حاضرٌ should be محضورٌ', why: 'حاضر is correctly an active participle here; the error is the definiteness mismatch between طالب and المجتهد, not the khabar.' }],
    hints: ['Check definiteness across the noun and its نعت.'],
    explanation: 'المجتهد is definite (has ال), so the noun it describes must also be definite — الطالب, not طالب.',
    misconceptionTags: ['mis-forgetting-adjective-agreement'], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-idafa', conceptCode: 'c-idafa', sentenceCode: 'nom-06-idafa-basic', type: 'construct_from_root',
    objective: 'Build an idafa phrase from two given nouns.',
    prompt: 'Combine بَاب and بَيْت into an إضافة meaning "the door of the house."', difficulty: 2,
    expectedAnswer: 'بَابُ الْبَيْتِ', acceptedVariants: ['باب البيت'],
    hints: ['The first noun (مضاف) takes no ال. The second noun (مضاف إليه) takes ال and is genitive.'],
    explanation: 'بَابُ الْبَيْتِ: بَابُ has no ال and no تنوين; الْبَيْتِ carries both the definiteness and the genitive ending.',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-idafa', conceptCode: 'c-idafa', type: 'repair_error',
    objective: 'Correct a common idafa definiteness error.',
    prompt: 'Find the error: "الكتابُ الطالبِ" (intended: "the student\'s book").', difficulty: 2,
    expectedAnswer: 'الكتابُ should be كِتَابُ — the مضاف can never take ال.',
    hints: ['The first noun in an idafa never takes ال, no matter how definite the whole phrase is.'],
    explanation: 'Correct: كِتَابُ الطَّالِبِ. Adding ال to both nouns of an idafa is one of the most common learner errors when transferring English\'s single "the."',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-dual-sound-plurals', conceptCode: 'c-dual-and-sound-plurals', sentenceCode: 'case-04-dual-predicate', type: 'transform_word',
    objective: 'Convert a singular noun to its dual form with correct case.',
    prompt: 'Give the nominative dual of الطَّالِبُ.', difficulty: 2,
    expectedAnswer: 'الطَّالِبَانِ', acceptedVariants: ['الطالبان'],
    hints: ['The nominative dual suffix is ـَانِ.'],
    explanation: 'الطالب + ـَانِ = الطَّالِبَانِ, replacing the singular\'s short-vowel case marker with the dual\'s dedicated suffix.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-dual-sound-plurals', conceptCode: 'c-dual-and-sound-plurals', sentenceCode: 'case-05-dual-accusative', type: 'transform_word',
    objective: 'Convert a nominative dual to accusative/genitive.',
    prompt: 'الطَّالِبَانِ is nominative. What is its accusative/genitive form?', difficulty: 2,
    expectedAnswer: 'الطَّالِبَيْنِ', acceptedVariants: ['الطالبين'],
    hints: ['The dual has only one non-nominative suffix, covering both other cases.'],
    explanation: 'ـَانِ (nominative) becomes ـَيْنِ for both accusative and genitive — the dual does not distinguish those two cases.',
    misconceptionTags: ['mis-marker-type-confusion'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-inna', conceptCode: 'c-inna-wa-akhawatuha', sentenceCode: 'part-01-inna-basic', type: 'transform_sentence',
    objective: 'Insert إنّ into a bare nominal sentence and adjust case.',
    prompt: 'Transform الطَّالِبُ مُجْتَهِدٌ by adding إنّ at the front. What changes?', difficulty: 2,
    expectedAnswer: 'إِنَّ الطَّالِبَ مُجْتَهِدٌ — الطالب shifts from nominative (مبتدأ) to accusative (اسم إنّ); مجتهد stays nominative (خبر إنّ).',
    hints: ['Only the noun immediately after إنّ is affected.'],
    explanation: 'إنّ governs only the noun immediately following it, turning the former مبتدأ into اسم إنّ (accusative), while the خبر is untouched.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-inna', conceptCode: 'c-inna-wa-akhawatuha', type: 'identify_governor',
    objective: 'Name the governor responsible for a case change.',
    prompt: 'In لَكِنَّ الطَّالِبَ غَائِبٌ, what specifically causes الطالبَ to be accusative?', difficulty: 2,
    expectedAnswer: 'لكنّ (a sister of إنّ)', acceptedVariants: ['لكن'],
    hints: ['Look immediately before the accusative noun.'],
    explanation: 'لكنّ governs exactly like إنّ, pushing the following noun into the accusative.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-kana', conceptCode: 'c-kana-wa-akhawatuha', sentenceCode: 'part-03-kana-basic', type: 'compare_analyses',
    objective: 'Contrast إنّ\'s and كان\'s targets.',
    prompt: 'إنّ governs the subject into the accusative. كان governs the predicate into the accusative. Using إِنَّ الطَّالِبَ مُجْتَهِدٌ and كَانَ الطَّالِبُ مُجْتَهِدًا, show exactly which word changes case in each.', difficulty: 3,
    expectedAnswer: 'With إنّ: الطالب becomes accusative (الطالبَ), مجتهد stays nominative. With كان: الطالب stays nominative, مجتهد becomes accusative (مجتهدًا).',
    hints: ['Track الطالب and مجتهد separately across both transformed sentences.'],
    explanation: 'This side-by-side contrast is the fastest way to stop confusing which of the two governors touches which word.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 50,
  },
  {
    lessonCode: 'l-kana', conceptCode: 'c-kana-wa-akhawatuha', sentenceCode: 'part-05-laysa-negation', type: 'transform_sentence',
    objective: 'Negate a nominal sentence using ليس and adjust case.',
    prompt: 'Use ليس to negate الطَّالِبُ غَائِبٌ ("The student is absent"), producing "The student is not absent."', difficulty: 2,
    expectedAnswer: 'لَيْسَ الطَّالِبُ غَائِبًا', acceptedVariants: ['ليس الطالب غائبا'],
    hints: ['ليس keeps the subject nominative and pushes the predicate accusative, exactly like كان.'],
    explanation: 'غَائِبٌ (nominative khabar) becomes غَائِبًا (accusative خبر ليس) once ليس enters the sentence.',
    estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', type: 'teach_back',
    objective: 'Explain the mubtada/khabar rule in the learner\'s own words.',
    prompt: 'Explain to a beginner, in your own words, why both words in الطَّالِبُ مُجْتَهِدٌ are nominative even though there is no verb and no preposition in sight.', difficulty: 2,
    expectedAnswer: 'Nominative is the default case for a bare nominal sentence — both مبتدأ and خبر start out nominative unless a governing particle intervenes.',
    hints: ['Think about what "default" means versus what needs an active governor.'],
    explanation: 'Correct explanations should mention that nominative here needs no governor — it is simply the sentence\'s baseline state.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-khabar-types', conceptCode: 'c-khabar-types', type: 'analyze_passage',
    objective: 'Identify a full embedded-sentence khabar.',
    prompt: 'In الطُّلَّابُ كَتَبُوا الدَّرْسَ, identify the خبر of الطلاب and explain what kind of khabar it is.', difficulty: 3,
    expectedAnswer: 'كَتَبُوا الدَّرْسَ is the khabar — a full embedded verbal sentence (جملة فعلية في محل رفع خبر).',
    hints: ['The khabar here is not a single word or a prepositional phrase — look at how many words, and what kind, follow الطلاب.'],
    explanation: 'Recognizing an embedded verbal sentence as a single khabar unit is essential once sentences grow past two or three words.',
    estimatedSeconds: 45,
  },
];
