import type { ExerciseSeed } from '../exerciseTypes';

export const nominalExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', sentenceCode: 'nom-01-mubtada-khabar-basic', type: 'identify_role',
    objective: 'Identify the مبتدأ in a nominal sentence.', prompt: 'In الطَّالِبُ مُجْتَهِدٌ, which word is the مبتدأ?',
    difficulty: 1, expectedAnswer: 'الطَّالِبُ', acceptedVariants: ['الطالب'],
    hints: ['The مبتدأ is what the sentence is about — usually the first, definite noun.'],
    explanation: 'الطَّالِبُ is the مبتدأ: definite, nominative, and the topic the rest of the sentence comments on.',
    estimatedSeconds: 15,
  },
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', sentenceCode: 'nom-01-mubtada-khabar-basic', type: 'full_irab',
    objective: 'Perform full إعراب on a two-word nominal sentence.',
    prompt: 'Give the full إعراب of الطَّالِبُ مُجْتَهِدٌ (role + case + marker for each word).', difficulty: 2,
    expectedAnswer: 'الطالبُ: مبتدأ مرفوع وعلامة رفعه الضمة. مُجتهدٌ: خبر مرفوع وعلامة رفعه الضمة المنونة.',
    hints: ['Name each word\'s role first, then its case, then its marker.'],
    explanation: 'Both words are nominative — الطالب as مبتدأ (visible ḍammah), مجتهد as خبر (ḍammah + tanwīn since it is indefinite).',
    estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-khabar-types', conceptCode: 'c-khabar-types', sentenceCode: 'nom-04-khabar-shibh-jumla', type: 'compare_analyses',
    objective: 'Distinguish khabar types across sentences.',
    prompt: 'Is the خبر in الكِتَابُ عَلَى الطَّاولَةِ a single word, a prepositional phrase, or an embedded sentence? What about in الطَّالِبُ مُجْتَهِدٌ?', difficulty: 2,
    expectedAnswer: 'عَلَى الطَّاولَةِ is a prepositional-phrase khabar (شبه جملة); مُجْتَهِدٌ is a single-word khabar (مفرد).',
    hints: ['Count the words that make up each khabar and check whether one of them is a preposition.'],
    explanation: 'Recognizing which of the three khabar shapes you are looking at determines how to search for it inside longer sentences.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-definiteness', conceptCode: 'c-definiteness', type: 'identify_role',
    objective: 'Identify the source of a noun\'s definiteness.',
    prompt: 'What makes الطَّالِبِ definite in كِتَابُ الطَّالِبِ, since it takes no ال prefix issue here — wait, it does have ال. Rephrase: what makes كِتَابُ (the first word) definite, given it has no ال at all?', difficulty: 3,
    expectedAnswer: 'It inherits its definiteness from being the مضاف of an إضافة whose مضاف إليه (الطالب) is definite.',
    hints: ['Check the second noun\'s definiteness — idafa definiteness flows in one direction only.'],
    explanation: 'كتاب itself carries no ال and no تنوين; its definiteness is entirely borrowed from الطالب.',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-adjective-agreement', conceptCode: 'c-adjective-agreement', sentenceCode: 'nom-05-adjective-agreement-definite', type: 'complete_paradigm',
    objective: 'Produce all four agreement features for a نعت.',
    prompt: 'List all four features that المجتهد must match in الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ, and confirm each one.', difficulty: 3,
    expectedAnswer: 'Gender: masculine (matches). Number: singular (matches). Definiteness: definite via ال (matches). Case: nominative (matches).',
    hints: ['Go through gender, number, definiteness, and case one at a time — do not skip any.'],
    explanation: 'A نعت must match on all four features simultaneously; skipping even one check is the most common source of small، self-correctable errors at this stage.',
    misconceptionTags: ['mis-forgetting-adjective-agreement'], estimatedSeconds: 50,
  },
  {
    lessonCode: 'l-adjective-agreement', conceptCode: 'c-adjective-agreement', type: 'repair_error',
    objective: 'Detect a broken agreement feature.',
    prompt: 'Find the error: "طالبٌ المجتهدُ حاضرٌ" (intended: "The diligent student is present").', difficulty: 3,
    expectedAnswer: 'طالبٌ should be الطالبُ — you cannot mix an indefinite noun with a definite نعت.',
    invalidPlausible: [{ answer: 'حاضرٌ should be محضورٌ', why: 'حاضر is correctly an active participle here; the error is the definiteness mismatch between طالب and المجتهد, not the khabar.' }],
    hints: ['Check definiteness across the noun and its نعت.'],
    explanation: 'المجتهد is definite (has ال), so the noun it describes must also be definite — الطالب, not طالب.',
    misconceptionTags: ['mis-forgetting-adjective-agreement'], estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-idafa', conceptCode: 'c-idafa', sentenceCode: 'nom-06-idafa-basic', type: 'construct_from_root',
    objective: 'Build an idafa phrase from two given nouns.',
    prompt: 'Combine بَاب and بَيْت into an إضافة meaning "the door of the house."', difficulty: 2,
    expectedAnswer: 'بَابُ الْبَيْتِ', acceptedVariants: ['باب البيت'],
    hints: ['The first noun (مضاف) takes no ال. The second noun (مضاف إليه) takes ال and is genitive.'],
    explanation: 'بَابُ الْبَيْتِ: بَابُ has no ال and no تنوين; الْبَيْتِ carries both the definiteness and the genitive ending.',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-idafa', conceptCode: 'c-idafa', type: 'repair_error',
    objective: 'Correct a common idafa definiteness error.',
    prompt: 'Find the error: "الكتابُ الطالبِ" (intended: "the student\'s book").', difficulty: 2,
    expectedAnswer: 'الكتابُ should be كِتَابُ — the مضاف can never take ال.',
    hints: ['The first noun in an idafa never takes ال, no matter how definite the whole phrase is.'],
    explanation: 'Correct: كِتَابُ الطَّالِبِ. Adding ال to both nouns of an idafa is one of the most common learner errors when transferring English\'s single "the."',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-dual-sound-plurals', conceptCode: 'c-dual-and-sound-plurals', sentenceCode: 'case-04-dual-predicate', type: 'transform_word',
    objective: 'Convert a singular noun to its dual form with correct case.',
    prompt: 'Give the nominative dual of الطَّالِبُ.', difficulty: 2,
    expectedAnswer: 'الطَّالِبَانِ', acceptedVariants: ['الطالبان'],
    hints: ['The nominative dual suffix is ـَانِ.'],
    explanation: 'الطالب + ـَانِ = الطَّالِبَانِ, replacing the singular\'s short-vowel case marker with the dual\'s dedicated suffix.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-dual-sound-plurals', conceptCode: 'c-dual-and-sound-plurals', sentenceCode: 'case-05-dual-accusative', type: 'transform_word',
    objective: 'Convert a nominative dual to accusative/genitive.',
    prompt: 'الطَّالِبَانِ is nominative. What is its accusative/genitive form?', difficulty: 2,
    expectedAnswer: 'الطَّالِبَيْنِ', acceptedVariants: ['الطالبين'],
    hints: ['The dual has only one non-nominative suffix, covering both other cases.'],
    explanation: 'ـَانِ (nominative) becomes ـَيْنِ for both accusative and genitive — the dual does not distinguish those two cases.',
    misconceptionTags: ['mis-marker-type-confusion'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-inna', conceptCode: 'c-inna-wa-akhawatuha', sentenceCode: 'part-01-inna-basic', type: 'transform_sentence',
    objective: 'Insert إنّ into a bare nominal sentence and adjust case.',
    prompt: 'Transform الطَّالِبُ مُجْتَهِدٌ by adding إنّ at the front. What changes?', difficulty: 2,
    expectedAnswer: 'إِنَّ الطَّالِبَ مُجْتَهِدٌ — الطالب shifts from nominative (مبتدأ) to accusative (اسم إنّ); مجتهد stays nominative (خبر إنّ).',
    hints: ['Only the noun immediately after إنّ is affected.'],
    explanation: 'إنّ governs only the noun immediately following it, turning the former مبتدأ into اسم إنّ (accusative), while the خبر is untouched.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-inna', conceptCode: 'c-inna-wa-akhawatuha', type: 'identify_governor',
    objective: 'Name the governor responsible for a case change.',
    prompt: 'In لَكِنَّ الطَّالِبَ غَائِبٌ, what specifically causes الطالبَ to be accusative?', difficulty: 2,
    expectedAnswer: 'لكنّ (a sister of إنّ)', acceptedVariants: ['لكن'],
    hints: ['Look immediately before the accusative noun.'],
    explanation: 'لكنّ governs exactly like إنّ, pushing the following noun into the accusative.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-kana', conceptCode: 'c-kana-wa-akhawatuha', sentenceCode: 'part-03-kana-basic', type: 'compare_analyses',
    objective: 'Contrast إنّ\'s and كان\'s targets.',
    prompt: 'إنّ governs the subject into the accusative. كان governs the predicate into the accusative. Using إِنَّ الطَّالِبَ مُجْتَهِدٌ and كَانَ الطَّالِبُ مُجْتَهِدًا, show exactly which word changes case in each.', difficulty: 3,
    expectedAnswer: 'With إنّ: الطالب becomes accusative (الطالبَ), مجتهد stays nominative. With كان: الطالب stays nominative, مجتهد becomes accusative (مجتهدًا).',
    hints: ['Track الطالب and مجتهد separately across both transformed sentences.'],
    explanation: 'This side-by-side contrast is the fastest way to stop confusing which of the two governors touches which word.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 50,
  },
  {
    lessonCode: 'l-kana', conceptCode: 'c-kana-wa-akhawatuha', sentenceCode: 'part-05-laysa-negation', type: 'transform_sentence',
    objective: 'Negate a nominal sentence using ليس and adjust case.',
    prompt: 'Use ليس to negate الطَّالِبُ غَائِبٌ ("The student is absent"), producing "The student is not absent."', difficulty: 2,
    expectedAnswer: 'لَيْسَ الطَّالِبُ غَائِبًا', acceptedVariants: ['ليس الطالب غائبا'],
    hints: ['ليس keeps the subject nominative and pushes the predicate accusative, exactly like كان.'],
    explanation: 'غَائِبٌ (nominative khabar) becomes غَائِبًا (accusative خبر ليس) once ليس enters the sentence.',
    estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-mubtada-khabar', conceptCode: 'c-mubtada-khabar', type: 'teach_back',
    objective: 'Explain the mubtada/khabar rule in the learner\'s own words.',
    prompt: 'Explain to a beginner, in your own words, why both words in الطَّالِبُ مُجْتَهِدٌ are nominative even though there is no verb and no preposition in sight.', difficulty: 2,
    expectedAnswer: 'Nominative is the default case for a bare nominal sentence — both مبتدأ and خبر start out nominative unless a governing particle intervenes.',
    hints: ['Think about what "default" means versus what needs an active governor.'],
    explanation: 'Correct explanations should mention that nominative here needs no governor — it is simply the sentence\'s baseline state.',
    estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-khabar-types', conceptCode: 'c-khabar-types', type: 'analyze_passage',
    objective: 'Identify a full embedded-sentence khabar.',
    prompt: 'In الطُّلَّابُ كَتَبُوا الدَّرْسَ, identify the خبر of الطلاب and explain what kind of khabar it is.', difficulty: 3,
    expectedAnswer: 'كَتَبُوا الدَّرْسَ is the khabar — a full embedded verbal sentence (جملة فعلية في محل رفع خبر).',
    hints: ['The khabar here is not a single word or a prepositional phrase — look at how many words, and what kind, follow الطلاب.'],
    explanation: 'Recognizing an embedded verbal sentence as a single khabar unit is essential once sentences grow past two or three words.',
    estimatedSeconds: 45,
  },
  {
    conceptCode: 'c-personal-pronouns', sentenceCode: 'nom-09-pronoun-mubtada-plural-khabar', type: 'identify_role',
    objective: 'Recognize that detached pronouns are مبني.',
    prompt: 'In نَحْنُ طُلَّابٌ مُجْتَهِدُونَ, what part of speech is نحن, and can it ever take a visible case ending?', difficulty: 2,
    expectedAnswer: 'نحن is a detached personal pronoun; it is مبني (built) and never takes a visible case ending, even though it is assigned a grammatical role (here، مبتدأ) and an estimated case (nominative).',
    hints: ['Compare نحن to a demonstrative like هذا — do either of them change their final letter for case?'],
    explanation: 'Detached personal pronouns are always مبني, just like demonstratives — their case is assigned but never shown by a changing vowel.',
    misconceptionTags: ['mis-case-on-indeclinables'], estimatedSeconds: 25,
  },
  {
    conceptCode: 'c-adjective-agreement', sentenceCode: 'nom-09-pronoun-mubtada-plural-khabar', type: 'compare_analyses',
    objective: 'Confirm agreement across mismatched plural mechanisms.',
    prompt: 'طُلَّابٌ (a broken plural) takes the نعت مُجْتَهِدُونَ (a sound masculine plural), not a broken-plural adjective. Does this break the four-feature agreement rule?', difficulty: 3,
    expectedAnswer: 'No — مجتهدون still agrees with طلاب in gender, number, definiteness, and case; it simply realizes "plural" through the sound-plural mechanism rather than a matching broken-plural shape, which is normal for human-referring nouns.',
    hints: ['Check all four features separately rather than checking whether the two words "look" like the same plural type.'],
    explanation: 'Agreement is about matching features (gender/number/definiteness/case), not about the two words sharing the exact same morphological plural strategy.',
    estimatedSeconds: 35,
  },
  {
    conceptCode: 'c-questions', sentenceCode: 'nom-10-interrogative-khabar-muqaddam', type: 'identify_role',
    objective: 'Separate word order from grammatical role in a question.',
    prompt: 'In أَيْنَ الْمُعَلِّمُ؟, which word is the مبتدأ and which is the خبر, given that أين comes first?', difficulty: 2,
    expectedAnswer: 'المعلم is the مبتدأ (delayed, مبتدأ مؤخر); أين is the خبر (fronted, خبر مقدم) — interrogatives like أين must open their sentence regardless of their grammatical role.',
    hints: ['Word order and grammatical role are not the same thing — ask which word the sentence is fundamentally "about."'],
    explanation: 'أين is obligatorily fronted because it is an interrogative, but it is still functioning as the predicate, not the subject.',
    misconceptionTags: ['mis-english-word-order-decisive'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-dual-sound-plurals', conceptCode: 'c-dual-and-sound-plurals', sentenceCode: 'nom-11-dual-teachers-busy', type: 'transform_word',
    objective: 'Convert a nominative dual to accusative/genitive.',
    prompt: 'Give the accusative/genitive dual of الْمُعَلِّمَانِ.', difficulty: 2,
    expectedAnswer: 'الْمُعَلِّمَيْنِ', acceptedVariants: ['المعلمين'],
    hints: ['The dual has one suffix for nominative, and a different single suffix shared by both other cases.'],
    explanation: 'ـَانِ (nominative) becomes ـَيْنِ for both accusative and genitive, exactly as with الطالبان/الطالبين.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-idafa', conceptCode: 'c-idafa', sentenceCode: 'nom-12-idafa-chain', type: 'explain_rule',
    objective: 'Explain the double role of a middle term in an idafa chain.',
    prompt: 'In بَابُ بَيْتِ الطَّالِبِ مَفْتُوحٌ, بَيْتِ has no ال and no تنوين, yet it is genitive. Explain both facts about بيت at once.', difficulty: 4,
    expectedAnswer: 'بيت is genitive because it is مضاف إليه of باب; it has no ال or تنوين because it is simultaneously مضاف to الطالب — every middle term of an idafa chain is both مضاف إليه (to what precedes) and مضاف (to what follows).',
    hints: ['بيت is playing two idafa roles at once — name both.'],
    explanation: 'This double role for middle terms is exactly what makes a three-or-more-term idafa chain different from a simple two-term idafa.',
    misconceptionTags: ['mis-idafa-definiteness'], estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-kana', conceptCode: 'c-kana-wa-akhawatuha', sentenceCode: 'part-07-asbaha-weather-cold', type: 'identify_governor',
    objective: 'Name the governor responsible for a case change among كان\'s sisters.',
    prompt: 'In أَصْبَحَ الْجَوُّ بَارِدًا, what specifically causes بَارِدًا to be accusative?', difficulty: 2,
    expectedAnswer: 'أصبح (a sister of كان)', acceptedVariants: ['اصبح'],
    hints: ['Look at the verb that opens the sentence — is it an ordinary action verb or one of the "deficient" verbs?'],
    explanation: 'أصبح governs exactly like كان: subject stays nominative, predicate becomes accusative.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-inna', conceptCode: 'c-inna-wa-akhawatuha', sentenceCode: 'part-08-laalla-hope', type: 'compare_analyses',
    objective: 'Separate meaning from case government among إنّ\'s sisters.',
    prompt: 'إنّ expresses emphasis; لعلّ expresses hope or expectation. Do they govern case differently?', difficulty: 3,
    expectedAnswer: 'No — لعلّ governs exactly like إنّ (following noun accusative, predicate nominative); only the added meaning (hope/expectation vs. emphasis) differs, not the case government.',
    hints: ['Separate "what a sister of إنّ means" from "what a sister of إنّ does grammatically."'],
    explanation: 'All of إنّ\'s sisters share the same case-government behavior; they differ only in the shade of meaning each adds.',
    estimatedSeconds: 30,
  },
];
