import type { ExerciseSeed } from '../exerciseTypes';

export const verbalExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-verb-subject', conceptCode: 'c-fi-l-fa-il', sentenceCode: 'verb-01-basic-vso', type: 'identify_role',
    objective: 'Identify the فاعل using case, not position.',
    prompt: 'In كَتَبَ الطَّالِبُ الدَّرْسَ, which word is the فاعل, and how do you know — not by position, but by ending?', difficulty: 1,
    expectedAnswer: 'الطَّالِبُ, because it is nominative (ḍammah).', acceptedVariants: ['الطالب'],
    invalidPlausible: [{ answer: 'الدَّرْسَ, because it comes right after الطالب and could look object-like in English word order', why: 'الدرس is accusative (fatḥah), which marks it as مفعول به, not فاعل — case, not position, decides the role.' }],
    hints: ['Check each noun\'s final vowel before deciding.'],
    explanation: 'الطَّالِبُ is nominative, which is how you know it is the فاعل — regardless of the fact that an English translation would put "student" and "lesson" in a different structural relationship.',
    misconceptionTags: ['mis-first-noun-is-subject', 'mis-english-word-order-decisive'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-verb-subject', conceptCode: 'c-fi-l-fa-il', type: 'identify_role',
    objective: 'Use case, not translated position, to find the فاعل.',
    prompt: 'رَأَى الْمُعَلِّمَ الطَّالِبُ. Who saw whom? (Careful — this is not simple VSO order in translation.)', difficulty: 3,
    expectedAnswer: 'الطَّالِبُ (nominative) is the فاعل: "The student saw the teacher." الْمُعَلِّمَ is accusative, the مفعول به.',
    hints: ['Do not assume the first noun after the verb is the subject — check both nouns\' case endings.'],
    explanation: 'Word order shifted here for emphasis, but case marking is unaffected: الْمُعَلِّمَ (accusative) is still the object, and الطَّالِبُ (nominative) is still the subject, regardless of order.',
    misconceptionTags: ['mis-first-noun-is-subject', 'mis-english-word-order-decisive'], estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-verb-agreement', conceptCode: 'c-verb-subject-agreement', sentenceCode: 'verb-03-plural-subject-singular-verb', type: 'select_ending',
    objective: 'Choose the correct verb form for a following plural subject.',
    prompt: 'Choose the correct verb: ___ الطُّلَّابُ الدَّرْسَ (كَتَبَ / كَتَبُوا)', difficulty: 2,
    expectedAnswer: 'كَتَبَ', acceptedVariants: ['كتب'], choices: ['كَتَبَ', 'كَتَبُوا'],
    invalidPlausible: [{ answer: 'كَتَبُوا', why: 'Fully agreeing plural verb forms are only used when the subject is fronted before the verb, not in default VSO order.' }],
    hints: ['Is the subject before or after the verb here?'],
    explanation: 'When the فاعل follows the verb (the default order), the verb stays grammatically singular even for a plural subject.',
    misconceptionTags: [], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-verb-agreement', conceptCode: 'c-verb-subject-agreement', sentenceCode: 'verb-04-fronted-subject-full-agreement', type: 'transform_sentence',
    objective: 'Front a subject and adjust verb agreement accordingly.',
    prompt: 'Rewrite كَتَبَ الطُّلَّابُ الدَّرْسَ by moving الطلاب to the front of the sentence. What must change on the verb?', difficulty: 3,
    expectedAnswer: 'الطُّلَّابُ كَتَبُوا الدَّرْسَ — the verb must now fully agree (كَتَبُوا) because the subject is fronted and the verb carries its own attached pronoun.',
    hints: ['Once the subject leads, the verb needs its own attached subject marker matching that noun.'],
    explanation: 'Fronting الطلاب makes this a nominal sentence whose khabar is the verbal sentence كتبوا الدرس — and that embedded verb must fully agree with its own (now redundant but grammatically required) attached pronoun.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-verb-agreement', conceptCode: 'c-verb-subject-agreement', sentenceCode: 'verb-05-feminine-intransitive', type: 'select_ending',
    objective: 'Apply gender agreement even in default verb-first order.',
    prompt: 'Choose the correct verb form: ___ الطَّالِبَةُ إِلَى الْمَدْرَسَةِ (ذَهَبَ / ذَهَبَتْ)', difficulty: 2,
    expectedAnswer: 'ذَهَبَتْ', acceptedVariants: ['ذهبت'], choices: ['ذَهَبَ', 'ذَهَبَتْ'],
    invalidPlausible: [{ answer: 'ذَهَبَ', why: 'Gender agreement (unlike number agreement) is required even when the verb precedes its subject.' }],
    hints: ['Number agreement is suspended before the subject, but is gender agreement also suspended?'],
    explanation: 'Verb-subject agreement suspends full number agreement before the subject, but gender agreement still applies: ذهبت, not ذهب, because الطالبة is feminine.',
    misconceptionTags: [], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-maful-bihi', conceptCode: 'c-maful-bihi', sentenceCode: 'verb-07-intransitive-no-object', type: 'identify_role',
    objective: 'Recognize an intransitive verb that takes no مفعول به.',
    prompt: 'Does جَلَسَ الْوَلَدُ have a مفعول به? Why or why not?', difficulty: 1,
    expectedAnswer: 'No — جلس is intransitive (لازم); the sentence is complete with just a فاعل.',
    hints: ['Check whether anything in the sentence is accusative.'],
    explanation: 'جلس needs no direct object to be a complete, meaningful sentence — not every verb requires a مفعول به.',
    estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-maful-bihi', conceptCode: 'c-maful-bihi', sentenceCode: 'verb-10-ditransitive', type: 'identify_role',
    objective: 'Identify both objects of a ditransitive verb.',
    prompt: 'أَعْطَى الْمُعَلِّمُ الطَّالِبَ كِتَابًا — name both مفعول به words and their case.', difficulty: 3,
    expectedAnswer: 'الطَّالِبَ (first مفعول به, accusative) and كِتَابًا (second مفعول به, accusative). Both are accusative — Arabic does not case-mark them differently the way English marks direct vs. indirect objects.',
    hints: ['Look for every accusative-marked noun after the verb and subject.'],
    explanation: 'Verbs of giving take two objects, both accusative, with no separate case for "indirect object" the way some other languages have.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-passive', conceptCode: 'c-passive-voice', sentenceCode: 'pass-01-anchor', type: 'transform_sentence',
    objective: 'Convert an active sentence to passive and track the case shift.',
    prompt: 'Convert كَتَبَ الطَّالِبُ الدَّرْسَ to the passive voice, omitting the agent.', difficulty: 2,
    expectedAnswer: 'كُتِبَ الدَّرْسُ — الدرس shifts from accusative مفعول به to nominative نائب الفاعل; الطالب (the agent) is dropped entirely.',
    hints: ['The internal vowels of the verb shift to a fixed passive pattern.', 'The former object is promoted; the agent disappears.'],
    explanation: 'كُتِبَ الدَّرْسُ: the vowel pattern shifts, the case of الدرس changes from accusative to nominative, and no agent is stated.',
    estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-passive', conceptCode: 'c-passive-voice', sentenceCode: 'pass-03-two-object-verb-passive', type: 'compare_analyses',
    objective: 'Determine which object is promoted in a ditransitive passive.',
    prompt: 'أَعْطَى الْمُعَلِّمُ الطَّالِبَ كِتَابًا becomes أُعْطِيَ الطَّالِبُ كِتَابًا in the passive. Which object was promoted to نائب الفاعل, and which stayed accusative?', difficulty: 4,
    expectedAnswer: 'الطَّالِبُ (the recipient, first object) is promoted to نائب الفاعل; كِتَابًا (the thing given, second object) stays accusative.',
    hints: ['Only one of the two objects changes case in the passive version — which one?'],
    explanation: 'With ditransitive verbs, the first (recipient) object is normally promoted, while the second remains an ordinary accusative object.',
    estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-passive', conceptCode: 'c-passive-voice', type: 'repair_error',
    objective: 'Correct a passive-voice case error.',
    prompt: 'Find the error: "كُتِبَ الدَّرْسَ" (intended: "The lesson was written").', difficulty: 2,
    expectedAnswer: 'الدَّرْسَ should be الدَّرْسُ — the نائب الفاعل must be nominative, not accusative.',
    hints: ['What case does نائب الفاعل always take?'],
    explanation: 'Once promoted to نائب الفاعل, the former object must be nominative: كُتِبَ الدَّرْسُ.',
    estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-verb-subject', conceptCode: 'c-fi-l-fa-il', type: 'teach_back',
    objective: 'Explain why position does not decide subjecthood in Arabic.',
    prompt: 'A friend insists "the first noun in the sentence is always the subject." Using كَتَبَ الطَّالِبُ الدَّرْسَ, explain why that rule fails for Arabic.', difficulty: 2,
    expectedAnswer: 'Arabic sentences are typically verb-first, so the verb itself, not a noun, often comes first; and even among the nouns, case marking (not position) decides which is فاعل.',
    hints: ['Point out what actually comes first in a typical Arabic sentence.'],
    explanation: 'A correct answer should note both that the verb usually leads, and that case — not order — assigns the فاعل role.',
    misconceptionTags: ['mis-first-noun-is-subject'], estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-verb-agreement', conceptCode: 'c-verb-subject-agreement', type: 'explain_rule',
    objective: 'State the verb-subject agreement rule precisely.',
    prompt: 'State the complete rule for verb-subject agreement in Arabic, covering both the verb-first and subject-first cases.', difficulty: 3,
    expectedAnswer: 'When the verb precedes the فاعل, it agrees in gender but stays grammatically singular regardless of the فاعل\'s number. When the subject is fronted, the resulting embedded verb — carrying its own attached pronoun — fully agrees in gender and number.',
    hints: ['Cover gender and number separately, and both sentence orders.'],
    explanation: 'A complete answer distinguishes gender agreement (always required) from number agreement (only required before a fronted subject).',
    estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-imperative', conceptCode: 'c-imperative', sentenceCode: 'verb-11-imperative', type: 'identify_role',
    objective: 'Recognize that the imperative is built, not inflected.',
    prompt: 'Does اِفْتَحِ in اِفْتَحِ الْبَابَ have a case or mood ending the way the perfect and imperfect do?', difficulty: 2,
    expectedAnswer: 'No — the imperative is مبني (built); it has no case/mood inflection. The kasrah under its final ح is only a helping vowel to avoid two adjacent silent consonants, not a grammatical marker.',
    hints: ['Compare with a perfect verb like كَتَبَ (also built, but for a different reason) versus an imperfect verb, which does inflect for mood.'],
    explanation: 'Both the perfect and the imperative are مبني; only the imperfect inflects for mood (indicative/subjunctive/jussive).',
    misconceptionTags: ['mis-case-on-indeclinables'], estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-mood', conceptCode: 'c-mood-jussive-subjunctive', sentenceCode: 'verb-12-negation-jussive-lam', type: 'compare_analyses',
    objective: 'Track a mood change caused by a governing particle.',
    prompt: 'يَكْتُبُ (verb-06) is indicative. يَكْتُبِ in لَمْ يَكْتُبِ الطَّالِبُ الدَّرْسَ is jussive. What single-vowel-level change signals the mood shift, and what caused it?', difficulty: 3,
    expectedAnswer: 'The final vowel changes (indicative ḍammah → jussive sukūn, here realized as a helping kasrah); لم is the particle that causes the shift by governing the following imperfect verb into the jussive.',
    hints: ['Compare the two verbs\' final letters side by side, then ask what precedes each one.'],
    explanation: 'لم is one of a small set of particles that force the jussive mood — recognizing it is the fastest way to predict a verb\'s mood before even looking at the ending.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-mood', conceptCode: 'c-mood-jussive-subjunctive', sentenceCode: 'verb-13-subjunctive-an', type: 'identify_governor',
    objective: 'Name the governor responsible for a subjunctive ending.',
    prompt: 'In يُرِيدُ الطَّالِبُ أَنْ يَكْتُبَ الدَّرْسَ, what causes يَكْتُبَ to end in a fatḥah instead of the expected ḍammah?', difficulty: 2,
    expectedAnswer: 'أنْ, which governs the following imperfect verb into the subjunctive mood.', acceptedVariants: ['ان'],
    hints: ['Look at the particle immediately before يكتب.'],
    explanation: 'أنْ is one of the particles that force the subjunctive — its presence predicts the fatḥah ending before you even parse the rest of the clause.',
    misconceptionTags: ['mis-ignoring-government'], estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-mahall', conceptCode: 'c-mahall-al-jumla', sentenceCode: 'verb-14-attached-object-pronoun', type: 'explain_rule',
    objective: 'Extend محل الجملة to a built attached pronoun.',
    prompt: 'In فَهِمَ الطَّالِبُ الدَّرْسَ ثُمَّ كَتَبَهُ, the attached pronoun ـهُ on كتبه has no visible case vowel of its own. In what sense is it still "accusative"?', difficulty: 4,
    expectedAnswer: 'It occupies the syntactic slot a full accusative noun (مفعول به) could have filled, referring back to الدرس — grammarians call this "في محل نصب" (in the position of accusative), even though no vowel physically marks it.',
    hints: ['Recall the same logic used for a whole clause serving as خبر كان (محل الجملة) — attached pronouns work the same way.'],
    explanation: 'محل نصب/رفع/جر applies not just to whole clauses but to built words like attached pronouns that cannot carry a physical case vowel at all.',
    estimatedSeconds: 40,
  },
];
