import type { ExerciseSeed } from '../exerciseTypes';

export const weakVerbExercises: ExerciseSeed[] = [
  {
    lessonCode: 'l-hamzated', conceptCode: 'c-hamzated-verbs', type: 'identify_role',
    objective: 'Locate the همزة within a hamzated root.',
    prompt: 'In the root س أ ل ("asking"), which position is the همزة in: first, middle, or final?', difficulty: 2,
    expectedAnswer: 'middle', acceptedVariants: ['second', 'middle radical'],
    hints: ['Spell out the three root letters in order.'],
    explanation: 'س أ ل has همزة as its second (middle) radical, as in سَأَلَ.', estimatedSeconds: 20,
  },
  {
    lessonCode: 'l-hamzated', conceptCode: 'c-hamzated-verbs', type: 'compare_analyses',
    objective: 'Recognize that hamzated roots stay intact across conjugation.',
    prompt: 'أَكَلَ، سَأَلَ، قَرَأَ each hide a همزة in a different root position (first, middle, final). Does the root ever actually disappear in any of these verbs?', difficulty: 3,
    expectedAnswer: 'No — the root consonants (including the همزة) are always present; only the همزة\'s written seat (ء/أ/إ/ؤ) shifts with the surrounding vowels.',
    hints: ['Compare this to the hollow and defective verbs, where a letter genuinely does drop or contract.'],
    explanation: 'Hamzated verbs are the mildest of the four irregular categories — a spelling-seat issue, not a disappearing-consonant issue.', estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-doubled', conceptCode: 'c-doubled-verbs', type: 'transform_word',
    objective: 'Split a doubled verb\'s merged consonants before a suffix.',
    prompt: 'مَدَّ means "he extended." Conjugate it for "I": أنا ___.', difficulty: 3,
    expectedAnswer: 'مَدَدْتُ', acceptedVariants: ['مددت'],
    hints: ['Before a consonant-initial suffix like ـتُ, the doubled consonant splits back into its two original letters.'],
    explanation: 'مَدَدْتُ separates the merged دّ back into د-د because ـتُ would otherwise create an unpronounceable three-consonant cluster.',
    misconceptionTags: [], estimatedSeconds: 35,
  },
  {
    lessonCode: 'l-doubled', conceptCode: 'c-doubled-verbs', type: 'repair_error',
    objective: 'Correct an over-merged doubled verb form.',
    prompt: 'Find the error: "أنا حَبَّتُ الكتابةَ" (intended: "I loved writing").', difficulty: 3,
    expectedAnswer: 'حَبَّتُ should be حَبَبْتُ — before the consonant-initial suffix ـتُ, the doubled بّ must split apart.',
    hints: ['Doubled verbs only stay merged when a vowel would otherwise separate the identical letters.'],
    explanation: 'حَبَبْتُ is correct; حَبَّتُ incorrectly keeps the merge in a position where the split is required.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-hollow', conceptCode: 'c-hollow-verbs', sentenceCode: 'morph-06-hollow-first-person-resurfaces', type: 'transform_word',
    objective: 'Conjugate a hollow verb before a consonant-initial suffix.',
    prompt: 'قَالَ means "he said." Conjugate it for "I": أنا ___.', difficulty: 3,
    expectedAnswer: 'قُلْتُ', acceptedVariants: ['قلت'],
    hints: ['The contracted ا resurfaces as its underlying short vowel once ـتُ follows.'],
    explanation: 'قُلْتُ shows the root\'s middle و resurfacing as ُ before the consonant-initial suffix.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-hollow', conceptCode: 'c-hollow-verbs', type: 'transform_word',
    objective: 'Conjugate another hollow verb before a consonant-initial suffix.',
    prompt: 'بَاعَ means "he sold." Conjugate it for "you (f.)": أنتِ ___.', difficulty: 3,
    expectedAnswer: 'بِعْتِ', acceptedVariants: ['بعت'],
    hints: ['Same resurfacing pattern as قال → قلت, but with the root\'s middle ي.'],
    explanation: 'بِعْتِ shows the same predictable resurfacing rule applied to a different hollow root.', estimatedSeconds: 30,
  },
  {
    lessonCode: 'l-hollow', conceptCode: 'c-hollow-verbs', type: 'explain_rule',
    objective: 'State the general hollow-verb rule.',
    prompt: 'State, in one general rule, when a hollow verb\'s middle radical contracts into a long vowel and when it resurfaces as a short one.', difficulty: 4,
    expectedAnswer: 'It contracts into a long vowel whenever no suffix (or only a vowel-initial one) follows; it resurfaces as a short vowel whenever a consonant-initial suffix follows.',
    hints: ['Compare قَالَ (no suffix) with قُلْتُ (consonant-initial suffix).'],
    explanation: 'This single conditioning rule explains both قال and قلت without treating them as separate irregular verbs.', estimatedSeconds: 45,
  },
  {
    lessonCode: 'l-defective', conceptCode: 'c-defective-verbs', sentenceCode: 'morph-07-defective-ya', type: 'identify_role',
    objective: 'Locate a defective verb\'s weak final radical.',
    prompt: 'نَسِيَ ("he forgot") is defective. Which root letter is weak, and where does it sit in the root?', difficulty: 2,
    expectedAnswer: 'ي, the final (third) radical.', acceptedVariants: ['final ي', 'third radical'],
    hints: ['Spell the root ن س ي and find the weak letter\'s position.'],
    explanation: 'ن س ي has ي as its final radical, visible here as the ending -iya.', estimatedSeconds: 25,
  },
  {
    lessonCode: 'l-defective', conceptCode: 'c-defective-verbs', sentenceCode: 'morph-08-defective-waw', type: 'compare_analyses',
    objective: 'Distinguish defective from hollow weakness.',
    prompt: 'قَالَ (hollow) and دَعَا (defective) both show a long ا in the third-person perfect, but for different underlying reasons. What is the difference?', difficulty: 4,
    expectedAnswer: 'قَالَ\'s weak letter (و) is the middle radical; دَعَا\'s weak letter (و) is the final radical. The surface look is similar, but the weakness is structurally located in a different part of the root.',
    hints: ['Spell out both roots (ق و ل and د ع و) and compare where the weak letter sits.'],
    explanation: 'This is a classic trap: two verbs can look alike on the surface while being weak for structurally different reasons — always check the root, not just the surface form.', estimatedSeconds: 40,
  },
  {
    lessonCode: 'l-defective', conceptCode: 'c-defective-verbs', type: 'explain_rule',
    objective: 'Connect defective verbs to mood marking.',
    prompt: 'Why do defective verbs show mood changes (jussive/subjunctive) as the final weak letter dropping or shortening, rather than as an added vowel the way sound verbs do?', difficulty: 5,
    expectedAnswer: 'Because the final letter is already weak (و or ي, often realized as a long vowel), there is no ordinary consonant available to carry a separate mood vowel — so the mood distinction is instead carried by the weak letter itself shortening or dropping.',
    hints: ['Think about what a sound verb\'s jussive ending looks like, and why a defective verb\'s final letter cannot do the same thing.'],
    explanation: 'This is an advanced but important synthesis: defective-verb mood marking is a direct consequence of their morphological weakness, not an unrelated extra rule.', estimatedSeconds: 60,
  },
  {
    lessonCode: 'l-hamzated', conceptCode: 'c-hamzated-verbs', type: 'construct_from_root',
    objective: 'Build a passive participle from a hamzated root.',
    prompt: 'Give the passive participle of أ ك ل ("eating").', difficulty: 3,
    expectedAnswer: 'مَأْكُول', acceptedVariants: ['مأكول'],
    hints: ['Apply the ordinary مَفْعُول pattern; the همزة keeps its seat as أ after the prefixed م.'],
    explanation: 'مأكول means "eaten; edible," following the regular passive-participle pattern despite the hamzated root.', estimatedSeconds: 30,
  },
];
