export interface LessonConceptLink {
  conceptCode: string;
  role: 'introduces' | 'reinforces' | 'reviews';
}

export interface LessonSeed {
  code: string;
  unitCode: string;
  title: string;
  titleArabic: string;
  summary: string;
  order: number;
  estimatedMinutes: number;
  concepts: LessonConceptLink[];
  observeSentenceCodes: string[];
  discoveryPrompt: string;
  microExplanation: string;
  deeperDetail?: string;
}

export const lessons: LessonSeed[] = [
  {
    code: 'l-word-classes',
    unitCode: 'unit-word-categories',
    title: 'Spotting a noun, a verb, and a particle',
    titleArabic: 'اسم، فعل، حرف',
    summary: 'The three-way sort every later rule depends on.',
    order: 1,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-word-classes', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'verb-01-basic-vso', 'nom-04-khabar-shibh-jumla'],
    discoveryPrompt:
      'Look at الطَّالِبُ, مُجْتَهِدٌ, كَتَبَ, and عَلَى across these three sentences. Two of these words could be pointed at and asked "what is it?" One describes an action locked to a time. One means nothing at all until it attaches to something else. Sort all four into three piles before reading on.',
    microExplanation:
      'Arabic sorts every word into اسم (noun — names a thing, person, quality, or idea and can take case endings and, in many instances, tanwīn), فعل (verb — ties an action or state to a tense), or حرف (particle — has no standalone meaning: عَلَى means nothing alone, only "on [something]"). This is a structural test, not a meaning test: مُجْتَهِدٌ ("diligent") is grammatically a noun in Arabic, not an adjective in a separate class.',
    deeperDetail:
      'Traditional grammars add finer tests: a noun can take تنوين or ال or be preceded by a preposition; a verb conjugates for tense and person; a particle does neither. You will use these tests constantly once ambiguous words appear.',
  },
  {
    code: 'l-complete-sentence',
    unitCode: 'unit-word-categories',
    title: "What makes a sentence complete",
    titleArabic: 'الجملة المفيدة وأنواعها',
    summary: 'Distinguishing a full sentence from a bare phrase, and telling nominal from verbal sentences.',
    order: 2,
    estimatedMinutes: 15,
    concepts: [
      { conceptCode: 'c-complete-utterance', role: 'introduces' },
      { conceptCode: 'c-nominal-vs-verbal', role: 'introduces' },
    ],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'verb-01-basic-vso'],
    discoveryPrompt:
      'الطَّالِبُ مُجْتَهِدٌ and كَتَبَ الطَّالِبُ الدَّرْسَ both leave you satisfied — nothing more is needed. What is the very first word of each? Is it the same kind of word in both?',
    microExplanation:
      'A complete utterance (الكلام) gives a self-sufficient meaning. Arabic has exactly two shapes for one: if the first word is a noun, it is a nominal sentence (الجملة الاسمية); if the first word is a verb, it is a verbal sentence (الجملة الفعلية) — regardless of what the sentence is actually about.',
    deeperDetail:
      'This is a purely structural label. "الطالب مجتهد" and "كتب الطالب الدرس" are both about a student doing something, but only the second is "verbal" — because that term describes the sentence\'s opening word, not its meaning.',
  },
  {
    code: 'l-demonstratives',
    unitCode: 'unit-sentence-shapes',
    title: 'Pointing and naming: demonstratives',
    titleArabic: 'أسماء الإشارة',
    summary: 'هذا، هذه، هؤلاء — pointing words that already agree in gender and number.',
    order: 1,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-demonstratives', role: 'introduces' }],
    observeSentenceCodes: ['nom-02-demonstrative-indefinite-khabar', 'nom-03-demonstrative-feminine-adjective'],
    discoveryPrompt: 'هَذَا كِتَابٌ vs. هَذِهِ الْمَدْرَسَةُ جَمِيلَةٌ — what changes about the pointing word, and why, given كِتَاب is masculine and مَدْرَسَة is feminine?',
    microExplanation:
      'هذا (m.), هذه (f.), هذان/هاتان (dual), and هؤلاء (plural) point at something instead of naming it, and must agree with what they point at in gender and number. They are built words (مبني): they never change ending for case, even though a case role is still assigned to them.',
  },
  {
    code: 'l-pronouns',
    unitCode: 'unit-sentence-shapes',
    title: "Who's talking: personal pronouns",
    titleArabic: 'الضمائر المنفصلة',
    summary: 'Detached pronouns and why Arabic keeps more distinctions than English.',
    order: 2,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-personal-pronouns', role: 'introduces' }],
    observeSentenceCodes: ['case-02-accusative-triplet', 'verb-04-fronted-subject-full-agreement'],
    discoveryPrompt: 'رَأَيْتُ ends in ـتُ, and كَتَبُوا ends in ـوا. Neither sentence has a separate word for "I" or "they." Where did those meanings go?',
    microExplanation:
      'Arabic distinguishes gender in "you" and "they" where English does not, and marks person, gender, and number on attached pronoun suffixes fused directly onto verbs — ـتُ ("I"), ـوا ("they, m."). Detached pronouns (أنا، هو، هي، أنتَ، أنتِ، نحن، هم، هنّ) are used mainly when no verb is present to carry that information, or for emphasis.',
  },
  {
    code: 'l-questions-negation',
    unitCode: 'unit-sentence-shapes',
    title: 'Asking and denying',
    titleArabic: 'الاستفهام والنفي',
    summary: 'هل, question words, and the three negators لا، ما، ليس.',
    order: 3,
    estimatedMinutes: 20,
    concepts: [
      { conceptCode: 'c-questions', role: 'introduces' },
      { conceptCode: 'c-negation-basic', role: 'introduces' },
    ],
    observeSentenceCodes: ['part-05-laysa-negation'],
    discoveryPrompt: 'لَيْسَ الطَّالِبُ غَائِبًا — غَائِبًا is accusative, yet nothing "did" anything to it. What kind of word could reach in and change a noun\'s case without being a preposition or a verb of action?',
    microExplanation:
      'هل and أَ ask yes/no questions without reordering the sentence; مَن، ما/ماذا، أين، متى، كيف، كم ask for specific information and take on a grammatical role inside the sentence they open. Of the three negators, لا and ما negate plainly, while ليس is grammatically a verb that pushes a nominal sentence\'s predicate into the accusative — your first hint that "government" is coming.',
  },
  {
    code: 'l-prepositional-phrase',
    unitCode: 'unit-sentence-shapes',
    title: 'The prepositional phrase',
    titleArabic: 'الجار والمجرور',
    summary: 'Your first, cleanest example of grammatical government.',
    order: 4,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-prepositional-phrase', role: 'introduces' }],
    observeSentenceCodes: ['nom-04-khabar-shibh-jumla', 'nom-08-plural-mubtada-shibh-jumla'],
    discoveryPrompt: 'عَلَى الطَّاوِلَةِ and فِي الْفَصْلِ: both nouns end in kasrah. Both follow a particle. Coincidence?',
    microExplanation:
      'A preposition (حرف جر) always forces the following noun into the genitive — this is grammatical government (العامل) in its simplest, most reliable form. The whole pair (جار ومجرور) then behaves as a single unit that can serve as a khabar, an adjective-equivalent, or other roles.',
  },
  {
    code: 'l-mubtada-khabar',
    unitCode: 'unit-nominal-sentence',
    title: "مبتدأ and خبر: the sentence's skeleton",
    titleArabic: 'المبتدأ والخبر',
    summary: 'The two roles every nominal sentence is built from.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-mubtada-khabar', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'nom-02-demonstrative-indefinite-khabar'],
    discoveryPrompt: 'In الطَّالِبُ مُجْتَهِدٌ, which word is the sentence "about," and which word tells you something new about it? Check both words\' final vowel — what do you notice?',
    microExplanation:
      'The مبتدأ is the noun the sentence is about — typically definite, typically first. The خبر is what is said about it. Both are nominative by default. Every later complication in the nominal sentence (إنّ, كان, fronting, omission) is defined relative to this pair.',
  },
  {
    code: 'l-khabar-types',
    unitCode: 'unit-nominal-sentence',
    title: 'Three shapes of خبر',
    titleArabic: 'أنواع الخبر',
    summary: 'Single word, prepositional phrase, or a whole embedded sentence.',
    order: 2,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-khabar-types', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'nom-04-khabar-shibh-jumla', 'part-04-kana-imperfect'],
    discoveryPrompt: 'Compare the خبر in all three example sentences: مُجْتَهِدٌ, عَلَى الطَّاوِلَةِ, and يَكْتُبُ الدَّرْسَ. Which one is a single word? Which is a phrase? Which is a whole miniature sentence?',
    microExplanation:
      'A خبر can be a single word (مفرد), a prepositional phrase (شبه جملة), or a full embedded sentence (جملة) with its own internal فاعل/مفعول أو مبتدأ/خبر — while still, as a whole, doing one job: being predicated of the mubtada.',
  },
  {
    code: 'l-definiteness',
    unitCode: 'unit-nominal-sentence',
    title: "Definiteness: what makes a noun 'the'",
    titleArabic: 'التعريف والتنكير',
    summary: 'Six ways Arabic makes a noun definite — and why it matters for إضافة.',
    order: 3,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-definiteness', role: 'introduces' }],
    observeSentenceCodes: ['nom-06-idafa-basic', 'case-08-diptote-genitive'],
    discoveryPrompt: 'كِتَابُ الطَّالِبِ is "the student\'s book" — definite — but neither word carries ال. Where did "the" come from?',
    microExplanation:
      'A noun becomes definite with ال, as a proper name, as a pronoun, as a demonstrative\'s referent, as a relative noun, or — critically — by being the first term of an إضافة whose second term is already definite. Anything else is indefinite (نكرة).',
  },
  {
    code: 'l-adjective-agreement',
    unitCode: 'unit-nominal-sentence',
    title: 'Adjective agreement in four features',
    titleArabic: 'النعت',
    summary: 'Gender, number, definiteness, and case — all four, every time.',
    order: 4,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-adjective-agreement', role: 'introduces' }],
    observeSentenceCodes: ['nom-05-adjective-agreement-definite', 'nom-01-mubtada-khabar-basic'],
    discoveryPrompt: 'الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ has three nominative words in a row, but only two of them form a matched pair. Which two, and on how many features do they match?',
    microExplanation:
      'A نعت agrees with its noun in gender, number, definiteness, and case — all four simultaneously. Contrast this with a خبر (as in nom-01), which only shares case with its mubtada, not definiteness: مُجْتَهِدٌ can be indefinite while الطالب is definite, because خبر and نعت are different jobs with different agreement rules.',
  },
  {
    code: 'l-idafa',
    unitCode: 'unit-nominal-sentence',
    title: 'Possession without a possessive word',
    titleArabic: 'الإضافة',
    summary: 'How two nouns in a row express "of" — with no word meaning "of."',
    order: 5,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-idafa', role: 'introduces' }],
    observeSentenceCodes: ['nom-06-idafa-basic', 'nom-07-idafa-passive-participle-khabar'],
    discoveryPrompt: 'كِتَابُ الطَّالِبِ has no تنوين on كتاب and no ال on either word, yet the whole phrase is definite. Try adding ال to كتاب — native intuition (and the rule) says you cannot. Why not?',
    microExplanation:
      'Two nouns in a row form an إضافة: the first (المضاف) never takes ال or تنوين, and the second (المضاف إليه) is always genitive and supplies the whole phrase\'s definiteness. This has no direct English equivalent — English\'s "the student\'s book" marks definiteness once, on "the," while Arabic marks it structurally, through position.',
  },
  {
    code: 'l-dual-sound-plurals',
    unitCode: 'unit-nominal-sentence',
    title: 'Duals and sound plurals',
    titleArabic: 'المثنى وجمعا المذكر والمؤنث السالمان',
    summary: 'When case is shown by swapping a whole suffix, not a vowel.',
    order: 6,
    estimatedMinutes: 20,
    concepts: [
      { conceptCode: 'c-gender-number-of-nouns', role: 'introduces' },
      { conceptCode: 'c-dual-and-sound-plurals', role: 'introduces' },
    ],
    observeSentenceCodes: ['case-04-dual-predicate', 'case-05-dual-accusative', 'case-06-sound-plural-predicate', 'case-07-sound-plural-accusative'],
    discoveryPrompt: 'الطَّالِبَانِ (nominative) vs. الطَّالِبَيْنِ (accusative) — and الْمُعَلِّمُونَ vs. الْمُعَلِّمِينَ. What part of the word is changing? Is it the same kind of change you\'ve seen on singular nouns?',
    microExplanation:
      'The dual marks case with ـَانِ (nominative) vs. ـَيْنِ (accusative/genitive combined); the sound masculine plural marks it with ـُونَ vs. ـِينَ. These are secondary markers — a different mechanism from a singular noun\'s short-vowel change, but still fully regular and predictable.',
  },
  {
    code: 'l-inna',
    unitCode: 'unit-nominal-sentence',
    title: 'إنّ enters the sentence',
    titleArabic: 'إنّ وأخواتها',
    summary: 'A particle that reaches in and flips the mubtada to accusative.',
    order: 7,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-inna-wa-akhawatuha', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'part-01-inna-basic', 'part-02-lakinna-contrast'],
    discoveryPrompt: 'الطَّالِبُ مُجْتَهِدٌ vs. إِنَّ الطَّالِبَ مُجْتَهِدٌ — track the ending on الطالب across both sentences. What changed, and what did not?',
    microExplanation:
      'إنّ، أنّ، كأنّ، لكنّ، ليت، لعلّ push the following noun (now called اسم إنّ) into the accusative, while the predicate (خبر إنّ) stays nominative. This is grammatical government reaching into a sentence type — the nominal sentence — that otherwise has no verb to do the governing.',
  },
  {
    code: 'l-kana',
    unitCode: 'unit-nominal-sentence',
    title: 'كان and the nominal sentence in the past',
    titleArabic: 'كان وأخواتها',
    summary: "The mirror image of إنّ: the predicate moves, not the subject.",
    order: 8,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-kana-wa-akhawatuha', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'part-03-kana-basic', 'part-05-laysa-negation', 'part-06-maa-zaala'],
    discoveryPrompt: 'الطَّالِبُ مُجْتَهِدٌ vs. كَانَ الطَّالِبُ مُجْتَهِدًا — this time track مُجْتَهِدٌ/مُجْتَهِدًا. Compare with what إنّ did in the previous lesson: same target, or different?',
    microExplanation:
      'كان، أصبح، ظلّ، أمسى، بات، صار، ما زال، ليس keep the subject (اسم كان) nominative but push the predicate (خبر كان) into the accusative — the reverse of إنّ\'s target. Contrasting the two side by side is the fastest way to stop confusing which governor touches which word.',
  },
  {
    code: 'l-verb-subject',
    unitCode: 'unit-verbal-sentence',
    title: 'The verb and its subject',
    titleArabic: 'الفعل والفاعل',
    summary: 'Why the first noun is not automatically the subject.',
    order: 1,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-fi-l-fa-il', role: 'introduces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'verb-07-intransitive-no-object'],
    discoveryPrompt: 'كَتَبَ الطَّالِبُ الدَّرْسَ — in English word order this reads "wrote the-student the-lesson." Which word is doing the writing? How do you know, if not from position?',
    microExplanation:
      'In a verbal sentence, the فاعل is whoever performs the action, and it is always nominative — regardless of position, and regardless of what an English translation\'s word order might suggest. Arabic sentences default to verb-first order, so the very first noun after the verb is usually, but not definitionally, the فاعل.',
  },
  {
    code: 'l-verb-agreement',
    unitCode: 'unit-verbal-sentence',
    title: "Why the verb doesn't always \"agree\"",
    titleArabic: 'مطابقة الفعل للفاعل',
    summary: 'Singular verb, plural subject — until the subject moves to the front.',
    order: 2,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-verb-subject-agreement', role: 'introduces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'verb-02-dual-subject-singular-verb', 'verb-03-plural-subject-singular-verb', 'verb-04-fronted-subject-full-agreement'],
    discoveryPrompt: 'كَتَبَ stays exactly the same in all three of the first sentences, even though the فاعل changes from singular to dual to plural. Then in the fourth sentence, the verb suddenly becomes كَتَبُوا. What changed about the sentence itself, not just the noun?',
    microExplanation:
      'A verb before its فاعل stays grammatically singular no matter the فاعل\'s real number (though it still agrees in gender). Once the subject is fronted, the sentence becomes structurally nominal with an embedded verbal khabar, and that embedded verb carries its own attached pronoun, which does fully agree.',
  },
  {
    code: 'l-maful-bihi',
    unitCode: 'unit-verbal-sentence',
    title: 'The direct object',
    titleArabic: 'المفعول به',
    summary: 'Accusative by role, not by meaning.',
    order: 3,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-maful-bihi', role: 'introduces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'verb-07-intransitive-no-object', 'verb-10-ditransitive'],
    discoveryPrompt: 'جَلَسَ الْوَلَدُ has no object at all, while أَعْطَى الْمُعَلِّمُ الطَّالِبَ كِتَابًا has two. What decides whether a verb needs، allows, or forbids a مفعول به?',
    microExplanation:
      'A transitive verb\'s مفعول به is accusative — the thing acted upon. Some verbs are intransitive (لازم) and take none; a few take two, both marked identically as accusative even when one maps to an English indirect object.',
  },
  {
    code: 'l-passive',
    unitCode: 'unit-verbal-sentence',
    title: 'The passive voice',
    titleArabic: 'المبني للمجهول ونائب الفاعل',
    summary: 'The object gets promoted, and the verb changes its internal vowels.',
    order: 4,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-passive-voice', role: 'introduces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'pass-01-anchor'],
    discoveryPrompt: 'كَتَبَ الطَّالِبُ الدَّرْسَ becomes كُتِبَ الدَّرْسُ. الدَّرْسَ was accusative; الدَّرْسُ is nominative. Did its meaning in the sentence change, or just its grammatical role?',
    microExplanation:
      'When the agent is unknown, unimportant, or hidden on purpose, the verb\'s internal vowels shift and the former مفعول به is promoted to نائب الفاعل — nominative, exactly like a real فاعل — even though it is still semantically the one acted upon. Case tracks syntactic role, not real-world meaning.',
  },
  {
    code: 'l-irab-concept',
    unitCode: 'unit-case-foundations',
    title: 'What إعراب actually is',
    titleArabic: 'مفهوم الإعراب',
    summary: 'Reframing "grammar" as evidence of role, not a list to memorize.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-irab-concept', role: 'introduces' }],
    observeSentenceCodes: ['case-01-nominative-triplet', 'case-02-accusative-triplet', 'case-03-genitive-triplet'],
    discoveryPrompt: 'الطَّالِبُ، الطَّالِبَ، الطَّالِبِ — same word, three different endings, across three sentences. What changed between the sentences that could explain each ending?',
    microExplanation:
      'إعراب is the system by which a word\'s ending changes to reveal its grammatical role — the ending is evidence of the role, not the rule itself. Most nouns and present-tense verbs change this way (معرب); a smaller set of words never change regardless of role (مبني).',
  },
  {
    code: 'l-three-cases',
    unitCode: 'unit-case-foundations',
    title: 'The three homes: رفع، نصب، جر',
    titleArabic: 'رفع، نصب، جر',
    summary: 'Turning "which ending?" into "which home does this role belong to?"',
    order: 2,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-three-cases', role: 'reinforces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'nom-04-khabar-shibh-jumla'],
    discoveryPrompt: 'List every role you have learned so far — مبتدأ، خبر، فاعل، مفعول به، مجرور بحرف جر. Which case does each one live in by default?',
    microExplanation:
      'رفع is the default state, home to مبتدأ، خبر، and فاعل. نصب is the state a governor imposes, most often on مفعول به. جر only ever happens after a preposition or as a مضاف إليه. Once you can name a word\'s role, its case is a lookup, not a guess.',
  },
  {
    code: 'l-marker-types',
    unitCode: 'unit-case-foundations',
    title: 'Visible, secondary, and estimated markers',
    titleArabic: 'العلامات الأصلية والفرعية والمقدرة',
    summary: 'Why some case endings can be heard, and some cannot.',
    order: 3,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-marker-types', role: 'introduces' }],
    observeSentenceCodes: ['case-01-nominative-triplet', 'case-04-dual-predicate', 'case-08-diptote-genitive'],
    discoveryPrompt: 'الطَّالِبُ shows case with a short vowel. الطَّالِبَانِ shows it with a whole suffix. مِصْرَ shows genitive with the "wrong" vowel and no تنوين at all. Are all three of these "exceptions," or is something more organized going on?',
    microExplanation:
      'A visible marker is an ordinary short vowel. A secondary marker is a dedicated suffix, as with duals and sound plurals. An estimated marker means the case is grammatically present but cannot be physically pronounced — most often because the noun\'s final letter cannot carry a short vowel at all.',
  },
  {
    code: 'l-diptotes',
    unitCode: 'unit-case-foundations',
    title: 'The diptote exception class',
    titleArabic: 'الممنوع من الصرف',
    summary: 'A closed set of nouns that only ever show two case vowels.',
    order: 4,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-diptotes', role: 'introduces' }],
    observeSentenceCodes: ['case-08-diptote-genitive'],
    discoveryPrompt: 'سَافَرْتُ إِلَى مِصْرَ — إلى should govern a genitive, which should show as kasrah. It doesn\'t. Is this a mistake, or a rule you haven\'t met yet?',
    microExplanation:
      'Diptotes — many proper names, the أَفْعَل/فَعْلَاء pattern family, and certain broken plurals — take فتحة for both accusative and genitive, and never take تنوين. This is a fixed, learnable list of shapes, not a random irregularity.',
  },
  {
    code: 'l-root-pattern',
    unitCode: 'unit-roots-patterns',
    title: 'Root and pattern: the master key',
    titleArabic: 'الجذر والوزن',
    summary: 'Every Arabic word as a root poured into a mold.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-root-and-pattern', role: 'introduces' }],
    observeSentenceCodes: ['morph-01-form2-causative', 'nom-06-idafa-basic'],
    discoveryPrompt: 'كَاتِب، مَكْتُوب، كِتَابَة، مَكْتَب all share ك ت ب but sound and mean different things. What is staying constant, and what is changing?',
    microExplanation:
      'Almost every Arabic word is built from a root of (usually) three consonants carrying a core meaning, poured into a pattern that adds grammatical shape and a fairly predictable derivational meaning. Learning to extract the root and recognize the pattern turns an unfamiliar word into something decodable.',
  },
  {
    code: 'l-form-i',
    unitCode: 'unit-roots-patterns',
    title: 'Form I and its family',
    titleArabic: 'الوزن الأول ومشتقاته',
    summary: 'فَعَلَ, its active participle, its passive participle, and its verbal noun.',
    order: 2,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-form-i-verb', role: 'introduces' }],
    observeSentenceCodes: ['nom-01-mubtada-khabar-basic', 'nom-07-idafa-passive-participle-khabar'],
    discoveryPrompt: 'كَتَبَ، كَاتِب، مَكْتُوب، كِتَابَة — one verb and three related nouns. What job does each one do in a sentence?',
    microExplanation:
      'Form I is the bare, underived verb a root starts from. From it come the active participle (فَاعِل — the doer), the passive participle (مَفْعُول — the one acted upon), and a مصدر whose exact shape must be learned per verb (unlike the derived forms, whose مصادر are far more predictable).',
  },
  {
    code: 'l-derived-forms',
    unitCode: 'unit-roots-patterns',
    title: 'Derived forms and their meaning tendencies',
    titleArabic: 'الأوزان من الثاني إلى العاشر',
    summary: 'Causative, reciprocal, reflexive, and "seeking" — read off the shape.',
    order: 3,
    estimatedMinutes: 25,
    concepts: [{ conceptCode: 'c-derived-forms', role: 'introduces' }],
    observeSentenceCodes: ['morph-01-form2-causative', 'morph-02-form5-reflexive', 'morph-03-form8-reciprocal-effort', 'morph-04-form7-vs-form1-transitivity'],
    discoveryPrompt: 'دَرَسَ ("studied") → دَرَّسَ ("taught"). عَلَّمَ ("taught") → تَعَلَّمَ ("learned"). كَسَرَ ("broke it") → انْكَسَرَ ("it broke"). What is the pattern behind each shift in meaning?',
    microExplanation:
      'Augmenting Form I with doubling, a prefixed أ، an infixed ت or ن, or other changes produces Forms II–X, each with recurring (not exceptionless) meaning tendencies: II often causative, III often "toward another party," V often reflexive-of-II, VII often passive/reflexive, VIII often reflexive-or-effortful, X often "to seek."',
  },
  {
    code: 'l-participles',
    unitCode: 'unit-roots-patterns',
    title: 'Active and passive participles',
    titleArabic: 'اسم الفاعل واسم المفعول',
    summary: 'كَاتِب names the doer; مَكْتُوب names the one acted upon.',
    order: 4,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-active-passive-participle', role: 'introduces' }],
    observeSentenceCodes: ['verb-01-basic-vso', 'nom-07-idafa-passive-participle-khabar'],
    discoveryPrompt: 'الطَّالِبُ ("the student," from a Form-I active participle of ط ل ب) is فاعل in كتب الطالب الدرس. Is "طالب" (the shape of the word) the same thing as "فاعل" (the job it does in this sentence)?',
    microExplanation:
      'اسم الفاعل (فَاعِل for Form I) names the doer of an action; اسم المفعول (مَفْعُول for Form I) names the one acted upon. Both behave as ordinary nouns or adjectives afterward — a shape a word has is not the same thing as فاعل, the syntactic subject job a word can perform in a sentence.',
  },
  {
    code: 'l-masdar',
    unitCode: 'unit-roots-patterns',
    title: 'The verbal noun',
    titleArabic: 'المصدر',
    summary: 'Naming the action itself, with no doer and no time attached.',
    order: 5,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-verbal-noun', role: 'introduces' }],
    observeSentenceCodes: ['morph-09-hamzated-cognate-object'],
    discoveryPrompt: 'كِتَابَة means "writing" with no one doing it and no time attached — compare to كَتَبَ ("he wrote," locked to third-person-past). What did the pattern shift accomplish?',
    microExplanation:
      'المصدر abstracts the action from any doer or time — كِتَابَة, "writing" (the act itself). Every verb has at least one مصدر; derived forms\' مصادر are largely predictable even though Form I\'s is not.',
  },
  {
    code: 'l-perfect',
    unitCode: 'unit-verb-conjugation',
    title: 'The perfect tense',
    titleArabic: 'الفعل الماضي',
    summary: 'How a whole sentence can fit inside one conjugated verb.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-perfect-tense', role: 'introduces' }],
    observeSentenceCodes: ['case-02-accusative-triplet', 'verb-04-fronted-subject-full-agreement', 'verb-05-feminine-intransitive'],
    discoveryPrompt: 'رَأَيْتُ، كَتَبُوا، ذَهَبَتِ — three different suffixes on three different verbs. What information does each suffix carry?',
    microExplanation:
      'The perfect marks a completed action by attaching suffixes that encode person, gender, and number directly onto the stem. Because subject information is fused into the verb, a single fully conjugated verb can be a complete sentence with no separate subject word.',
  },
  {
    code: 'l-imperfect',
    unitCode: 'unit-verb-conjugation',
    title: 'The imperfect tense',
    titleArabic: 'الفعل المضارع',
    summary: 'Prefixed for person, and — unlike the perfect — inflected for mood.',
    order: 2,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-imperfect-tense', role: 'introduces' }],
    observeSentenceCodes: ['verb-06-imperfect-indefinite-object', 'part-04-kana-imperfect'],
    discoveryPrompt: 'يَكْتُبُ starts with ي, not a suffix. Compare to كَتَبَ. Where did the person-marking move?',
    microExplanation:
      'The imperfect marks an ongoing, habitual, or future action with a prefix encoding person (and often gender): يَكْتُبُ (he writes), تَكْتُبُ (she writes / you, m., write). Unlike the perfect, its ending changes with mood — the doorway into Domain D and F\'s mood system.',
  },
  {
    code: 'l-imperative',
    unitCode: 'unit-verb-conjugation',
    title: 'The imperative',
    titleArabic: 'فعل الأمر',
    summary: 'Built from the jussive, not memorized as a fourth form.',
    order: 3,
    estimatedMinutes: 15,
    concepts: [{ conceptCode: 'c-imperative', role: 'introduces' }],
    observeSentenceCodes: ['verb-06-imperfect-indefinite-object'],
    discoveryPrompt: 'يَكْتُبُ means "he writes." Strip the ي and add a helping أ at the front: what command does اُكْتُبْ give, and to whom?',
    microExplanation:
      'The imperative is derived from the jussive form of the imperfect by stripping the subject prefix, sometimes adding a helping همزة: اكْتُبْ (write!, to a man), اكْتُبِي (write!, to a woman) — a derived form, not an independent fourth tense to memorize from scratch.',
  },
  {
    code: 'l-mood',
    unitCode: 'unit-verb-conjugation',
    title: 'Mood: indicative, subjunctive, jussive',
    titleArabic: 'الرفع والنصب والجزم في المضارع',
    summary: "The imperfect verb's own version of case.",
    order: 4,
    estimatedMinutes: 25,
    concepts: [{ conceptCode: 'c-mood-jussive-subjunctive', role: 'introduces' }],
    observeSentenceCodes: ['verb-06-imperfect-indefinite-object'],
    discoveryPrompt: 'يَكْتُبُ ends in ḍammah by default. If a particle like لن or لم precedes it, tradition says that final vowel must change. Which system have you already learned that behaves exactly this way?',
    microExplanation:
      'The imperfect verb\'s final vowel (or final letter, for weak/plural forms) changes with mood: رفع (indicative, default), نصب (subjunctive, triggered by particles like أن، لن، كي), جزم (jussive, triggered by لم، لا الناهية، or conditional particles) — verbal إعراب, running on the same logic as nominal case.',
  },
  {
    code: 'l-hamzated',
    unitCode: 'unit-weak-verbs',
    title: 'Hamzated verbs',
    titleArabic: 'الفعل المهموز',
    summary: 'When one root letter is a همزة.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-hamzated-verbs', role: 'introduces' }],
    observeSentenceCodes: ['morph-09-hamzated-cognate-object'],
    discoveryPrompt: 'سَأَلَ has a همزة as its middle letter, seated on ا. Does the root itself ever actually disappear in any conjugated form?',
    microExplanation:
      'A verb with همزة as one of its root letters (أَكَلَ، سَأَلَ، قَرَأَ) conjugates on entirely regular lines — only the همزة\'s written seat (ء/أ/إ/ؤ) shifts as the surrounding vowels change. The root consonants themselves never vanish.',
  },
  {
    code: 'l-doubled',
    unitCode: 'unit-weak-verbs',
    title: 'Doubled verbs',
    titleArabic: 'الفعل المضعّف',
    summary: 'Merged consonants that split apart again before certain suffixes.',
    order: 2,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-doubled-verbs', role: 'introduces' }],
    observeSentenceCodes: ['case-03-genitive-triplet'],
    discoveryPrompt: 'مَرَرْتُ keeps both رs separate, spelled out. Would you expect حَبَّ ("he loved") to do the same before ـتُ?',
    microExplanation:
      'When a verb\'s second and third root letters are identical (م د د، ح ب ب), they merge (إدغام) in most forms — مَدَّ، حَبَّ — but split back apart wherever a vowel would otherwise fall between them, as with the تُ suffix: مَدَدْتُ، حَبَبْتُ.',
  },
  {
    code: 'l-hollow',
    unitCode: 'unit-weak-verbs',
    title: 'Hollow verbs',
    titleArabic: 'الفعل الأجوف',
    summary: 'A middle root letter that contracts — and resurfaces.',
    order: 3,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-hollow-verbs', role: 'introduces' }],
    observeSentenceCodes: ['morph-05-hollow-perfect-contracted', 'morph-06-hollow-first-person-resurfaces'],
    discoveryPrompt: 'قَالَ vs. قُلْتُ — these look like two unrelated verbs at first glance. What is the same in both, and what predicts the difference?',
    microExplanation:
      'A verb with و or ي as its middle root letter (ق و ل، ب ي ع) contracts that letter into a long vowel in most forms — قَالَ، بَاعَ — but the weak letter resurfaces as a short vowel once a consonant-initial suffix follows: قُلْتُ، بِعْتُ. One rule explains both surface shapes.',
  },
  {
    code: 'l-defective',
    unitCode: 'unit-weak-verbs',
    title: 'Defective verbs',
    titleArabic: 'الفعل الناقص',
    summary: 'A final weak letter, and how mood shows up as it disappears.',
    order: 4,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-defective-verbs', role: 'introduces' }],
    observeSentenceCodes: ['morph-07-defective-ya', 'morph-08-defective-waw'],
    discoveryPrompt: 'نَسِيَ ends in ي؛ دَعَا ends in a long ا that is really a hidden و. Both are "defective" for different underlying reasons — can you tell which final radical each one hides?',
    microExplanation:
      'A verb with و or ي as its final root letter shows that weak letter as a long vowel in most forms — دَعَا، نَسِيَ — but drops or shortens it in others. Because the final letter is already weak, jussive and subjunctive show up here as the letter dropping outright, rather than as a separate vowel change.',
  },
  {
    code: 'l-ellipsis',
    unitCode: 'unit-advanced-analysis',
    title: 'What gets omitted, and why',
    titleArabic: 'الحذف والتقدير',
    summary: 'Recoverable omission as a normal, rule-governed compression.',
    order: 1,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-ellipsis-and-estimation', role: 'introduces' }],
    observeSentenceCodes: ['nom-02-demonstrative-indefinite-khabar'],
    discoveryPrompt: 'A sign reading simply "ممنوعٌ" ("forbidden") is a complete, understood sentence in context, even with no visible مبتدأ. What is the missing word doing?',
    microExplanation:
      'Arabic regularly omits a word whose identity is fully recoverable from context or convention, while the role that word would have played is still "estimated" (مُقدَّر) for the purposes of analysis. Without this concept, an omission looks like a broken sentence instead of a normal compression.',
  },
  {
    code: 'l-mahall',
    unitCode: 'unit-advanced-analysis',
    title: 'When a whole clause has a syntactic position',
    titleArabic: 'محل الجملة من الإعراب',
    summary: 'Clauses do not carry case endings — but they still occupy a slot.',
    order: 2,
    estimatedMinutes: 20,
    concepts: [{ conceptCode: 'c-mahall-al-jumla', role: 'introduces' }],
    observeSentenceCodes: ['part-04-kana-imperfect', 'verb-04-fronted-subject-full-agreement'],
    discoveryPrompt: 'يَكْتُبُ الدَّرْسَ, as the خبر of كَانَ, has no case ending of its own — a whole clause can\'t take a single vowel. So in what sense is it still "accusative"?',
    microExplanation:
      'An embedded clause has no case ending, yet it still occupies a syntactic slot equivalent to whatever single word could have filled it — grammarians say it "has a position" (لها محل). This is what makes full إعراب of sentences with embedded clauses possible.',
  },
];
