export interface MisconceptionSeed {
  code: string;
  title: string;
  description: string;
  evidencePattern: string;
  correctModel: string;
  contrastExample: string;
  repairGuidance: string;
  conceptCodes: string[];
}

export const misconceptions: MisconceptionSeed[] = [
  {
    code: 'mis-first-noun-is-subject',
    title: 'Assuming the first noun is always the subject',
    description: 'Treating whichever noun appears first in the sentence as the فاعل, by analogy with English subject-first word order.',
    evidencePattern: 'In كَتَبَ الطَّالِبُ الدَّرْسَ, learner correctly identifies الطالب as subject (it happens to be first noun), but then in a sentence like رَأَى الطَّالِبَ الْمُعَلِّمُ, misidentifies الطالبَ (accusative, first noun encountered after the verb) as the subject rather than checking its case ending.',
    correctModel: 'The فاعل is decided by case marking and grammatical behavior, not by linear position. Arabic is verb-first by default, and word order can shift for emphasis without changing grammatical roles.',
    contrastExample: 'رَأَى الْمُعَلِّمُ الطَّالِبَ ("The teacher saw the student") vs. رَأَى الطَّالِبَ الْمُعَلِّمُ ("The teacher saw the student," object fronted for emphasis) — both mean the same thing because الْمُعَلِّمُ is nominative in both, regardless of position.',
    repairGuidance: 'Before assigning a role, find the case ending first. Only after confirming nominative should a noun be called فاعل.',
    conceptCodes: ['c-fi-l-fa-il'],
  },
  {
    code: 'mis-faail-vs-ism-al-faail',
    title: 'Confusing فاعل with اسم الفاعل',
    description: 'Treating "active participle" (a morphological shape) and "subject" (a syntactic role) as the same concept because both come from the same root ف ع ل.',
    evidencePattern: 'Learner says a word "is a فاعل" because it looks like an اسم فاعل pattern (فَاعِل), without checking whether it is actually performing the subject role in that sentence.',
    correctModel: 'اسم الفاعل is a word-shape (a noun pattern naming a doer); فاعل is a job a word performs in a specific sentence. An اسم فاعل can serve as فاعل, مفعول به, مبتدأ, or any other role, depending on the sentence.',
    contrastExample: 'الكَاتِبُ حَاضِرٌ ("The writer is present") — كاتب (an اسم فاعل) here is مبتدأ, not فاعل, because this is a nominal, not verbal, sentence.',
    repairGuidance: 'Always ask two separate questions: "What shape is this word?" (morphology) and "What job is it doing here?" (syntax). Never let the answer to one substitute for the other.',
    conceptCodes: ['c-active-passive-participle', 'c-fi-l-fa-il'],
  },
  {
    code: 'mis-damma-always-subject',
    title: 'Treating every ḍammah as evidence of subjecthood',
    description: 'Assuming any word ending in ḍammah must be the فاعل, ignoring that ḍammah is simply the nominative marker shared by مبتدأ, خبر, فاعل, and نائب الفاعل alike.',
    evidencePattern: 'In الطَّالِبُ مُجْتَهِدٌ, learner labels both الطالب and مجتهد as "subjects" because both end in ḍammah.',
    correctModel: 'ḍammah marks the nominative case generally, which is the default home for several distinct roles (مبتدأ، خبر، فاعل، نائب الفاعل) — the ending narrows the case, not the specific role.',
    contrastExample: 'الطَّالِبُ مُجْتَهِدٌ: both words are nominative, but only الطالب is مبتدأ and only مجتهد is خبر — neither is فاعل, because this is a nominal, not verbal, sentence.',
    repairGuidance: 'After identifying the case from the ending, still ask whether the sentence is nominal or verbal, and where the word sits in that structure, before naming its exact role.',
    conceptCodes: ['c-irab-concept', 'c-three-cases'],
  },
  {
    code: 'mis-kasra-always-genitive-possession',
    title: 'Treating every kasrah as ordinary possessive genitive',
    description: 'Assuming a kasrah-marked noun is always the second term of an إضافة, ignoring that كسرة also marks the object of any preposition.',
    evidencePattern: 'In سَلَّمْتُ عَلَى الطَّالِبِ, learner says الطالبِ is "possessed by" على, confusing prepositional government with possession.',
    correctModel: 'Genitive case has two distinct triggers: being a مضاف إليه (possession-like) or being governed by a preposition (حرف جر). Both produce kasrah, but the grammatical relationship is different.',
    contrastExample: 'كِتَابُ الطَّالِبِ (idafa: "the student\'s book") vs. سَلَّمْتُ عَلَى الطَّالِبِ ("I greeted the student," prepositional government) — both show kasrah on الطالب for entirely different structural reasons.',
    repairGuidance: 'Check what precedes the genitive noun: a bare noun (idafa) or a preposition (government). Name the relationship accordingly, not just the case.',
    conceptCodes: ['c-idafa', 'c-prepositional-phrase'],
  },
  {
    code: 'mis-ignoring-government',
    title: 'Ignoring grammatical government (العامل)',
    description: 'Assigning case by guessing at meaning rather than identifying the specific word or particle responsible for the ending.',
    evidencePattern: 'Learner cannot say why الطالبَ is accusative in إِنَّ الطَّالِبَ مُجْتَهِدٌ beyond "it feels like an object."',
    correctModel: 'Every non-default case ending has a specific, nameable governor: a preposition, إنّ or a sister, كان or a sister, a verb assigning مفعول به, etc. "Feeling like an object" is never sufficient justification.',
    contrastExample: 'الطَّالِبَ is accusative in إِنَّ الطَّالِبَ مُجْتَهِدٌ because إنّ governs it — not because الطالب is doing or receiving any action.',
    repairGuidance: 'For every non-nominative ending, name the exact governing word before accepting the case as correct.',
    conceptCodes: ['c-irab-concept', 'c-inna-wa-akhawatuha'],
  },
  {
    code: 'mis-forgetting-adjective-agreement',
    title: 'Forgetting one of the four adjective agreement features',
    description: 'Matching an adjective to its noun in gender and number, but forgetting definiteness or case (most often definiteness).',
    evidencePattern: 'Learner produces "الطالب مجتهدة" or "بنت جميل" — gender/number correct but a feature dropped, or produces "طالب المجتهد" — indefinite noun with definite adjective.',
    correctModel: 'نعت agreement requires all four features simultaneously: gender, number, definiteness, and case. Missing any one produces an ungrammatical phrase, not just an awkward one.',
    contrastExample: 'طَالِبٌ مُجْتَهِدٌ (both indefinite) vs. الطَّالِبُ الْمُجْتَهِدُ (both definite) — mixing ال onto only one word is not acceptable Arabic.',
    repairGuidance: 'Run all four checks explicitly every time, even after fluency starts to develop — this is exactly the kind of error automatic habits hide.',
    conceptCodes: ['c-adjective-agreement'],
  },
  {
    code: 'mis-idafa-definiteness',
    title: 'Confusing definiteness rules inside إضافة',
    description: 'Adding ال to the مضاف (first term), or failing to recognize that a مضاف with an indefinite مضاف إليه is itself indefinite.',
    evidencePattern: 'Learner writes "الكتاب الطالب" attempting "the student\'s book," incorrectly doubling ال onto the first noun.',
    correctModel: 'The مضاف never takes ال or تنوين. Its definiteness is entirely inherited from the مضاف إليه: كِتَابُ طَالِبٍ ("a student\'s book," indefinite) vs. كِتَابُ الطَّالِبِ ("the student\'s book," definite) — the only thing that changes is the second word.',
    contrastExample: 'كِتَابُ الطَّالِبِ is correct; الْكِتَابُ الطَّالِبِ and كِتَابٌ الطَّالِبِ are both ungrammatical attempts at the same meaning.',
    repairGuidance: 'Before adding ال to any noun, check whether it is immediately followed by another noun in a possessive relationship — if so, ال belongs only on the second noun (or not at all, if the phrase should be indefinite).',
    conceptCodes: ['c-idafa', 'c-definiteness'],
  },
  {
    code: 'mis-english-word-order-decisive',
    title: 'Using English word order as decisive for role',
    description: 'Assuming the noun in the English-subject position of a translated sentence must correspond to the Arabic فاعل, regardless of Arabic case marking.',
    evidencePattern: 'In a sentence like رَأَى الْمُعَلِّمَ الطَّالِبُ (unusual but valid order, object fronted before subject due to context), learner defaults to whichever noun "sounds like" the subject in the English gloss.',
    correctModel: 'Arabic case, not translated word order, decides grammatical role. Word order in Arabic can shift for topic, focus, or emphasis without changing who does what to whom.',
    contrastExample: 'رَأَى الْمُعَلِّمَ الطَّالِبُ still means "the student saw the teacher," because الطالبُ (nominative) is the فاعل no matter which noun the English sentence structure would put first.',
    repairGuidance: 'Translate meaning only after confirming case-based roles — never let the English translation you are drafting talk you into a role assignment the Arabic endings do not support.',
    conceptCodes: ['c-fi-l-fa-il', 'c-irab-concept'],
  },
  {
    code: 'mis-missing-embedded-pronoun',
    title: 'Failing to identify an embedded subject pronoun',
    description: 'Looking for a separate word to serve as فاعل and concluding a sentence "has no subject" when the subject is actually fused into the verb as an attached pronoun.',
    evidencePattern: 'Given كَتَبْتُ الدَّرْسَ, learner asks "where is the فاعل?" because no separate noun follows the verb.',
    correctModel: 'A perfect verb\'s person/gender/number suffix (ـتُ، ـتْ، ـوا، etc.) is itself the فاعل when no separate noun is present — it is a hidden/attached pronoun (ضمير مستتر أو متصل), not an absence of a subject.',
    contrastExample: 'كَتَبْتُ الدَّرْسَ ("I wrote the lesson") has a complete فاعل: the ـتُ suffix meaning "I," fully doing the grammatical job a separate noun would otherwise do.',
    repairGuidance: 'Before concluding a verb has no فاعل, check its person/gender/number suffix — it very likely is the فاعل.',
    conceptCodes: ['c-perfect-tense', 'c-fi-l-fa-il'],
  },
  {
    code: 'mis-case-on-indeclinables',
    title: 'Applying case endings to indeclinable words',
    description: 'Attempting to add or alter case vowels on بناء (built) words — pronouns, demonstratives, most particles — which never change ending regardless of role.',
    evidencePattern: 'Learner tries to vocalize هذا as if it should show a case-appropriate ending, such as adding a genitive-style vowel after a preposition.',
    correctModel: 'مبني (built) words keep one fixed form no matter their syntactic role. Their case is still assigned and can still be named ("in the position of genitive"), but it is never audible or written as a changing vowel.',
    contrastExample: 'مِنْ هَذَا ("from this") — هذا does not change to show the genitive that من would otherwise impose on a معرب noun; it stays هذا regardless.',
    repairGuidance: 'Learn the closed list of مبني word classes (most particles, pronouns, demonstratives, most relative nouns) and stop expecting them to visibly inflect.',
    conceptCodes: ['c-irab-concept', 'c-marker-types'],
  },
  {
    code: 'mis-verbs-no-person-gender',
    title: 'Conjugating Arabic verbs as though they carried no person or gender information',
    description: 'Treating an Arabic verb as a single invariant form and relying entirely on a separate pronoun to signal who is acting, as many learners over-generalize from English "the verb barely changes."',
    evidencePattern: 'Learner writes "أنا ذهب" instead of "أنا ذهبتُ" or "هي ذهب" instead of "هي ذهبتْ," leaving the verb in a bare, unmarked shape.',
    correctModel: 'Arabic verbs obligatorily encode person, gender, and (in the perfect) number through prefixes and suffixes; the verb form itself is not optional or invariant the way English "go/went" mostly is across persons.',
    contrastExample: 'ذَهَبْتُ ("I went"), ذَهَبَتْ ("she went"), ذَهَبُوا ("they, m., went") are three different words, not one word plus three separate pronouns.',
    repairGuidance: 'Always conjugate the verb fully for its subject\'s person, gender, and number — never leave it in a bare dictionary-citation shape inside a real sentence.',
    conceptCodes: ['c-perfect-tense'],
  },
  {
    code: 'mis-pattern-vs-role',
    title: 'Confusing a morphological pattern with a syntactic role',
    description: 'Treating a word\'s pattern name (e.g. "this is a مفعول pattern word") as if it directly told you the word\'s job in the current sentence.',
    evidencePattern: 'Learner assumes any مَفْعُول-pattern word must be a مفعول به in its sentence.',
    correctModel: 'A pattern (وزن) describes a word\'s shape and its typical derivational meaning; a syntactic role (like مفعول به) describes what job the word performs in one specific sentence. The same shaped word can fill many different roles across different sentences.',
    contrastExample: 'الْمَكْتُوبُ وَاضِحٌ ("The written [thing] is clear") — مكتوب (a مفعول-pattern word) is مبتدأ here, not مفعول به.',
    repairGuidance: 'Separate the two questions explicitly every time: "What shape is this?" and "What is it doing in this sentence?"',
    conceptCodes: ['c-active-passive-participle', 'c-root-and-pattern'],
  },
  {
    code: 'mis-same-day-mastery-illusion',
    title: 'Assuming same-day repetition guarantees retention',
    description: "Treating a strong streak of correct answers within a single study session as proof a concept is durably learned, when it may only reflect short-term working memory or pattern-matching against the immediately preceding examples.",
    evidencePattern: 'Learner answers 10 questions on a rule correctly in a row today, then fails the identical rule two days later with no intervening practice.',
    correctModel: 'Durable mastery requires evidence across a real time gap, not just volume within one sitting — this is why mastery labels in this app require multi-day evidence and why the review scheduler exists at all.',
    contrastExample: 'A learner who gets a concept "Strong" after one long session but fails its next scheduled review is not experiencing a broken system — they are experiencing exactly the gap this app is built to catch and correct.',
    repairGuidance: 'Trust the scheduled review queue over same-day confidence. If a concept feels "done" after one session, the review queue — not that feeling — determines whether it actually is.',
    conceptCodes: [],
  },
  {
    code: 'mis-broken-plural-agreement',
    title: 'Applying human-plural agreement rules to non-human plurals',
    description: 'Expecting a plural adjective or verb form to agree with a non-human plural noun the same way it would with a human plural, rather than treating the non-human plural as grammatically feminine singular for agreement.',
    evidencePattern: 'Learner produces "الكتب الجديدون" (masculine sound plural adjective) for "the new books" instead of the correct feminine-singular-pattern agreement.',
    correctModel: 'Non-human plurals (whether broken or sound) trigger feminine-singular agreement on their adjectives and verbs, regardless of the actual gender of the singular noun — a rule with no analogue in English or Yorùbá plural agreement.',
    contrastExample: 'الْكُتُبُ الْجَدِيدَةُ ("the new books") uses feminine-singular الجديدة to agree with كتب, even though a single كِتَاب is grammatically masculine.',
    repairGuidance: 'For any non-human plural noun, default its agreement targets to feminine singular rather than trying to match the plural noun\'s own gender and number directly.',
    conceptCodes: ['c-gender-number-of-nouns', 'c-adjective-agreement'],
  },
  {
    code: 'mis-marker-type-confusion',
    title: 'Confusing visible, secondary, and estimated markers',
    description: 'Assuming a case must be audible/written as a short vowel to "count," and concluding a word "has no case" when its marker is secondary (a suffix) or estimated (unpronounceable).',
    evidencePattern: 'Learner says الطالبان "has no case ending" because they are looking for a short vowel rather than recognizing ـَانِ as the marker itself.',
    correctModel: 'All three marker types are equally real evidence of case; they simply differ in what they look or sound like. A missing short vowel does not mean a missing case.',
    contrastExample: 'الطَّالِبَانِ (secondary marker ـَانِ) and مِصْرَ (estimated/substituted marker, diptote fatḥah) both fully participate in the case system, despite neither showing an ordinary singular-style short vowel.',
    repairGuidance: 'Ask "what is this noun\'s category (singular / dual / sound plural / diptote / defective)?" before deciding what its case marker should even look like.',
    conceptCodes: ['c-marker-types', 'c-dual-and-sound-plurals', 'c-diptotes'],
  },
];
