export interface PlacementQuestionSeed {
  code: string;
  skillArea: string;
  prompt: string;
  promptArabic?: string;
  type: 'multiple_choice' | 'short_answer' | 'sorting' | 'free_text';
  options?: string[];
  correctAnswer: string | string[];
  difficulty: number;
}

export const placementQuestions: PlacementQuestionSeed[] = [
  {
    code: 'ph-01-reading-comfort',
    skillArea: 'reading_comfort',
    prompt: 'Can you read this word aloud, sound by sound, even without knowing its meaning?',
    promptArabic: 'كِتَاب',
    type: 'multiple_choice',
    options: ['Yes, comfortably', 'Slowly, letter by letter', 'Not yet — the script itself is still unfamiliar'],
    correctAnswer: 'Yes, comfortably',
    difficulty: 1,
  },
  {
    code: 'ph-02-word-category',
    skillArea: 'word_category',
    prompt: 'Which of these three words is a فعل (verb)?',
    promptArabic: 'كَتَبَ  —  كِتَاب  —  فِي',
    type: 'multiple_choice',
    options: ['كَتَبَ', 'كِتَاب', 'فِي'],
    correctAnswer: 'كَتَبَ',
    difficulty: 1,
  },
  {
    code: 'ph-03-word-category-particle',
    skillArea: 'word_category',
    prompt: 'Which of these words is a حرف (particle) — meaningless on its own?',
    promptArabic: 'طَالِب  —  عَلَى  —  ذَهَبَ',
    type: 'multiple_choice',
    options: ['طَالِب', 'عَلَى', 'ذَهَبَ'],
    correctAnswer: 'عَلَى',
    difficulty: 1,
  },
  {
    code: 'ph-04-sentence-meaning',
    skillArea: 'sentence_meaning',
    prompt: 'What does this sentence mean?',
    promptArabic: 'الطَّالِبُ مُجْتَهِدٌ',
    type: 'multiple_choice',
    options: ['The student is diligent.', 'The student wrote a book.', 'The diligent student left.'],
    correctAnswer: 'The student is diligent.',
    difficulty: 1,
  },
  {
    code: 'ph-05-nominal-vs-verbal',
    skillArea: 'nominal_verbal',
    prompt: 'Is this a nominal sentence (starts with a noun) or a verbal sentence (starts with a verb)?',
    promptArabic: 'كَتَبَ الطَّالِبُ الدَّرْسَ',
    type: 'multiple_choice',
    options: ['Nominal', 'Verbal'],
    correctAnswer: 'Verbal',
    difficulty: 1,
  },
  {
    code: 'ph-06-sentence-meaning-2',
    skillArea: 'sentence_meaning',
    prompt: 'Who wrote the lesson?',
    promptArabic: 'كَتَبَ الطَّالِبُ الدَّرْسَ',
    type: 'short_answer',
    correctAnswer: ['the student', 'الطالب', 'aṭ-ṭālib'],
    difficulty: 2,
  },
  {
    code: 'ph-07-agreement-gender',
    skillArea: 'agreement',
    prompt: 'Fill in the correct form of the verb ذهب ("went") to agree with الطَّالِبَةُ (a female student): ___ الطَّالِبَةُ إِلَى الْمَدْرَسَةِ',
    type: 'short_answer',
    correctAnswer: ['ذَهَبَتْ', 'ذهبت'],
    difficulty: 2,
  },
  {
    code: 'ph-08-case-awareness-nominative',
    skillArea: 'case_awareness',
    prompt: 'In كَتَبَ الطَّالِبُ الدَّرْسَ, which word is nominative (مرفوع)?',
    type: 'multiple_choice',
    options: ['كَتَبَ', 'الطَّالِبُ', 'الدَّرْسَ'],
    correctAnswer: 'الطَّالِبُ',
    difficulty: 2,
  },
  {
    code: 'ph-09-case-awareness-accusative',
    skillArea: 'case_awareness',
    prompt: 'In the same sentence, which word is accusative (منصوب), and why?',
    promptArabic: 'كَتَبَ الطَّالِبُ الدَّرْسَ',
    type: 'short_answer',
    correctAnswer: ['الدرس, because it is the direct object', 'الدَّرْسَ — مفعول به'],
    difficulty: 3,
  },
  {
    code: 'ph-10-nominal-vs-verbal-agreement',
    skillArea: 'agreement',
    prompt: 'Why does the verb stay singular (كَتَبَ, not كَتَبُوا) even though الطُّلَّابُ ("the students") is plural, in كَتَبَ الطُّلَّابُ الدَّرْسَ?',
    type: 'multiple_choice',
    options: [
      'Because the verb comes before its subject, which is the default rule for verb–subject agreement.',
      'Because طلاب is actually singular in meaning.',
      'It is a mistake — the sentence should read كَتَبُوا.',
    ],
    correctAnswer: 'Because the verb comes before its subject, which is the default rule for verb–subject agreement.',
    difficulty: 3,
  },
  {
    code: 'ph-11-conjugation',
    skillArea: 'conjugation',
    prompt: 'Conjugate كتب ("to write") in the perfect tense for "I": أنا ___ الدرسَ.',
    type: 'short_answer',
    correctAnswer: ['كَتَبْتُ', 'كتبت'],
    difficulty: 2,
  },
  {
    code: 'ph-12-conjugation-imperfect',
    skillArea: 'conjugation',
    prompt: 'What does يَكْتُبُ mean, and what does the ي at the front tell you?',
    type: 'free_text',
    correctAnswer: ['he writes / is writing; the ي marks third person masculine in the imperfect'],
    difficulty: 3,
  },
  {
    code: 'ph-13-root-pattern',
    skillArea: 'root_pattern',
    prompt: 'كَاتِب، مَكْتُوب، and كِتَابَة all share the same three-letter root. What is it, and what does it mean?',
    type: 'short_answer',
    correctAnswer: ['ك ت ب — writing', 'k-t-b, writing'],
    difficulty: 2,
  },
  {
    code: 'ph-14-root-pattern-inference',
    skillArea: 'root_pattern',
    prompt: 'If فَاعِل is the pattern that names "the one who does the action," and the root ف ه م means "understanding," what word would you expect this pattern to produce, and what would it mean?',
    type: 'free_text',
    correctAnswer: ['فَاهِم — one who understands'],
    difficulty: 4,
  },
  {
    code: 'ph-15-inference',
    skillArea: 'inference',
    prompt: 'Compare كَتَبَ الطَّالِبُ الدَّرْسَ and كُتِبَ الدَّرْسُ. What changed about الدرس\'s case, and what does that tell you about who is doing the writing in the second sentence?',
    type: 'free_text',
    correctAnswer: ['الدرس becomes nominative in the passive sentence; the agent (who wrote it) is not mentioned at all.'],
    difficulty: 4,
  },
  {
    code: 'ph-16-explanation',
    skillArea: 'explanation',
    prompt: 'Explain, in your own words, why الطَّالِبَ is accusative in إِنَّ الطَّالِبَ مُجْتَهِدٌ, when the same word was nominative in الطَّالِبُ مُجْتَهِدٌ.',
    type: 'free_text',
    correctAnswer: ['إنّ governs the following noun and forces it into the accusative, changing its role from مبتدأ to اسم إنّ.'],
    difficulty: 4,
  },
  {
    code: 'ph-17-diptote-inference',
    skillArea: 'inference',
    prompt: 'سَافَرْتُ إِلَى مِصْرَ ends with a فتحة on مِصْرَ, not the كسرة you would expect after إلى. Can you guess why, based on anything you already know about Arabic proper names?',
    type: 'free_text',
    correctAnswer: ['مصر is a diptote (feminine proper name without ة), so it takes fatḥah instead of kasrah for the genitive and has no tanwīn.'],
    difficulty: 5,
  },
  {
    code: 'ph-18-explanation-agreement',
    skillArea: 'explanation',
    prompt: 'الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ has three nominative words, but المجتهد and حاضر are doing two different jobs. Explain the difference.',
    type: 'free_text',
    correctAnswer: [
      'المجتهد is a نعت (attributive adjective) agreeing with الطالب in all four features (gender, number, definiteness, case); حاضر is the خبر of the whole sentence, agreeing only in case.',
    ],
    difficulty: 5,
  },
];
