import type { SentenceSeed } from '../sentenceTypes';

export const caseSentences: SentenceSeed[] = [
  {
    code: 'case-01-nominative-triplet',
    textVocalized: 'حَضَرَ الطَّالِبُ',
    textUnvocalized: 'حضر الطالب',
    transliteration: 'ḥaḍara ṭ-ṭālibu',
    translationEnglish: 'The student was present.',
    difficulty: 1,
    notes: 'First of a three-sentence set using the same noun, الطالب, across all three cases (see case-02, case-03).',
    tokens: [
      { position: 1, surfaceVocalized: 'حَضَرَ', surfaceUnvocalized: 'حضر', lemma: 'حضر', rootRadicals: 'ح ض ر', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'was present', explanation: 'Intransitive Form I verb.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Nominative: home case of the فاعل.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the being-present.' }],
  },
  {
    code: 'case-02-accusative-triplet',
    textVocalized: 'رَأَيْتُ الطَّالِبَ',
    textUnvocalized: 'رأيت الطالب',
    transliteration: "raʾaytu ṭ-ṭāliba",
    translationEnglish: 'I saw the student.',
    difficulty: 2,
    notes: 'Second of the triplet: same noun, now مفعول به, accusative. Also introduces the first-person perfect suffix ـتُ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', stem: 'رأي', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb, with its own attached subject pronoun', translation: 'I saw', explanation: 'ـتُ is the attached first-person-singular subject pronoun fused onto the perfect stem — the whole word رَأَيْتُ is itself a complete little sentence, "I saw."' },
      { position: 2, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student', explanation: 'Same noun as case-01, now accusative because it is the object, not the subject: the ending changed, not the word\'s identity.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الطالب is what is seen.' }],
  },
  {
    code: 'case-03-genitive-triplet',
    textVocalized: 'مَرَرْتُ بِالطَّالِبِ',
    textUnvocalized: 'مررت بالطالب',
    transliteration: 'marartu bi-ṭ-ṭālibi',
    translationEnglish: 'I passed by the student.',
    difficulty: 2,
    notes: 'Third of the triplet: same noun, now genitive after the preposition بِ ("by/with").',
    tokens: [
      { position: 1, surfaceVocalized: 'مَرَرْتُ', surfaceUnvocalized: 'مررت', lemma: 'مر', stem: 'مرر', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I passed', explanation: 'A doubled root (م ر ر) with the attached first-person suffix.' },
      { position: 2, surfaceVocalized: 'بِالطَّالِبِ', surfaceUnvocalized: 'بالطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'بال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the student', explanation: 'The same noun a third time — now genitive purely because بِ governs it. Across all three sentences, الطالب never changed meaning; only its grammatical role, and with it, its ending, changed.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'preposition_object', explanation: 'بِ governs الطالب.' }],
  },
  {
    code: 'case-04-dual-predicate',
    textVocalized: 'الطَّالِبَانِ مُجْتَهِدَانِ',
    textUnvocalized: 'الطالبان مجتهدان',
    transliteration: 'aṭ-ṭālibāni mujtahidāni',
    translationEnglish: 'The two students are diligent.',
    difficulty: 2,
    notes: 'Unlike a fronted verb\'s agreement, a khabar that is a single adjective-like word DOES fully agree in number: both mubtada and khabar are dual here.',
    tokens: [
      { position: 1, surfaceVocalized: 'الطَّالِبَانِ', surfaceUnvocalized: 'الطالبان', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ان', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ـَانِ', markerType: 'secondary', translation: 'the two students', explanation: 'Dual nominative suffix.' },
      { position: 2, surfaceVocalized: 'مُجْتَهِدَانِ', surfaceUnvocalized: 'مجتهدان', lemma: 'مجتهد', suffix: 'ان', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـَانِ', markerType: 'secondary', translation: 'diligent (dual)', explanation: 'The khabar copies the mubtada\'s number here because it is a single descriptive word, not a following verb — the "verb stays singular" rule only applies to actual verbs.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مجتهدان is predicated of الطالبان and matches its dual number.' }],
  },
  {
    code: 'case-05-dual-accusative',
    textVocalized: 'رَأَيْتُ الطَّالِبَيْنِ',
    textUnvocalized: 'رأيت الطالبين',
    transliteration: 'raʾaytu ṭ-ṭālibayni',
    translationEnglish: 'I saw the two students.',
    difficulty: 2,
    notes: 'The dual has only one non-nominative suffix, covering both accusative and genitive: ـَيْنِ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I saw', explanation: 'Same verb as case-02.' },
      { position: 2, surfaceVocalized: 'الطَّالِبَيْنِ', surfaceUnvocalized: 'الطالبين', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ين', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'ـَيْنِ (dual accusative/genitive)', markerType: 'secondary', translation: 'the two students', explanation: 'Unlike the singular (which distinguishes fatḥah from kasrah), the dual collapses accusative and genitive into one shared suffix.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الطالبين is what is seen.' }],
  },
  {
    code: 'case-06-sound-plural-predicate',
    textVocalized: 'الْمُعَلِّمُونَ حَاضِرُونَ',
    textUnvocalized: 'المعلمون حاضرون',
    transliteration: 'al-muʿallimūna ḥāḍirūna',
    translationEnglish: 'The teachers are present.',
    difficulty: 2,
    tokens: [
      { position: 1, surfaceVocalized: 'الْمُعَلِّمُونَ', surfaceUnvocalized: 'المعلمون', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ون', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ـُونَ (sound masculine plural nominative)', markerType: 'secondary', translation: 'the teachers', explanation: 'Sound masculine plural: a real "regular" plural, formed by a predictable suffix rather than an internal change.' },
      { position: 2, surfaceVocalized: 'حَاضِرُونَ', surfaceUnvocalized: 'حاضرون', lemma: 'حاضر', rootRadicals: 'ح ض ر', patternLabel: 'Active participle (Form I) — فَاعِل', suffix: 'ون', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـُونَ', markerType: 'secondary', translation: 'present (plural)', explanation: 'Agrees fully in number since it is a single-word khabar, not a following verb.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'حاضرون is predicated of المعلمون.' }],
  },
  {
    code: 'case-07-sound-plural-accusative',
    textVocalized: 'رَأَيْتُ الْمُعَلِّمِينَ',
    textUnvocalized: 'رأيت المعلمين',
    transliteration: 'raʾaytu l-muʿallimīna',
    translationEnglish: 'I saw the teachers.',
    difficulty: 2,
    notes: 'Sound masculine plural, like the dual, collapses accusative and genitive into one suffix: ـِينَ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I saw', explanation: 'Same verb as before.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمِينَ', surfaceUnvocalized: 'المعلمين', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ين', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'ـِينَ (sound masculine plural accusative/genitive)', markerType: 'secondary', translation: 'the teachers', explanation: 'Contrast with case-06\'s ـُونَ: the same word takes ـِينَ once it is no longer nominative.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'المعلمين is what is seen.' }],
  },
  {
    code: 'case-08-diptote-genitive',
    textVocalized: 'سَافَرْتُ إِلَى مِصْرَ',
    textUnvocalized: 'سافرت إلى مصر',
    transliteration: 'sāfartu ilā miṣra',
    translationEnglish: 'I traveled to Egypt.',
    difficulty: 3,
    notes: 'مِصْرَ is a diptote (ممنوع من الصرف) — a feminine proper name with no ة. Genitive is shown by فتحة instead of the expected كسرة, and there is no تنوين.',
    tokens: [
      { position: 1, surfaceVocalized: 'سَافَرْتُ', surfaceUnvocalized: 'سافرت', lemma: 'سافر', stem: 'سافر', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I traveled', explanation: 'Form III verb سَافَرَ with the first-person suffix.' },
      { position: 2, surfaceVocalized: 'إِلَى', surfaceUnvocalized: 'إلى', lemma: 'إلى', partOfSpeech: 'particle', role: 'preposition (direction)', translation: 'to', explanation: 'Governs مصر into the genitive.' },
      { position: 3, surfaceVocalized: 'مِصْرَ', surfaceUnvocalized: 'مصر', lemma: 'مصر', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'fatḥah, no tanwīn (diptote genitive)', markerType: 'secondary', translation: 'Egypt', explanation: 'Because مصر is a diptote (a feminine proper name without ة), it borrows the accusative\'s فتحة to mark the genitive instead of the usual كسرة, and never takes تنوين at all — a closed, learnable exception class, not a random irregularity.', traditionalExplanation: 'اسم مجرور وعلامة جره الفتحة نيابة عن الكسرة لأنه ممنوع من الصرف.' },
    ],
    dependencies: [{ headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'إلى governs مصر, whose genitive shows as a diptote fatḥah.' }],
  },
  {
    code: 'case-09-diptote-broken-plural-genitive',
    textVocalized: 'صَلَّيْتُ فِي مَسَاجِدَ',
    textUnvocalized: 'صليت في مساجد',
    transliteration: 'ṣallaytu fī masājida',
    translationEnglish: 'I prayed in mosques.',
    difficulty: 3,
    notes: 'A second diptote category, distinct from case-08\'s proper-name class: broken plurals of the pattern مَفَاعِل (three or more syllables with a long vowel before the final consonant) are also diptote — فتحة for the genitive, no تنوين, even while remaining indefinite in meaning.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'صَلَّيْتُ', surfaceUnvocalized: 'صليت', lemma: 'صلى', rootRadicals: 'ص ل و', patternLabel: 'Form II — فَعَّلَ',
        stem: 'صلي', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular',
        role: 'the verb, with its own attached subject pronoun', translation: 'I prayed',
        explanation: 'Form II of the defective root ص ل و, with the attached first-person suffix.',
      },
      {
        position: 2, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'preposition (location)',
        translation: 'in', explanation: 'Governs مساجد into the genitive.',
      },
      {
        position: 3, surfaceVocalized: 'مَسَاجِدَ', surfaceUnvocalized: 'مساجد', lemma: 'مسجد', rootRadicals: 'س ج د', patternLabel: 'Diptote broken plural — مَفَاعِل',
        partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'indefinite', grammaticalCase: 'genitive',
        role: 'majrūr', marker: 'fatḥah, no tanwīn (diptote genitive)', markerType: 'secondary', translation: 'mosques',
        explanation: 'مساجد follows the diptote plural pattern مَفَاعِل — it takes فتحة instead of كسرة for the genitive and never carries تنوين, even though it remains indefinite in meaning. This is a different diptote trigger from case-08\'s proper name: broken plurals of this shape are diptote as a category, regardless of what they name.',
        traditionalExplanation: 'اسم مجرور وعلامة جره الفتحة نيابة عن الكسرة لأنه ممنوع من الصرف على وزن منتهى الجموع.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'في governs مساجد, whose genitive appears as a diptote fatḥah rather than the expected kasrah.' },
    ],
  },
  {
    code: 'case-10-sound-feminine-plural-accusative',
    textVocalized: 'رَأَيْتُ الْمُعَلِّمَاتِ',
    textUnvocalized: 'رأيت المعلمات',
    transliteration: 'raʾaytu l-muʿallimāti',
    translationEnglish: 'I saw the female teachers.',
    difficulty: 2,
    notes: 'The sound feminine plural (جمع المؤنث السالم) marks accusative and genitive identically — not with a distinct suffix the way the dual and sound masculine plural do, but by swapping the final short vowel: ḍammah in the nominative becomes kasrah here.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', stem: 'رأي', suffix: 'تُ', partOfSpeech: 'verb',
        person: 'first', number: 'singular', role: 'the verb, with its own attached subject pronoun', translation: 'I saw',
        explanation: 'Same verb as case-02 and case-05.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمَاتِ', surfaceUnvocalized: 'المعلمات', lemma: 'معلمة', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ات',
        partOfSpeech: 'noun', gender: 'feminine', number: 'plural', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'kasrah (ـِ) — sound feminine plural accusative/genitive marker, substituting for fatḥah', markerType: 'secondary',
        translation: 'the female teachers',
        explanation: 'المعلمات keeps the same ات suffix in the nominative, accusative, and genitive alike; only the short vowel on ت changes (ḍammah → kasrah) to signal that it is no longer nominative. This is a third distinct mechanism for marking non-default case, alongside the dual\'s and sound-masculine-plural\'s dedicated suffixes.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'المعلماتِ is what is seen; its accusative shows as كسرة rather than فتحة.' },
    ],
  },
  {
    code: 'case-11-irab-concept-mixed',
    textVocalized: 'رَأَى الْمُعَلِّمُ طَالِبًا فِي الْفَصْلِ',
    textUnvocalized: 'رأى المعلم طالبا في الفصل',
    transliteration: 'raʾā l-muʿallimu ṭāliban fī l-faṣli',
    translationEnglish: 'The teacher saw a student in the classroom.',
    difficulty: 3,
    notes: 'All three cases inside a single sentence: nominative (fāʿil), accusative (mafʿūl bihi), and genitive (after a preposition) — the clearest possible one-sentence illustration of what إعراب actually tracks.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'رَأَى', surfaceUnvocalized: 'رأى', lemma: 'رأى', rootRadicals: 'ر أ ي', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl', marker: 'estimated fatḥah (blocked by the final ى)', markerType: 'estimated', translation: 'saw',
        explanation: 'رأى ends in ى (a defective root, ر أ ي), so its own fatḥah is estimated rather than pronounced.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher',
        explanation: 'المعلم performs the seeing, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'طَالِبًا', surfaceUnvocalized: 'طالبا', lemma: 'طالب', rootRadicals: 'ط ل ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a student',
        explanation: 'طالبًا is what is seen, so it is accusative as مفعول به.',
      },
      {
        position: 4, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'ḥarf jarr (preposition)',
        marker: 'built (مبني)', markerType: 'positional', translation: 'in',
        explanation: 'في never takes a case ending itself — it governs the following noun into the genitive.',
      },
      {
        position: 5, surfaceVocalized: 'الْفَصْلِ', surfaceUnvocalized: 'الفصل', lemma: 'فصل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr of في', marker: 'kasrah (ـِ)', markerType: 'visible',
        translation: 'the classroom',
        explanation: 'Three words, three cases, three different jobs: المعلم does the seeing (rafʿ), طالبًا receives the seeing (naṣb), and الفصل is merely located by a preposition (jarr) — this is the whole scope of إعراب in miniature.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the seeing.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'طالبًا is what/who is seen.' },
      { headPosition: 4, dependentPosition: 5, relation: 'preposition_object', explanation: 'الفصل is majrūr, governed by في.' },
    ],
  },
  {
    code: 'case-12-three-cases-coffee',
    textVocalized: 'شَرِبَ الرَّجُلُ الْقَهْوَةَ فِي الصَّبَاحِ',
    textUnvocalized: 'شرب الرجل القهوة في الصباح',
    transliteration: 'shariba r-rajulu l-qahwata fī ṣ-ṣabāḥi',
    translationEnglish: 'The man drank the coffee in the morning.',
    difficulty: 3,
    notes: 'A second three-case-in-one-sentence example with entirely different vocabulary from case-11, so the pattern generalizes rather than being tied to one memorized sentence.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'شَرِبَ', surfaceUnvocalized: 'شرب', lemma: 'شرب', rootRadicals: 'ش ر ب', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl', marker: 'fatḥah', markerType: 'visible', translation: 'drank',
        explanation: 'شرب is a plain, transitive Form I verb.',
      },
      {
        position: 2, surfaceVocalized: 'الرَّجُلُ', surfaceUnvocalized: 'الرجل', lemma: 'رجل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the man',
        explanation: 'الرجل performs the drinking, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الْقَهْوَةَ', surfaceUnvocalized: 'القهوة', lemma: 'قهوة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the coffee',
        explanation: 'Definite direct objects take a plain fatḥah with no tanwīn, unlike the indefinite طالبًا in case-11 — تنوين only appears on indefinite nouns.',
      },
      {
        position: 4, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'ḥarf jarr (preposition)',
        marker: 'built (مبني)', markerType: 'positional', translation: 'in',
        explanation: 'في governs الصباح into the genitive.',
      },
      {
        position: 5, surfaceVocalized: 'الصَّبَاحِ', surfaceUnvocalized: 'الصباح', lemma: 'صباح', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr of في', marker: 'kasrah (ـِ)', markerType: 'visible',
        translation: 'the morning',
        explanation: 'الصباح is genitive purely because في governs it.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الرجل performs the drinking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'القهوة is what is drunk.' },
      { headPosition: 4, dependentPosition: 5, relation: 'preposition_object', explanation: 'الصباح is majrūr, governed by في.' },
    ],
  },
  {
    code: 'case-13-estimated-marker-fatan',
    textVocalized: 'رَأَيْتُ فَتًى',
    textUnvocalized: 'رأيت فتى',
    transliteration: 'raʾaytu fatan',
    translationEnglish: 'I saw a young man.',
    difficulty: 3,
    notes: 'فتى ends in ألف مقصورة (a fixed, unchangeable long-ā-like letter) — its case is estimated (مقدّرة) rather than shown by any visible vowel, in every one of the three cases, not only when built like a demonstrative.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', suffix: 'تُ', partOfSpeech: 'verb', person: 'first',
        number: 'singular', role: 'fiʿl, with its own attached subject pronoun', translation: 'I saw',
        explanation: 'The attached تُ is the first-person subject pronoun fused onto the perfect stem.',
      },
      {
        position: 2, surfaceVocalized: 'فَتًى', surfaceUnvocalized: 'فتى', lemma: 'فتى', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'estimated fatḥah (the ألف مقصورة never changes shape)',
        markerType: 'estimated', translation: 'a young man',
        explanation: 'Unlike a demonstrative, فتى is an ordinary noun that fully participates in إعراب — it is genuinely accusative here — but its final ألف مقصورة is a fixed letter that cannot carry a short vowel, so the accusative marker is estimated rather than heard. The same estimation happens in the nominative (فتًى) and genitive (فتًى) — all three cases look identical on the page.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'فتًى is what is seen, even though its case ending is never actually pronounced.' },
    ],
  },
  {
    code: 'case-14-diptote-proper-noun',
    textVocalized: 'سَلَّمْتُ عَلَى أَحْمَدَ',
    textUnvocalized: 'سلمت على أحمد',
    transliteration: 'sallamtu ʿalā aḥmada',
    translationEnglish: 'I greeted Ahmad.',
    difficulty: 3,
    notes: 'A second diptote example beyond a broken plural (case-08): أحمد is diptote because, as a proper name, it happens to share the pattern أَفْعَل with the comparative/elative — one of the recognized diptote-triggering categories for names.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'سَلَّمْتُ', surfaceUnvocalized: 'سلمت', lemma: 'سلّم', rootRadicals: 'س ل م', suffix: 'تُ', partOfSpeech: 'verb',
        person: 'first', number: 'singular', role: 'fiʿl (Form II — سَلَّمَ عَلَى, "to greet"), with its own attached subject pronoun',
        translation: 'I greeted',
        explanation: 'سلّم is Form II (فَعَّلَ) of س ل م, idiomatically paired with the preposition على to mean "to greet."',
      },
      {
        position: 2, surfaceVocalized: 'عَلَى', surfaceUnvocalized: 'على', lemma: 'على', partOfSpeech: 'particle', role: 'ḥarf jarr (preposition, required by سلّم على)',
        marker: 'built (مبني)', markerType: 'positional', translation: 'upon/to',
        explanation: 'على governs أحمد into the genitive, here as part of the fixed idiom سلّم على.',
      },
      {
        position: 3, surfaceVocalized: 'أَحْمَدَ', surfaceUnvocalized: 'أحمد', lemma: 'أحمد', patternLabel: 'Elative pattern — أَفْعَل', partOfSpeech: 'proper noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr of على (diptote — ممنوع من الصرف)',
        marker: 'fatḥah, no tanwīn (diptote genitive marker)', markerType: 'secondary', translation: 'Ahmad',
        explanation: 'A proper name built on the أَفْعَل pattern is one of the standard diptote triggers — أحمد takes فتحة instead of كسرة in the genitive, and could never take تنوين even though it is definite by being a name.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'أحمد is majrūr, governed by على, but shows فتحة instead of كسرة because it is a diptote.' },
    ],
  },
  {
    code: 'case-15-sound-masc-plural-marker',
    textVocalized: 'نَجَحَ الْمُهَنْدِسُونَ',
    textUnvocalized: 'نجح المهندسون',
    transliteration: 'najaḥa l-muhandisūna',
    translationEnglish: 'The engineers succeeded.',
    difficulty: 2,
    notes: 'A clean example of the secondary marker type on its own: the sound masculine plural marks nominative with the letter و itself, not a vowel.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'نَجَحَ', surfaceUnvocalized: 'نجح', lemma: 'نجح', rootRadicals: 'ن ج ح', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl', marker: 'fatḥah', markerType: 'visible', translation: 'succeeded',
        explanation: 'نجح is a plain intransitive Form I verb.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُهَنْدِسُونَ', surfaceUnvocalized: 'المهندسون', lemma: 'مهندس', rootRadicals: 'ه ن د س', prefix: 'ال', suffix: 'ونَ',
        partOfSpeech: 'noun', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'وَاو + نَ (sound masculine plural nominative marker)', markerType: 'secondary', translation: 'the engineers',
        explanation: 'المهندسون marks its nominative case with the letter و itself rather than a vowel — in the accusative/genitive it would become المهندسينَ, swapping و for ي, exactly the same secondary-marker mechanism as the dual\'s ا/ي.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المهندسون performs the succeeding.' },
    ],
  },
];
