import type { SentenceSeed } from '../sentenceTypes';

export const caseSentences: SentenceSeed[] = [
  {
    code: 'case-01-nominative-triplet',
    textVocalized: 'حَضَرَ الطَّالِبُ',
    textUnvocalized: 'حضر الطالب',
    transliteration: 'ḥaḍara ṭ-ṭālibu',
    translationEnglish: 'The student was present.',
    difficulty: 1,
    notes: 'First of a three-sentence set using the same noun, الطالب, across all three cases (see case-02, case-03).',
    tokens: [
      { position: 1, surfaceVocalized: 'حَضَرَ', surfaceUnvocalized: 'حضر', lemma: 'حضر', rootRadicals: 'ح ض ر', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'was present', explanation: 'Intransitive Form I verb.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Nominative: home case of the فاعل.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the being-present.' }],
  },
  {
    code: 'case-02-accusative-triplet',
    textVocalized: 'رَأَيْتُ الطَّالِبَ',
    textUnvocalized: 'رأيت الطالب',
    transliteration: "raʾaytu ṭ-ṭāliba",
    translationEnglish: 'I saw the student.',
    difficulty: 2,
    notes: 'Second of the triplet: same noun, now مفعول به, accusative. Also introduces the first-person perfect suffix ـتُ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', stem: 'رأي', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb, with its own attached subject pronoun', translation: 'I saw', explanation: 'ـتُ is the attached first-person-singular subject pronoun fused onto the perfect stem — the whole word رَأَيْتُ is itself a complete little sentence, "I saw."' },
      { position: 2, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student', explanation: 'Same noun as case-01, now accusative because it is the object, not the subject: the ending changed, not the word\'s identity.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الطالب is what is seen.' }],
  },
  {
    code: 'case-03-genitive-triplet',
    textVocalized: 'مَرَرْتُ بِالطَّالِبِ',
    textUnvocalized: 'مررت بالطالب',
    transliteration: 'marartu bi-ṭ-ṭālibi',
    translationEnglish: 'I passed by the student.',
    difficulty: 2,
    notes: 'Third of the triplet: same noun, now genitive after the preposition بِ ("by/with").',
    tokens: [
      { position: 1, surfaceVocalized: 'مَرَرْتُ', surfaceUnvocalized: 'مررت', lemma: 'مر', stem: 'مرر', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I passed', explanation: 'A doubled root (م ر ر) with the attached first-person suffix.' },
      { position: 2, surfaceVocalized: 'بِالطَّالِبِ', surfaceUnvocalized: 'بالطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'بال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the student', explanation: 'The same noun a third time — now genitive purely because بِ governs it. Across all three sentences, الطالب never changed meaning; only its grammatical role, and with it, its ending, changed.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'preposition_object', explanation: 'بِ governs الطالب.' }],
  },
  {
    code: 'case-04-dual-predicate',
    textVocalized: 'الطَّالِبَانِ مُجْتَهِدَانِ',
    textUnvocalized: 'الطالبان مجتهدان',
    transliteration: 'aṭ-ṭālibāni mujtahidāni',
    translationEnglish: 'The two students are diligent.',
    difficulty: 2,
    notes: 'Unlike a fronted verb\'s agreement, a khabar that is a single adjective-like word DOES fully agree in number: both mubtada and khabar are dual here.',
    tokens: [
      { position: 1, surfaceVocalized: 'الطَّالِبَانِ', surfaceUnvocalized: 'الطالبان', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ان', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ـَانِ', markerType: 'secondary', translation: 'the two students', explanation: 'Dual nominative suffix.' },
      { position: 2, surfaceVocalized: 'مُجْتَهِدَانِ', surfaceUnvocalized: 'مجتهدان', lemma: 'مجتهد', suffix: 'ان', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـَانِ', markerType: 'secondary', translation: 'diligent (dual)', explanation: 'The khabar copies the mubtada\'s number here because it is a single descriptive word, not a following verb — the "verb stays singular" rule only applies to actual verbs.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مجتهدان is predicated of الطالبان and matches its dual number.' }],
  },
  {
    code: 'case-05-dual-accusative',
    textVocalized: 'رَأَيْتُ الطَّالِبَيْنِ',
    textUnvocalized: 'رأيت الطالبين',
    transliteration: 'raʾaytu ṭ-ṭālibayni',
    translationEnglish: 'I saw the two students.',
    difficulty: 2,
    notes: 'The dual has only one non-nominative suffix, covering both accusative and genitive: ـَيْنِ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I saw', explanation: 'Same verb as case-02.' },
      { position: 2, surfaceVocalized: 'الطَّالِبَيْنِ', surfaceUnvocalized: 'الطالبين', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ين', partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'ـَيْنِ (dual accusative/genitive)', markerType: 'secondary', translation: 'the two students', explanation: 'Unlike the singular (which distinguishes fatḥah from kasrah), the dual collapses accusative and genitive into one shared suffix.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الطالبين is what is seen.' }],
  },
  {
    code: 'case-06-sound-plural-predicate',
    textVocalized: 'الْمُعَلِّمُونَ حَاضِرُونَ',
    textUnvocalized: 'المعلمون حاضرون',
    transliteration: 'al-muʿallimūna ḥāḍirūna',
    translationEnglish: 'The teachers are present.',
    difficulty: 2,
    tokens: [
      { position: 1, surfaceVocalized: 'الْمُعَلِّمُونَ', surfaceUnvocalized: 'المعلمون', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ون', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ـُونَ (sound masculine plural nominative)', markerType: 'secondary', translation: 'the teachers', explanation: 'Sound masculine plural: a real "regular" plural, formed by a predictable suffix rather than an internal change.' },
      { position: 2, surfaceVocalized: 'حَاضِرُونَ', surfaceUnvocalized: 'حاضرون', lemma: 'حاضر', rootRadicals: 'ح ض ر', patternLabel: 'Active participle (Form I) — فَاعِل', suffix: 'ون', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـُونَ', markerType: 'secondary', translation: 'present (plural)', explanation: 'Agrees fully in number since it is a single-word khabar, not a following verb.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'حاضرون is predicated of المعلمون.' }],
  },
  {
    code: 'case-07-sound-plural-accusative',
    textVocalized: 'رَأَيْتُ الْمُعَلِّمِينَ',
    textUnvocalized: 'رأيت المعلمين',
    transliteration: 'raʾaytu l-muʿallimīna',
    translationEnglish: 'I saw the teachers.',
    difficulty: 2,
    notes: 'Sound masculine plural, like the dual, collapses accusative and genitive into one suffix: ـِينَ.',
    tokens: [
      { position: 1, surfaceVocalized: 'رَأَيْتُ', surfaceUnvocalized: 'رأيت', lemma: 'رأى', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I saw', explanation: 'Same verb as before.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمِينَ', surfaceUnvocalized: 'المعلمين', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ين', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'ـِينَ (sound masculine plural accusative/genitive)', markerType: 'secondary', translation: 'the teachers', explanation: 'Contrast with case-06\'s ـُونَ: the same word takes ـِينَ once it is no longer nominative.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'المعلمين is what is seen.' }],
  },
  {
    code: 'case-08-diptote-genitive',
    textVocalized: 'سَافَرْتُ إِلَى مِصْرَ',
    textUnvocalized: 'سافرت إلى مصر',
    transliteration: 'sāfartu ilā miṣra',
    translationEnglish: 'I traveled to Egypt.',
    difficulty: 3,
    notes: 'مِصْرَ is a diptote (ممنوع من الصرف) — a feminine proper name with no ة. Genitive is shown by فتحة instead of the expected كسرة, and there is no تنوين.',
    tokens: [
      { position: 1, surfaceVocalized: 'سَافَرْتُ', surfaceUnvocalized: 'سافرت', lemma: 'سافر', stem: 'سافر', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb', translation: 'I traveled', explanation: 'Form III verb سَافَرَ with the first-person suffix.' },
      { position: 2, surfaceVocalized: 'إِلَى', surfaceUnvocalized: 'إلى', lemma: 'إلى', partOfSpeech: 'particle', role: 'preposition (direction)', translation: 'to', explanation: 'Governs مصر into the genitive.' },
      { position: 3, surfaceVocalized: 'مِصْرَ', surfaceUnvocalized: 'مصر', lemma: 'مصر', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'fatḥah, no tanwīn (diptote genitive)', markerType: 'secondary', translation: 'Egypt', explanation: 'Because مصر is a diptote (a feminine proper name without ة), it borrows the accusative\'s فتحة to mark the genitive instead of the usual كسرة, and never takes تنوين at all — a closed, learnable exception class, not a random irregularity.', traditionalExplanation: 'اسم مجرور وعلامة جره الفتحة نيابة عن الكسرة لأنه ممنوع من الصرف.' },
    ],
    dependencies: [{ headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'إلى governs مصر, whose genitive shows as a diptote fatḥah.' }],
  },
];
