import type { SentenceSeed } from '../sentenceTypes';

export const morphologySentences: SentenceSeed[] = [
  {
    code: 'morph-01-form2-causative',
    textVocalized: 'عَلَّمَ الْمُعَلِّمُ الطُّلَّابَ النَّحْوَ',
    textUnvocalized: 'علم المعلم الطلاب النحو',
    transliteration: 'ʿallama l-muʿallimu ṭ-ṭullāba n-naḥwa',
    translationEnglish: 'The teacher taught the students grammar.',
    difficulty: 3,
    notes: 'عَلَّمَ (Form II of ع ل م) is causative — "caused to know" — and, like a small class of Form II verbs, takes two objects.',
    tokens: [
      { position: 1, surfaceVocalized: 'عَلَّمَ', surfaceUnvocalized: 'علم', lemma: 'علم', rootRadicals: 'ع ل م', patternLabel: 'Form II — فَعَّلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'taught', explanation: 'Form II of علم ("knew") — the doubled middle radical marks the causative shift to "taught," i.e. "caused to know."' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'Itself a Form II active-participle-derived noun, "one who causes learning."' },
      { position: 3, surfaceVocalized: 'الطُّلَّابَ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'accusative', role: 'first mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the students', explanation: 'First object — the ones taught.' },
      { position: 4, surfaceVocalized: 'النَّحْوَ', surfaceUnvocalized: 'النحو', lemma: 'نحو', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'second mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'grammar', explanation: 'Second object — the subject matter taught.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the teaching.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطلاب are taught.' },
      { headPosition: 1, dependentPosition: 4, relation: 'verb_object', explanation: 'النحو is what is taught.' },
    ],
  },
  {
    code: 'morph-02-form5-reflexive',
    textVocalized: 'تَعَلَّمَ الطَّالِبُ النَّحْوَ',
    textUnvocalized: 'تعلم الطالب النحو',
    transliteration: "taʿallama ṭ-ṭālibu n-naḥwa",
    translationEnglish: 'The student learned grammar.',
    difficulty: 3,
    notes: 'Direct pair with morph-01: Form V تَعَلَّمَ turns Form II\'s causative "taught" into a reflexive "taught himself," i.e. "learned."',
    tokens: [
      { position: 1, surfaceVocalized: 'تَعَلَّمَ', surfaceUnvocalized: 'تعلم', lemma: 'علم', rootRadicals: 'ع ل م', patternLabel: 'Form V — تَفَعَّلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'learned', explanation: 'Form V adds a reflexive ت- prefix to Form II\'s pattern: "caused himself to know."' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'النَّحْوَ', surfaceUnvocalized: 'النحو', lemma: 'نحو', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'grammar', explanation: 'Form V here takes only one object, unlike Form II\'s two — the reflexive folds the "student" role into the subject itself.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs (and receives) the learning.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'النحو is what is learned.' },
    ],
  },
  {
    code: 'morph-03-form8-reciprocal-effort',
    textVocalized: 'اجْتَمَعَ الطُّلَّابُ فِي الْفَصْلِ',
    textUnvocalized: 'اجتمع الطلاب في الفصل',
    transliteration: 'ijtamaʿa ṭ-ṭullābu fī l-faṣli',
    translationEnglish: 'The students gathered in the classroom.',
    difficulty: 3,
    tokens: [
      { position: 1, surfaceVocalized: 'اجْتَمَعَ', surfaceUnvocalized: 'اجتمع', lemma: 'جمع', rootRadicals: 'ج م ع', patternLabel: 'Form VIII — افْتَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'gathered (intransitive)', explanation: 'Form VIII of جمع ("gathered [something]") gives a reflexive/mutual sense: "gathered themselves" → "met, congregated."' },
      { position: 2, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students', explanation: 'Subject, still grammatically singular-agreeing verb despite plural fāʿil.' },
      { position: 3, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'preposition', translation: 'in', explanation: 'Governs الفصل.' },
      { position: 4, surfaceVocalized: 'الْفَصْلِ', surfaceUnvocalized: 'الفصل', lemma: 'فصل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the classroom', explanation: 'Genitive after في.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطلاب perform the gathering.' },
      { headPosition: 3, dependentPosition: 4, relation: 'preposition_object', explanation: 'في governs الفصل.' },
    ],
  },
  {
    code: 'morph-04-form7-vs-form1-transitivity',
    textVocalized: 'كَسَرَ الْوَلَدُ الْبَابَ فَانْكَسَرَ',
    textUnvocalized: 'كسر الولد الباب فانكسر',
    transliteration: 'kasara l-waladu l-bāba fa-nkasara',
    translationEnglish: 'The boy broke the door, so it broke.',
    difficulty: 4,
    notes: 'A single sentence pairing Form I (transitive, needs an agent and a patient) with Form VII (intransitive, describes the patient\'s resulting state alone) from the same root.',
    tokens: [
      { position: 1, surfaceVocalized: 'كَسَرَ', surfaceUnvocalized: 'كسر', lemma: 'كسر', rootRadicals: 'ك س ر', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'broke (something)', explanation: 'Transitive Form I: requires both an agent and a patient.' },
      { position: 2, surfaceVocalized: 'الْوَلَدُ', surfaceUnvocalized: 'الولد', lemma: 'ولد', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the boy', explanation: 'Agent of the breaking.' },
      { position: 3, surfaceVocalized: 'الْبَابَ', surfaceUnvocalized: 'الباب', lemma: 'باب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the door', explanation: 'Patient of the first verb.' },
      { position: 4, surfaceVocalized: 'فَانْكَسَرَ', surfaceUnvocalized: 'فانكسر', lemma: 'كسر', rootRadicals: 'ك س ر', patternLabel: 'Form VII — انْفَعَلَ', prefix: 'ف', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb, with an implied subject pronoun referring back to الباب', translation: 'so it broke', explanation: 'Form VII is intransitive: it needs no separate patient because it describes الباب undergoing the breaking, referred to by a hidden "it" (هو) built into the verb.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الولد performs the first breaking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الباب is broken by الولد.' },
      { headPosition: 4, dependentPosition: 3, relation: 'verb_subject', explanation: 'The hidden pronoun in انكسر refers back to الباب, which is now the one undergoing the action.' },
    ],
  },
  {
    code: 'morph-05-hollow-perfect-contracted',
    textVocalized: 'قَالَ الطَّالِبُ الْحَقَّ',
    textUnvocalized: 'قال الطالب الحق',
    transliteration: 'qāla ṭ-ṭālibu l-ḥaqqa',
    translationEnglish: 'The student spoke the truth.',
    difficulty: 3,
    notes: 'Hollow verb, third person: the middle radical و contracts fully into the long vowel ا.',
    tokens: [
      { position: 1, surfaceVocalized: 'قَالَ', surfaceUnvocalized: 'قال', lemma: 'قال', rootRadicals: 'ق و ل', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'said', explanation: 'The root\'s middle radical و is fully absorbed into the long vowel ا in third-person forms — compare with case-05\'s قُلْتُ (see morph-06), where it resurfaces.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْحَقَّ', surfaceUnvocalized: 'الحق', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the truth', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the speaking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الحق is what is spoken.' },
    ],
  },
  {
    code: 'morph-06-hollow-first-person-resurfaces',
    textVocalized: 'قُلْتُ الْحَقَّ',
    textUnvocalized: 'قلت الحق',
    transliteration: 'qultu l-ḥaqqa',
    translationEnglish: 'I spoke the truth.',
    difficulty: 3,
    notes: 'The direct pair to morph-05: once a consonant-initial suffix (ـتُ) follows, قال\'s middle radical resurfaces as a short vowel rather than staying a long ا.',
    tokens: [
      { position: 1, surfaceVocalized: 'قُلْتُ', surfaceUnvocalized: 'قلت', lemma: 'قال', rootRadicals: 'ق و ل', stem: 'قل', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb, with attached subject pronoun', translation: 'I said', explanation: 'Before the consonant-initial suffix ـتُ, the contracted long vowel of قَالَ shortens back to a bare vowel reflecting the underlying و — this is the predictable half of hollow-verb behavior, not a second irregular verb to memorize separately.' },
      { position: 2, surfaceVocalized: 'الْحَقَّ', surfaceUnvocalized: 'الحق', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the truth', explanation: 'Same object as morph-05.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الحق is what is said.' }],
  },
  {
    code: 'morph-07-defective-ya',
    textVocalized: 'نَسِيَ الطَّالِبُ الدَّرْسَ',
    textUnvocalized: 'نسي الطالب الدرس',
    transliteration: 'nasiya ṭ-ṭālibu d-darsa',
    translationEnglish: 'The student forgot the lesson.',
    difficulty: 3,
    notes: 'Defective verb: final radical ي surfaces as a short-vowel-plus-glide in the third-person-masculine perfect.',
    tokens: [
      { position: 1, surfaceVocalized: 'نَسِيَ', surfaceUnvocalized: 'نسي', lemma: 'نسي', rootRadicals: 'ن س ي', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'forgot', explanation: 'Final radical ي, visible here as the final vowel sequence -iya.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', rootRadicals: 'د ر س', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the forgetting.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is what is forgotten.' },
    ],
  },
  {
    code: 'morph-08-defective-waw',
    textVocalized: 'دَعَا الْمُعَلِّمُ الطَّالِبَ',
    textUnvocalized: 'دعا المعلم الطالب',
    transliteration: 'daʿā l-muʿallimu ṭ-ṭāliba',
    translationEnglish: 'The teacher called the student.',
    difficulty: 3,
    notes: 'Defective verb with final radical و, which surfaces as a long ā in the third-person-masculine perfect — visually identical to morph-05\'s hollow قَالَ, but for a structurally different reason (final vs. middle weak radical).',
    tokens: [
      { position: 1, surfaceVocalized: 'دَعَا', surfaceUnvocalized: 'دعا', lemma: 'دعا', rootRadicals: 'د ع و', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'called; invited', explanation: 'Final radical و surfaces here as ā — do not confuse this defective pattern with a hollow verb\'s contraction; they arise from weakness in different root positions.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the calling.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطالب is called.' },
    ],
  },
  {
    code: 'morph-09-hamzated-cognate-object',
    textVocalized: 'سَأَلَ الطَّالِبُ الْمُعَلِّمَ سُؤَالًا',
    textUnvocalized: 'سأل الطالب المعلم سؤالا',
    transliteration: 'saʾala ṭ-ṭālibu l-muʿallima suʾālan',
    translationEnglish: 'The student asked the teacher a question.',
    difficulty: 4,
    notes: 'سأل is hamzated (middle radical). سُؤَالًا here is a مصدر of the same root doubling as a second object, previewing the cognate-accusative construction (المفعول المطلق) covered in Domain C.',
    tokens: [
      { position: 1, surfaceVocalized: 'سَأَلَ', surfaceUnvocalized: 'سأل', lemma: 'سأل', rootRadicals: 'س أ ل', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'asked', explanation: 'Hamzated: the همزة sits as the middle radical.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْمُعَلِّمَ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the teacher', explanation: 'The person asked — direct object of سأل.' },
      { position: 4, surfaceVocalized: 'سُؤَالًا', surfaceUnvocalized: 'سؤالا', lemma: 'سؤال', rootRadicals: 'س أ ل', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'cognate object (مفعول مطلق-like use of the verbal noun)', marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a question', explanation: 'سؤالًا is the مصدر of the very same verb, used here as a second accusative element naming the action itself — a preview of the cognate accusative construction, not an ordinary second مفعول به.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the asking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'المعلم is asked.' },
      { headPosition: 1, dependentPosition: 4, relation: 'verb_object', explanation: 'سؤالًا names the act of asking itself.' },
    ],
  },
  {
    code: 'morph-10-assimilated',
    textVocalized: 'وَجَدَ الطَّالِبُ الْكِتَابَ',
    textUnvocalized: 'وجد الطالب الكتاب',
    transliteration: 'wajada ṭ-ṭālibu l-kitāba',
    translationEnglish: 'The student found the book.',
    difficulty: 3,
    notes: 'Assimilated verb: the weak first radical و is fully intact in the perfect, but drops in the imperfect (يَجِدُ, not يَوْجِدُ) — a change this sentence does not show directly, since only the perfect is used here.',
    tokens: [
      { position: 1, surfaceVocalized: 'وَجَدَ', surfaceUnvocalized: 'وجد', lemma: 'وجد', rootRadicals: 'و ج د', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'found', explanation: 'Perfect tense: the first radical و is unaffected here — assimilation only strikes in the imperfect.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْكِتَابَ', surfaceUnvocalized: 'الكتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the book', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the finding.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الكتاب is found.' },
    ],
  },
  {
    code: 'morph-11-verbal-noun-reading',
    textVocalized: 'الْقِرَاءَةُ مُفِيدَةٌ',
    textUnvocalized: 'القراءة مفيدة',
    transliteration: 'al-qirāʾatu mufīdatun',
    translationEnglish: 'Reading is beneficial.',
    difficulty: 2,
    notes: 'القراءة is a مصدر (verbal noun) — a noun naming the action of قرأ itself, "the act of reading" — used here as an ordinary noun functioning as mubtada, exactly like any other noun.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْقِرَاءَةُ', surfaceUnvocalized: 'القراءة', lemma: 'قراءة', rootRadicals: 'ق ر أ',
        patternLabel: 'Verbal noun (Form I) — فِعَالَة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine', number: 'singular',
        definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'reading',
        explanation: 'القراءة is the مصدر (verbal noun) of قرأ, naming the action itself rather than describing an agent or a result — grammatically it behaves exactly like any other noun once formed.',
      },
      {
        position: 2, surfaceVocalized: 'مُفِيدَةٌ', surfaceUnvocalized: 'مفيدة', lemma: 'مفيد', rootRadicals: 'ف ي د',
        patternLabel: 'Active participle (Form IV) — مُفْعِل', suffix: 'ة', partOfSpeech: 'adjective', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'beneficial', explanation: 'مفيد is the Form IV active participle of أفاد, "to benefit" — used adjectivally, with the feminine ة agreeing with القراءة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مفيدة is predicated of القراءة.' },
    ],
  },
  {
    code: 'morph-12-passive-participle-letter',
    textVocalized: 'الرِّسَالَةُ مَكْتُوبَةٌ بِخَطٍّ جَمِيلٍ',
    textUnvocalized: 'الرسالة مكتوبة بخط جميل',
    transliteration: 'ar-risālatu maktūbatun bi-khaṭṭin jamīlin',
    translationEnglish: 'The letter is written in beautiful handwriting.',
    difficulty: 3,
    notes: 'مَكْتُوبَةٌ is the اسم مفعول (passive participle) of كتب, used as an ordinary predicate adjective. بِخَطٍّ fuses the inseparable preposition بِ onto the noun خطّ, exactly as بِ fuses onto its noun in case-03.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الرِّسَالَةُ', surfaceUnvocalized: 'الرسالة', lemma: 'رسالة', rootRadicals: 'ر س ل', prefix: 'ال',
        suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the letter', explanation: 'Definite noun, mubtada.',
      },
      {
        position: 2, surfaceVocalized: 'مَكْتُوبَةٌ', surfaceUnvocalized: 'مكتوبة', lemma: 'مكتوب', rootRadicals: 'ك ت ب',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', suffix: 'ة', partOfSpeech: 'adjective', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'written',
        explanation: 'مكتوبة is the اسم المفعول (passive participle) of كتب — "having been written" — used here as an ordinary predicate adjective, feminine to agree with الرسالة.',
      },
      {
        position: 3, surfaceVocalized: 'بِخَطٍّ', surfaceUnvocalized: 'بخط', lemma: 'خط', rootRadicals: 'خ ط ط', prefix: 'ب',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'genitive',
        role: 'preposition بِ + majrūr (object of the preposition)', marker: 'kasrah + tanwīn (ـٍ)', markerType: 'visible',
        translation: 'in [a certain] handwriting',
        explanation: 'بِ here means "with / by means of," governing خطّ (a doubled root, خ ط ط, "line" → "handwriting") into the genitive — fused onto its noun exactly as بِ does in case-03\'s بِالطَّالِبِ.',
      },
      {
        position: 4, surfaceVocalized: 'جَمِيلٍ', surfaceUnvocalized: 'جميل', lemma: 'جميل', partOfSpeech: 'adjective', gender: 'masculine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'genitive', role: 'naʿt of خطّ', marker: 'kasrah + tanwīn (ـٍ)',
        markerType: 'visible', translation: 'beautiful', explanation: 'Agrees with خطّ in all four features, including its genitive case.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مكتوبة is predicated of الرسالة.' },
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'مكتوبة is described as happening بِخَطٍّ — بِ governs خطّ into the genitive.' },
      { headPosition: 3, dependentPosition: 4, relation: 'noun_adjective', explanation: 'جميل describes خطّ and matches its case (genitive) and other features.' },
    ],
  },
];
