import type { SentenceSeed } from '../sentenceTypes';

export const morphologySentences: SentenceSeed[] = [
  {
    code: 'morph-01-form2-causative',
    textVocalized: 'عَلَّمَ الْمُعَلِّمُ الطُّلَّابَ النَّحْوَ',
    textUnvocalized: 'علم المعلم الطلاب النحو',
    transliteration: 'ʿallama l-muʿallimu ṭ-ṭullāba n-naḥwa',
    translationEnglish: 'The teacher taught the students grammar.',
    difficulty: 3,
    notes: 'عَلَّمَ (Form II of ع ل م) is causative — "caused to know" — and, like a small class of Form II verbs, takes two objects.',
    tokens: [
      { position: 1, surfaceVocalized: 'عَلَّمَ', surfaceUnvocalized: 'علم', lemma: 'علم', rootRadicals: 'ع ل م', patternLabel: 'Form II — فَعَّلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'taught', explanation: 'Form II of علم ("knew") — the doubled middle radical marks the causative shift to "taught," i.e. "caused to know."' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'Itself a Form II active-participle-derived noun, "one who causes learning."' },
      { position: 3, surfaceVocalized: 'الطُّلَّابَ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'accusative', role: 'first mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the students', explanation: 'First object — the ones taught.' },
      { position: 4, surfaceVocalized: 'النَّحْوَ', surfaceUnvocalized: 'النحو', lemma: 'نحو', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'second mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'grammar', explanation: 'Second object — the subject matter taught.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the teaching.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطلاب are taught.' },
      { headPosition: 1, dependentPosition: 4, relation: 'verb_object', explanation: 'النحو is what is taught.' },
    ],
  },
  {
    code: 'morph-02-form5-reflexive',
    textVocalized: 'تَعَلَّمَ الطَّالِبُ النَّحْوَ',
    textUnvocalized: 'تعلم الطالب النحو',
    transliteration: "taʿallama ṭ-ṭālibu n-naḥwa",
    translationEnglish: 'The student learned grammar.',
    difficulty: 3,
    notes: 'Direct pair with morph-01: Form V تَعَلَّمَ turns Form II\'s causative "taught" into a reflexive "taught himself," i.e. "learned."',
    tokens: [
      { position: 1, surfaceVocalized: 'تَعَلَّمَ', surfaceUnvocalized: 'تعلم', lemma: 'علم', rootRadicals: 'ع ل م', patternLabel: 'Form V — تَفَعَّلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'learned', explanation: 'Form V adds a reflexive ت- prefix to Form II\'s pattern: "caused himself to know."' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'النَّحْوَ', surfaceUnvocalized: 'النحو', lemma: 'نحو', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'grammar', explanation: 'Form V here takes only one object, unlike Form II\'s two — the reflexive folds the "student" role into the subject itself.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs (and receives) the learning.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'النحو is what is learned.' },
    ],
  },
  {
    code: 'morph-03-form8-reciprocal-effort',
    textVocalized: 'اجْتَمَعَ الطُّلَّابُ فِي الْفَصْلِ',
    textUnvocalized: 'اجتمع الطلاب في الفصل',
    transliteration: 'ijtamaʿa ṭ-ṭullābu fī l-faṣli',
    translationEnglish: 'The students gathered in the classroom.',
    difficulty: 3,
    tokens: [
      { position: 1, surfaceVocalized: 'اجْتَمَعَ', surfaceUnvocalized: 'اجتمع', lemma: 'جمع', rootRadicals: 'ج م ع', patternLabel: 'Form VIII — افْتَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'gathered (intransitive)', explanation: 'Form VIII of جمع ("gathered [something]") gives a reflexive/mutual sense: "gathered themselves" → "met, congregated."' },
      { position: 2, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students', explanation: 'Subject, still grammatically singular-agreeing verb despite plural fāʿil.' },
      { position: 3, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'preposition', translation: 'in', explanation: 'Governs الفصل.' },
      { position: 4, surfaceVocalized: 'الْفَصْلِ', surfaceUnvocalized: 'الفصل', lemma: 'فصل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the classroom', explanation: 'Genitive after في.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطلاب perform the gathering.' },
      { headPosition: 3, dependentPosition: 4, relation: 'preposition_object', explanation: 'في governs الفصل.' },
    ],
  },
  {
    code: 'morph-04-form7-vs-form1-transitivity',
    textVocalized: 'كَسَرَ الْوَلَدُ الْبَابَ فَانْكَسَرَ',
    textUnvocalized: 'كسر الولد الباب فانكسر',
    transliteration: 'kasara l-waladu l-bāba fa-nkasara',
    translationEnglish: 'The boy broke the door, so it broke.',
    difficulty: 4,
    notes: 'A single sentence pairing Form I (transitive, needs an agent and a patient) with Form VII (intransitive, describes the patient\'s resulting state alone) from the same root.',
    tokens: [
      { position: 1, surfaceVocalized: 'كَسَرَ', surfaceUnvocalized: 'كسر', lemma: 'كسر', rootRadicals: 'ك س ر', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'broke (something)', explanation: 'Transitive Form I: requires both an agent and a patient.' },
      { position: 2, surfaceVocalized: 'الْوَلَدُ', surfaceUnvocalized: 'الولد', lemma: 'ولد', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the boy', explanation: 'Agent of the breaking.' },
      { position: 3, surfaceVocalized: 'الْبَابَ', surfaceUnvocalized: 'الباب', lemma: 'باب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the door', explanation: 'Patient of the first verb.' },
      { position: 4, surfaceVocalized: 'فَانْكَسَرَ', surfaceUnvocalized: 'فانكسر', lemma: 'كسر', rootRadicals: 'ك س ر', patternLabel: 'Form VII — انْفَعَلَ', prefix: 'ف', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb, with an implied subject pronoun referring back to الباب', translation: 'so it broke', explanation: 'Form VII is intransitive: it needs no separate patient because it describes الباب undergoing the breaking, referred to by a hidden "it" (هو) built into the verb.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الولد performs the first breaking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الباب is broken by الولد.' },
      { headPosition: 4, dependentPosition: 3, relation: 'verb_subject', explanation: 'The hidden pronoun in انكسر refers back to الباب, which is now the one undergoing the action.' },
    ],
  },
  {
    code: 'morph-05-hollow-perfect-contracted',
    textVocalized: 'قَالَ الطَّالِبُ الْحَقَّ',
    textUnvocalized: 'قال الطالب الحق',
    transliteration: 'qāla ṭ-ṭālibu l-ḥaqqa',
    translationEnglish: 'The student spoke the truth.',
    difficulty: 3,
    notes: 'Hollow verb, third person: the middle radical و contracts fully into the long vowel ا.',
    tokens: [
      { position: 1, surfaceVocalized: 'قَالَ', surfaceUnvocalized: 'قال', lemma: 'قال', rootRadicals: 'ق و ل', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'said', explanation: 'The root\'s middle radical و is fully absorbed into the long vowel ا in third-person forms — compare with case-05\'s قُلْتُ (see morph-06), where it resurfaces.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْحَقَّ', surfaceUnvocalized: 'الحق', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the truth', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the speaking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الحق is what is spoken.' },
    ],
  },
  {
    code: 'morph-06-hollow-first-person-resurfaces',
    textVocalized: 'قُلْتُ الْحَقَّ',
    textUnvocalized: 'قلت الحق',
    transliteration: 'qultu l-ḥaqqa',
    translationEnglish: 'I spoke the truth.',
    difficulty: 3,
    notes: 'The direct pair to morph-05: once a consonant-initial suffix (ـتُ) follows, قال\'s middle radical resurfaces as a short vowel rather than staying a long ا.',
    tokens: [
      { position: 1, surfaceVocalized: 'قُلْتُ', surfaceUnvocalized: 'قلت', lemma: 'قال', rootRadicals: 'ق و ل', stem: 'قل', suffix: 'تُ', partOfSpeech: 'verb', person: 'first', number: 'singular', role: 'the verb, with attached subject pronoun', translation: 'I said', explanation: 'Before the consonant-initial suffix ـتُ, the contracted long vowel of قَالَ shortens back to a bare vowel reflecting the underlying و — this is the predictable half of hollow-verb behavior, not a second irregular verb to memorize separately.' },
      { position: 2, surfaceVocalized: 'الْحَقَّ', surfaceUnvocalized: 'الحق', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the truth', explanation: 'Same object as morph-05.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'الحق is what is said.' }],
  },
  {
    code: 'morph-07-defective-ya',
    textVocalized: 'نَسِيَ الطَّالِبُ الدَّرْسَ',
    textUnvocalized: 'نسي الطالب الدرس',
    transliteration: 'nasiya ṭ-ṭālibu d-darsa',
    translationEnglish: 'The student forgot the lesson.',
    difficulty: 3,
    notes: 'Defective verb: final radical ي surfaces as a short-vowel-plus-glide in the third-person-masculine perfect.',
    tokens: [
      { position: 1, surfaceVocalized: 'نَسِيَ', surfaceUnvocalized: 'نسي', lemma: 'نسي', rootRadicals: 'ن س ي', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'forgot', explanation: 'Final radical ي, visible here as the final vowel sequence -iya.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', rootRadicals: 'د ر س', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the forgetting.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is what is forgotten.' },
    ],
  },
  {
    code: 'morph-08-defective-waw',
    textVocalized: 'دَعَا الْمُعَلِّمُ الطَّالِبَ',
    textUnvocalized: 'دعا المعلم الطالب',
    transliteration: 'daʿā l-muʿallimu ṭ-ṭāliba',
    translationEnglish: 'The teacher called the student.',
    difficulty: 3,
    notes: 'Defective verb with final radical و, which surfaces as a long ā in the third-person-masculine perfect — visually identical to morph-05\'s hollow قَالَ, but for a structurally different reason (final vs. middle weak radical).',
    tokens: [
      { position: 1, surfaceVocalized: 'دَعَا', surfaceUnvocalized: 'دعا', lemma: 'دعا', rootRadicals: 'د ع و', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'called; invited', explanation: 'Final radical و surfaces here as ā — do not confuse this defective pattern with a hollow verb\'s contraction; they arise from weakness in different root positions.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the calling.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطالب is called.' },
    ],
  },
  {
    code: 'morph-09-hamzated-cognate-object',
    textVocalized: 'سَأَلَ الطَّالِبُ الْمُعَلِّمَ سُؤَالًا',
    textUnvocalized: 'سأل الطالب المعلم سؤالا',
    transliteration: 'saʾala ṭ-ṭālibu l-muʿallima suʾālan',
    translationEnglish: 'The student asked the teacher a question.',
    difficulty: 4,
    notes: 'سأل is hamzated (middle radical). سُؤَالًا here is a مصدر of the same root doubling as a second object, previewing the cognate-accusative construction (المفعول المطلق) covered in Domain C.',
    tokens: [
      { position: 1, surfaceVocalized: 'سَأَلَ', surfaceUnvocalized: 'سأل', lemma: 'سأل', rootRadicals: 'س أ ل', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'asked', explanation: 'Hamzated: the همزة sits as the middle radical.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْمُعَلِّمَ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the teacher', explanation: 'The person asked — direct object of سأل.' },
      { position: 4, surfaceVocalized: 'سُؤَالًا', surfaceUnvocalized: 'سؤالا', lemma: 'سؤال', rootRadicals: 'س أ ل', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'cognate object (مفعول مطلق-like use of the verbal noun)', marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a question', explanation: 'سؤالًا is the مصدر of the very same verb, used here as a second accusative element naming the action itself — a preview of the cognate accusative construction, not an ordinary second مفعول به.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the asking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'المعلم is asked.' },
      { headPosition: 1, dependentPosition: 4, relation: 'verb_object', explanation: 'سؤالًا names the act of asking itself.' },
    ],
  },
  {
    code: 'morph-10-assimilated',
    textVocalized: 'وَجَدَ الطَّالِبُ الْكِتَابَ',
    textUnvocalized: 'وجد الطالب الكتاب',
    transliteration: 'wajada ṭ-ṭālibu l-kitāba',
    translationEnglish: 'The student found the book.',
    difficulty: 3,
    notes: 'Assimilated verb: the weak first radical و is fully intact in the perfect, but drops in the imperfect (يَجِدُ, not يَوْجِدُ) — a change this sentence does not show directly, since only the perfect is used here.',
    tokens: [
      { position: 1, surfaceVocalized: 'وَجَدَ', surfaceUnvocalized: 'وجد', lemma: 'وجد', rootRadicals: 'و ج د', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'found', explanation: 'Perfect tense: the first radical و is unaffected here — assimilation only strikes in the imperfect.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الْكِتَابَ', surfaceUnvocalized: 'الكتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the book', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the finding.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الكتاب is found.' },
    ],
  },
  {
    code: 'morph-11-verbal-noun-reading',
    textVocalized: 'الْقِرَاءَةُ مُفِيدَةٌ',
    textUnvocalized: 'القراءة مفيدة',
    transliteration: 'al-qirāʾatu mufīdatun',
    translationEnglish: 'Reading is beneficial.',
    difficulty: 2,
    notes: 'القراءة is a مصدر (verbal noun) — a noun naming the action of قرأ itself, "the act of reading" — used here as an ordinary noun functioning as mubtada, exactly like any other noun.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْقِرَاءَةُ', surfaceUnvocalized: 'القراءة', lemma: 'قراءة', rootRadicals: 'ق ر أ',
        patternLabel: 'Verbal noun (Form I) — فِعَالَة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine', number: 'singular',
        definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'reading',
        explanation: 'القراءة is the مصدر (verbal noun) of قرأ, naming the action itself rather than describing an agent or a result — grammatically it behaves exactly like any other noun once formed.',
      },
      {
        position: 2, surfaceVocalized: 'مُفِيدَةٌ', surfaceUnvocalized: 'مفيدة', lemma: 'مفيد', rootRadicals: 'ف ي د',
        patternLabel: 'Active participle (Form IV) — مُفْعِل', suffix: 'ة', partOfSpeech: 'adjective', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'beneficial', explanation: 'مفيد is the Form IV active participle of أفاد, "to benefit" — used adjectivally, with the feminine ة agreeing with القراءة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مفيدة is predicated of القراءة.' },
    ],
  },
  {
    code: 'morph-12-passive-participle-letter',
    textVocalized: 'الرِّسَالَةُ مَكْتُوبَةٌ بِخَطٍّ جَمِيلٍ',
    textUnvocalized: 'الرسالة مكتوبة بخط جميل',
    transliteration: 'ar-risālatu maktūbatun bi-khaṭṭin jamīlin',
    translationEnglish: 'The letter is written in beautiful handwriting.',
    difficulty: 3,
    notes: 'مَكْتُوبَةٌ is the اسم مفعول (passive participle) of كتب, used as an ordinary predicate adjective. بِخَطٍّ fuses the inseparable preposition بِ onto the noun خطّ, exactly as بِ fuses onto its noun in case-03.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الرِّسَالَةُ', surfaceUnvocalized: 'الرسالة', lemma: 'رسالة', rootRadicals: 'ر س ل', prefix: 'ال',
        suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the letter', explanation: 'Definite noun, mubtada.',
      },
      {
        position: 2, surfaceVocalized: 'مَكْتُوبَةٌ', surfaceUnvocalized: 'مكتوبة', lemma: 'مكتوب', rootRadicals: 'ك ت ب',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', suffix: 'ة', partOfSpeech: 'adjective', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'written',
        explanation: 'مكتوبة is the اسم المفعول (passive participle) of كتب — "having been written" — used here as an ordinary predicate adjective, feminine to agree with الرسالة.',
      },
      {
        position: 3, surfaceVocalized: 'بِخَطٍّ', surfaceUnvocalized: 'بخط', lemma: 'خط', rootRadicals: 'خ ط ط', prefix: 'ب',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'genitive',
        role: 'preposition بِ + majrūr (object of the preposition)', marker: 'kasrah + tanwīn (ـٍ)', markerType: 'visible',
        translation: 'in [a certain] handwriting',
        explanation: 'بِ here means "with / by means of," governing خطّ (a doubled root, خ ط ط, "line" → "handwriting") into the genitive — fused onto its noun exactly as بِ does in case-03\'s بِالطَّالِبِ.',
      },
      {
        position: 4, surfaceVocalized: 'جَمِيلٍ', surfaceUnvocalized: 'جميل', lemma: 'جميل', partOfSpeech: 'adjective', gender: 'masculine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'genitive', role: 'naʿt of خطّ', marker: 'kasrah + tanwīn (ـٍ)',
        markerType: 'visible', translation: 'beautiful', explanation: 'Agrees with خطّ in all four features, including its genitive case.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مكتوبة is predicated of الرسالة.' },
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'مكتوبة is described as happening بِخَطٍّ — بِ governs خطّ into the genitive.' },
      { headPosition: 3, dependentPosition: 4, relation: 'noun_adjective', explanation: 'جميل describes خطّ and matches its case (genitive) and other features.' },
    ],
  },
  {
    code: 'morph-13-root-pattern-triple',
    textVocalized: 'الْكَاتِبُ يَكْتُبُ الْكِتَابَ',
    textUnvocalized: 'الكاتب يكتب الكتاب',
    transliteration: 'al-kātibu yaktubu l-kitāba',
    translationEnglish: 'The writer writes the book.',
    difficulty: 2,
    notes: 'All three words share the root ك ت ب, poured into three different patterns (فَاعِل، يَفْعُلُ، فِعَال) — a single sentence that is itself a root-and-pattern demonstration.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْكَاتِبُ', surfaceUnvocalized: 'الكاتب', lemma: 'كاتب', rootRadicals: 'ك ت ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the writer',
        explanation: 'الكاتب is the فَاعِل-pattern active participle of ك ت ب — "the one who writes," used as a noun.',
      },
      {
        position: 2, surfaceVocalized: 'يَكْتُبُ', surfaceUnvocalized: 'يكتب', lemma: 'كتب', rootRadicals: 'ك ت ب', partOfSpeech: 'verb',
        person: 'third', gender: 'masculine', number: 'singular', mood: 'indicative', role: 'khabar (a verbal sentence, with a hidden fāʿil referring back to الكاتب)',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'writes',
        explanation: 'The same root ك ت ب, now in the imperfect verb pattern يَفْعُلُ.',
      },
      {
        position: 3, surfaceVocalized: 'الْكِتَابَ', surfaceUnvocalized: 'الكتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', patternLabel: 'فِعَال',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi of يكتب', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the book',
        explanation: 'The same root a third time, now in the noun pattern فِعَال — "the thing produced by the action," i.e. a book. One root, three patterns, three completely different jobs in the same sentence.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'verb_object', explanation: 'الكتاب is what is written.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'يكتب الكتاب (with its hidden subject) is predicated of الكاتب.' },
    ],
  },
  {
    code: 'morph-14-form4-causative',
    textVocalized: 'أَخْرَجَ الْمُعَلِّمُ الطَّالِبَ',
    textUnvocalized: 'أخرج المعلم الطالب',
    transliteration: 'akhraja l-muʿallimu ṭ-ṭāliba',
    translationEnglish: 'The teacher made the student go out.',
    difficulty: 3,
    notes: 'A Form IV (أَفْعَلَ) example: خَرَجَ ("he went out," Form I, intransitive) becomes أَخْرَجَ ("he made [someone] go out," Form IV) — the prefixed أ adds a causer and, with it, a direct object the Form I verb never had.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أَخْرَجَ', surfaceUnvocalized: 'أخرج', lemma: 'أخرج', rootRadicals: 'خ ر ج', patternLabel: 'Form IV — أَفْعَلَ',
        prefix: 'أ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'fiʿl (Form IV, causative)',
        marker: 'fatḥah', markerType: 'visible', translation: 'made go out',
        explanation: 'أخرج adds the causative أ to خرج\'s root — turning "he went out" into "he made [someone] go out," and turning an intransitive verb into one that now takes a direct object.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher',
        explanation: 'الْمُعَلِّمُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student',
        explanation: 'This object exists only because Form IV made the underlying Form I verb causative — خرج الطالبَ ("the student went out him") would be ungrammatical, since Form I خرج is intransitive.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the causing-to-go-out.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطالب is the one caused to go out — an object only Form IV\'s causative meaning makes possible.' },
    ],
  },
  {
    code: 'morph-15-hamzated-qaraa',
    textVocalized: 'قَرَأَتِ الْبِنْتُ قِصَّةً',
    textUnvocalized: 'قرأت البنت قصة',
    transliteration: 'qaraʾati l-bintu qiṣṣatan',
    translationEnglish: 'The girl read a story.',
    difficulty: 2,
    notes: 'قرأ has همزة as its final radical (لام الفعل) — a different position from the hamzated example already in the bank — so its seat shifts at the very end of the word as suffixes attach.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'قَرَأَتِ', surfaceUnvocalized: 'قرأت', lemma: 'قرأ', rootRadicals: 'ق ر أ', suffix: 'تْ', partOfSpeech: 'verb',
        person: 'third', gender: 'feminine', number: 'singular', role: 'fiʿl', marker: 'fatḥah + تاء التأنيث الساكنة', markerType: 'visible',
        translation: 'read',
        explanation: 'قرأ carries همزة as its third (final) root letter — the mildest hamzated position, since nothing follows it here to force a seat change; contrast قَرَأْتُ (I read), where the همزة keeps a bare ء seat before the sukūn-bearing تُ.',
      },
      {
        position: 2, surfaceVocalized: 'الْبِنْتُ', surfaceUnvocalized: 'البنت', lemma: 'بنت', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the girl',
        explanation: 'الْبِنْتُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'قِصَّةً', surfaceUnvocalized: 'قصة', lemma: 'قصة', rootRadicals: 'ق ص ص', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah + tanwīn (ـً)',
        markerType: 'visible', translation: 'a story',
        explanation: 'قِصَّةً is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'البنت performs the reading.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'قصة is what is read.' },
    ],
  },
  {
    code: 'morph-16-doubled-ahabbat',
    textVocalized: 'أَحَبَّتِ الْأُمُّ ابْنَهَا',
    textUnvocalized: 'أحبت الأم ابنها',
    transliteration: 'aḥabbati l-ummu ibnahā',
    translationEnglish: 'The mother loved her son.',
    difficulty: 3,
    notes: 'أَحَبَّ (Form IV of the doubled root ح ب ب) in a full sentence, plus a bonus attached possessive pronoun (ها, "her") on ابن.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أَحَبَّتِ', surfaceUnvocalized: 'أحبت', lemma: 'أحب', rootRadicals: 'ح ب ب', patternLabel: 'Form IV — أَفْعَلَ',
        prefix: 'أ', suffix: 'تْ', partOfSpeech: 'verb', person: 'third', gender: 'feminine', number: 'singular', role: 'fiʿl',
        marker: 'fatḥah + تاء التأنيث الساكنة', markerType: 'visible', translation: 'loved',
        explanation: 'The doubled بّ stays merged here because the تاء التأنيث ت is directly followed by a vowel (الأمُّ\'s own initial hamzat al-waṣl blends in) — contrast a form like أَحْبَبْتُ ("I loved"), where the consonant-initial تُ forces the doubled letters to split apart.',
      },
      {
        position: 2, surfaceVocalized: 'الْأُمُّ', surfaceUnvocalized: 'الأم', lemma: 'أم', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the mother',
        explanation: 'الْأُمُّ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'ابْنَهَا', surfaceUnvocalized: 'ابنها', lemma: 'ابن', suffix: 'هَا', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite (via attached pronoun)', grammaticalCase: 'accusative', role: 'mafʿūl bihi; مضاف with هَا as مضاف إليه',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'her son',
        explanation: 'ابن is مضاف to the attached pronoun ها ("her"), which supplies its definiteness exactly as a full noun would — the whole phrase ابنها is what receives the mother\'s love.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الأم performs the loving.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'ابنها is who is loved.' },
    ],
  },
  {
    code: 'morph-17-hollow-zaara',
    textVocalized: 'زَارَ الرَّجُلُ صَدِيقَهُ',
    textUnvocalized: 'زار الرجل صديقه',
    transliteration: 'zāra r-rajulu ṣadīqahu',
    translationEnglish: 'The man visited his friend.',
    difficulty: 3,
    notes: 'A hollow verb (ز و ر) with fresh vocabulary beyond قال/باع, plus an attached possessive pronoun on the object.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'زَارَ', surfaceUnvocalized: 'زار', lemma: 'زار', rootRadicals: 'ز و ر', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (hollow — middle radical و contracted into a long ا)', marker: 'estimated fatḥah',
        markerType: 'estimated', translation: 'visited',
        explanation: 'زار contracts the root\'s middle و into a long ا in the perfect, exactly like قال does for its middle و — the same hollow-verb mechanism, different root.',
      },
      {
        position: 2, surfaceVocalized: 'الرَّجُلُ', surfaceUnvocalized: 'الرجل', lemma: 'رجل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the man',
        explanation: 'الرَّجُلُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'صَدِيقَهُ', surfaceUnvocalized: 'صديقه', lemma: 'صديق', suffix: 'هُ', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite (via attached pronoun)', grammaticalCase: 'accusative', role: 'mafʿūl bihi; مضاف with هُ as مضاف إليه',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'his friend',
        explanation: 'صَدِيقَهُ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الرجل performs the visiting.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'صديقه is who is visited.' },
    ],
  },
  {
    code: 'morph-18-defective-daaa',
    textVocalized: 'دَعَا الرَّجُلُ صَدِيقَهُ',
    textUnvocalized: 'دعا الرجل صديقه',
    transliteration: 'daʿā r-rajulu ṣadīqahu',
    translationEnglish: 'The man called his friend.',
    difficulty: 3,
    notes: 'A defective verb (د ع و, weak final radical) with fresh vocabulary — the same مَدّ-final شكل as رمى/مشى but a different root.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'دَعَا', surfaceUnvocalized: 'دعا', lemma: 'دعا', rootRadicals: 'د ع و', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (defective — final radical و surfaces as ا in the perfect)', marker: 'estimated fatḥah',
        markerType: 'estimated', translation: 'called',
        explanation: 'دعا\'s final root letter و appears here as a long ا, following the same defective-verb contraction pattern covered for ى-final and و-final roots elsewhere in this unit.',
      },
      {
        position: 2, surfaceVocalized: 'الرَّجُلُ', surfaceUnvocalized: 'الرجل', lemma: 'رجل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the man',
        explanation: 'الرَّجُلُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'صَدِيقَهُ', surfaceUnvocalized: 'صديقه', lemma: 'صديق', suffix: 'هُ', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite (via attached pronoun)', grammaticalCase: 'accusative', role: 'mafʿūl bihi; مضاف with هُ as مضاف إليه',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'his friend',
        explanation: 'صَدِيقَهُ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الرجل performs the calling.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'صديقه is who is called.' },
    ],
  },
  {
    code: 'morph-19-root-pattern-daras',
    textVocalized: 'الدَّارِسُ يَدْرُسُ فِي الْمَدْرَسَةِ',
    textUnvocalized: 'الدارس يدرس في المدرسة',
    transliteration: 'ad-dārisu yadrusu fī l-madrasati',
    translationEnglish: 'The student studies at the school.',
    difficulty: 2,
    notes: 'A second root-and-pattern showcase (compare morph-13\'s ك ت ب) using د ر س, ending in a noun-of-place pattern rather than the "product of the action" pattern.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الدَّارِسُ', surfaceUnvocalized: 'الدارس', lemma: 'دارس', rootRadicals: 'د ر س', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student (lit. "the one who studies")',
        explanation: 'الدَّارِسُ is the subject of the nominal sentence.',
      },
      {
        position: 2, surfaceVocalized: 'يَدْرُسُ', surfaceUnvocalized: 'يدرس', lemma: 'درس', rootRadicals: 'د ر س', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', mood: 'indicative', role: 'khabar (verbal sentence, hidden fāʿil referring to الدارس)',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'studies',
        explanation: 'يَدْرُسُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'ḥarf jarr (preposition)',
        marker: 'built (مبني)', markerType: 'positional', translation: 'in/at',
        explanation: 'فِي never takes a case ending itself — it governs the following noun into the genitive.',
      },
      {
        position: 4, surfaceVocalized: 'الْمَدْرَسَةِ', surfaceUnvocalized: 'المدرسة', lemma: 'مدرسة', rootRadicals: 'د ر س', patternLabel: 'Noun of place (feminine) — مَفْعَلة',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'majrūr of في', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the school',
        explanation: 'The same root د ر س a third time, now in the noun-of-place pattern مَفْعَلة — "the place where the action happens." Three patterns (فَاعِل، يَفْعُلُ، مَفْعَلة), one root, one coherent scene.',
      },
    ],
    dependencies: [
      { headPosition: 3, dependentPosition: 4, relation: 'preposition_object', explanation: 'المدرسة is majrūr, governed by في.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'يدرس في المدرسة (with its hidden subject) is predicated of الدارس.' },
    ],
  },
  {
    code: 'morph-20-form10-istaqbala',
    textVocalized: 'اسْتَقْبَلَ الْمُدِيرُ الضُّيُوفَ',
    textUnvocalized: 'استقبل المدير الضيوف',
    transliteration: 'istaqbala l-mudīru ḍ-ḍuyūfa',
    translationEnglish: 'The director received the guests.',
    difficulty: 3,
    notes: 'A Form X (اسْتَفْعَلَ) example, filling out the derived-forms family alongside the II/IV/V/VII/VIII already in the bank: Form X\'s tendency is "to seek or treat as" — استقبل, roughly "to seek to be facing/meeting," i.e. to receive.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'اسْتَقْبَلَ', surfaceUnvocalized: 'استقبل', lemma: 'استقبل', rootRadicals: 'ق ب ل', patternLabel: 'Form X — اِسْتَفْعَلَ',
        prefix: 'است', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'fiʿl (Form X)',
        marker: 'fatḥah', markerType: 'visible', translation: 'received',
        explanation: 'استقبل is built on the root ق ب ل ("facing/meeting," the same root behind قَبْل "before" and مُقَابِل "facing") with the Form X سـت prefix — "to seek to receive/welcome."',
      },
      {
        position: 2, surfaceVocalized: 'الْمُدِيرُ', surfaceUnvocalized: 'المدير', lemma: 'مدير', rootRadicals: 'د و ر', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the director',
        explanation: 'الْمُدِيرُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الضُّيُوفَ', surfaceUnvocalized: 'الضيوف', lemma: 'ضيف', prefix: 'ال', partOfSpeech: 'noun', number: 'plural',
        definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the guests',
        explanation: 'الضُّيُوفَ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المدير performs the receiving.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الضيوف is who is received.' },
    ],
  },
  {
    code: 'morph-21-hamzated-initial-akhadha',
    textVocalized: 'أَخَذَ الْوَلَدُ الْكُرَةَ',
    textUnvocalized: 'أخذ الولد الكرة',
    transliteration: 'akhadha l-waladu l-kurata',
    translationEnglish: 'The boy took the ball.',
    difficulty: 2,
    notes: 'أخذ carries همزة as its first radical (فاء الفعل) — a third, distinct hamzated position from قرأ (final, morph-15) and سأل (middle).',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أَخَذَ', surfaceUnvocalized: 'أخذ', lemma: 'أخذ', rootRadicals: 'أ خ ذ', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (hamzated — همزة as فاء الفعل, the first radical)', marker: 'fatḥah', markerType: 'visible',
        translation: 'took',
        explanation: 'A همزة in the first radical position is the one most prone to unusual behavior in derived forms — Form VIII of this same root is اتَّخَذَ, not اِأْتَخَذَ, because an initial hamza assimilates into the following ت.',
      },
      {
        position: 2, surfaceVocalized: 'الْوَلَدُ', surfaceUnvocalized: 'الولد', lemma: 'ولد', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the boy',
        explanation: 'الْوَلَدُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الْكُرَةَ', surfaceUnvocalized: 'الكرة', lemma: 'كرة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the ball',
        explanation: 'الْكُرَةَ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الولد performs the taking.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الكرة is what is taken.' },
    ],
  },
  {
    code: 'morph-22-doubled-madda-sentence',
    textVocalized: 'مَدَّ الْعَامِلُ الْحَبْلَ',
    textUnvocalized: 'مد العامل الحبل',
    transliteration: 'madda l-ʿāmilu l-ḥabla',
    translationEnglish: 'The worker extended the rope.',
    difficulty: 2,
    notes: 'مدّ used in a full annotated sentence for the first time, rather than only in isolated conjugation exercises — merged consonants (دّ) staying merged because no vowel needs to fall between them here.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'مَدَّ', surfaceUnvocalized: 'مد', lemma: 'مد', rootRadicals: 'م د د', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (doubled root, merged)', marker: 'fatḥah', markerType: 'visible', translation: 'extended',
        explanation: 'مَدَّ keeps its two دs merged because nothing here forces them apart — compare مَدَدْتُ ("I extended"), where the consonant-initial تُ suffix splits them back into د-د.',
      },
      {
        position: 2, surfaceVocalized: 'الْعَامِلُ', surfaceUnvocalized: 'العامل', lemma: 'عامل', rootRadicals: 'ع م ل', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the worker',
        explanation: 'الْعَامِلُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الْحَبْلَ', surfaceUnvocalized: 'الحبل', lemma: 'حبل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the rope',
        explanation: 'الْحَبْلَ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'العامل performs the extending.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الحبل is what is extended.' },
    ],
  },
  {
    code: 'morph-23-hollow-baa',
    textVocalized: 'بَاعَ التَّاجِرُ الْبِضَاعَةَ',
    textUnvocalized: 'باع التاجر البضاعة',
    transliteration: 'bāʿa t-tājiru l-biḍāʿata',
    translationEnglish: 'The merchant sold the merchandise.',
    difficulty: 3,
    notes: 'A ي-type hollow verb (ب ي ع) contrasting with the و-type hollow verbs (قال، زار) already in the bank — the same contraction mechanism, a different middle radical.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'بَاعَ', surfaceUnvocalized: 'باع', lemma: 'باع', rootRadicals: 'ب ي ع', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (hollow — middle radical ي contracted into a long ا)', marker: 'estimated fatḥah',
        markerType: 'estimated', translation: 'sold',
        explanation: 'باع contracts its middle ي into a long ا in the perfect, exactly as قال contracts a middle و — the underlying radical only resurfaces in forms like بِعْتُ ("I sold"), where it shows up as a short ِ before a consonant-initial suffix.',
      },
      {
        position: 2, surfaceVocalized: 'التَّاجِرُ', surfaceUnvocalized: 'التاجر', lemma: 'تاجر', rootRadicals: 'ت ج ر', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the merchant',
        explanation: 'التَّاجِرُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الْبِضَاعَةَ', surfaceUnvocalized: 'البضاعة', lemma: 'بضاعة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the merchandise',
        explanation: 'الْبِضَاعَةَ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'التاجر performs the selling.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'البضاعة is what is sold.' },
    ],
  },
  {
    code: 'morph-24-defective-rama',
    textVocalized: 'رَمَى اللَّاعِبُ الْكُرَةَ',
    textUnvocalized: 'رمى اللاعب الكرة',
    transliteration: 'ramā l-lāʿibu l-kurata',
    translationEnglish: 'The player threw the ball.',
    difficulty: 3,
    notes: 'A ى-final defective verb (ر م ي) — pairs with morph-18\'s و-final دعا to show both defective subtypes with fresh vocabulary.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'رَمَى', surfaceUnvocalized: 'رمى', lemma: 'رمى', rootRadicals: 'ر م ي', partOfSpeech: 'verb', person: 'third',
        gender: 'masculine', number: 'singular', role: 'fiʿl (defective — final radical ي surfaces as ى in the perfect)', marker: 'estimated fatḥah',
        markerType: 'estimated', translation: 'threw',
        explanation: 'رمى contracts its final root letter ي into ى in the perfect — the same defective-verb pattern as دعا (morph-18), with a different root.',
      },
      {
        position: 2, surfaceVocalized: 'اللَّاعِبُ', surfaceUnvocalized: 'اللاعب', lemma: 'لاعب', rootRadicals: 'ل ع ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the player',
        explanation: 'اللَّاعِبُ performs the action, so it is nominative as فاعل.',
      },
      {
        position: 3, surfaceVocalized: 'الْكُرَةَ', surfaceUnvocalized: 'الكرة', lemma: 'كرة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the ball',
        explanation: 'الْكُرَةَ is what receives the action, so it is accusative as مفعول به.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'اللاعب performs the throwing.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الكرة is what is thrown.' },
    ],
  },
];
