import type { SentenceSeed } from '../sentenceTypes';

export const nominalSentences: SentenceSeed[] = [
  {
    code: 'nom-01-mubtada-khabar-basic',
    textVocalized: 'الطَّالِبُ مُجْتَهِدٌ',
    textUnvocalized: 'الطالب مجتهد',
    transliteration: 'aṭ-ṭālibu mujtahidun',
    translationEnglish: 'The student is diligent.',
    difficulty: 1,
    notes: 'The founding example of the nominal sentence: definite mubtada, indefinite single-word khabar, both nominative by default.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', stem: 'طالب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite',
        grammaticalCase: 'nominative', role: 'mubtada (subject of the nominal sentence)', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the student',
        explanation: 'The mubtada is the noun the sentence is about. It is definite (marked by ال) and nominative — the default case for a mubtada.',
        traditionalExplanation: 'مبتدأ مرفوع وعلامة رفعه الضمة الظاهرة.',
      },
      {
        position: 2, surfaceVocalized: 'مُجْتَهِدٌ', surfaceUnvocalized: 'مجتهد', lemma: 'مجتهد', rootRadicals: 'ج ه د', patternLabel: undefined,
        stem: 'مجتهد', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite',
        grammaticalCase: 'nominative', role: 'khabar (predicate)', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'diligent',
        explanation: 'The khabar tells us something about the mubtada. Here it is a single indefinite adjective-like noun (a Form VIII active participle from ج ه د, "to strive"), also nominative — khabar matches mubtada in case by default.',
        traditionalExplanation: 'خبر المبتدأ مرفوع وعلامة رفعه الضمة المنونة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مُجْتَهِدٌ is predicated of الطَّالِبُ: the sentence asserts that the diligence applies to the student.' },
    ],
  },
  {
    code: 'nom-02-demonstrative-indefinite-khabar',
    textVocalized: 'هَذَا كِتَابٌ',
    textUnvocalized: 'هذا كتاب',
    transliteration: 'hādhā kitābun',
    translationEnglish: 'This is a book.',
    difficulty: 1,
    notes: 'Arabic has no separate word for "is" here — the nominal sentence structure itself carries that meaning.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'هَذَا', surfaceUnvocalized: 'هذا', lemma: 'هذا', partOfSpeech: 'demonstrative',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'built (مبني), estimated nominative', markerType: 'estimated',
        translation: 'this',
        explanation: 'Demonstratives are built words (مبني) — they never change their ending no matter their grammatical role. Their case is still assigned and estimated even though no vowel changes.',
        traditionalExplanation: 'اسم إشارة مبني في محل رفع مبتدأ.',
      },
      {
        position: 2, surfaceVocalized: 'كِتَابٌ', surfaceUnvocalized: 'كتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب',
        stem: 'كتاب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite',
        grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'a book',
        explanation: 'English inserts "is" here; Arabic needs no linking verb in a present-tense nominal sentence — the juxtaposition of mubtada and khabar itself expresses "is."',
        traditionalExplanation: 'خبر المبتدأ مرفوع وعلامة رفعه الضمة المنونة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'كِتَابٌ identifies what هَذَا refers to.' },
    ],
  },
  {
    code: 'nom-03-demonstrative-feminine-adjective',
    textVocalized: 'هَذِهِ الْمَدْرَسَةُ جَمِيلَةٌ',
    textUnvocalized: 'هذه المدرسة جميلة',
    transliteration: 'hādhihi l-madrasatu jamīlatun',
    translationEnglish: 'This school is beautiful.',
    difficulty: 2,
    notes: 'هَذِهِ + noun functions as a single definite mubtada phrase; adjective agreement here is only in gender/number/definiteness since جميلة is the khabar, not a نعت.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'هَذِهِ', surfaceUnvocalized: 'هذه', lemma: 'هذه', partOfSpeech: 'demonstrative',
        gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'built, estimated nominative', markerType: 'estimated',
        translation: 'this (f.)',
        explanation: 'هَذِهِ is the feminine counterpart of هَذَا, chosen because المدرسة is grammatically feminine.',
      },
      {
        position: 2, surfaceVocalized: 'الْمَدْرَسَةُ', surfaceUnvocalized: 'المدرسة', lemma: 'مدرسة', rootRadicals: 'د ر س', patternLabel: 'Noun of place (feminine) — مَفْعَلة',
        prefix: 'ال', stem: 'مدرسة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite',
        grammaticalCase: 'nominative', role: 'badal (or noun in apposition, restating the demonstrative\'s referent)', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the school',
        explanation: 'المدرسة restates exactly what هذه points at, agreeing with it in case (nominative) as apposition (بدل) to the demonstrative mubtada.',
      },
      {
        position: 3, surfaceVocalized: 'جَمِيلَةٌ', surfaceUnvocalized: 'جميلة', lemma: 'جميل', suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'beautiful',
        explanation: 'جَمِيلَةٌ carries the feminine ة to agree with المدرسة. Note this is agreement as a khabar (predicate), not as a نعت (attributive adjective) — the four-feature agreement rule for adjectives only applies inside a noun phrase, not between mubtada and khabar.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'المدرسة is in apposition to هذه, clarifying its referent.' },
      { headPosition: 2, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'جميلة is predicated of المدرسة (and, through it, of هذه).' },
    ],
  },
  {
    code: 'nom-04-khabar-shibh-jumla',
    textVocalized: 'الْكِتَابُ عَلَى الطَّاوِلَةِ',
    textUnvocalized: 'الكتاب على الطاولة',
    transliteration: 'al-kitābu ʿalā ṭ-ṭāwilati',
    translationEnglish: 'The book is on the table.',
    difficulty: 2,
    notes: 'Demonstrates a prepositional-phrase khabar (شبه جملة) rather than a single-word khabar.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْكِتَابُ', surfaceUnvocalized: 'الكتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', prefix: 'ال', stem: 'كتاب',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the book',
        explanation: 'Definite noun in default nominative position as mubtada.',
      },
      {
        position: 2, surfaceVocalized: 'عَلَى', surfaceUnvocalized: 'على', lemma: 'على', partOfSpeech: 'particle', role: 'preposition (حرف جر) governing the following noun',
        translation: 'on', explanation: 'A preposition has no case of its own; it governs the noun that follows, forcing it into the genitive.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّاوِلَةِ', surfaceUnvocalized: 'الطاولة', lemma: 'طاولة', prefix: 'ال', stem: 'طاولة', suffix: 'ة',
        partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'majrūr (object of the preposition)', marker: 'kasrah (ـِ)', markerType: 'visible', governedByPosition: 2,
        translation: 'the table',
        explanation: 'الطاولة is genitive purely because عَلَى governs it — this is grammatical government (العامل) in its simplest form.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'عَلَى governs الطَّاوِلَةِ, assigning it the genitive case.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The whole prepositional phrase عَلَى الطَّاوِلَةِ functions as the khabar of الكتاب.' },
    ],
  },
  {
    code: 'nom-05-adjective-agreement-definite',
    textVocalized: 'الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ',
    textUnvocalized: 'الطالب المجتهد حاضر',
    transliteration: 'aṭ-ṭālibu l-mujtahidu ḥāḍirun',
    translationEnglish: 'The diligent student is present.',
    difficulty: 2,
    notes: 'Contrast with nom-01: here المجتهد is a نعت (attributive adjective) inside the mubtada phrase, not the khabar — so it must match الطالب in all four agreement features, including definiteness and case.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student',
        explanation: 'Head noun of the mubtada phrase.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُجْتَهِدُ', surfaceUnvocalized: 'المجتهد', lemma: 'مجتهد', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'naʿt (attributive adjective) of الطالب',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the diligent',
        explanation: 'This time المجتهد takes ال and matches الطالب in gender, number, definiteness, and case — all four agreement features required of a نعت, not just case.',
        traditionalExplanation: 'نعت مرفوع وعلامة رفعه الضمة، تابع للمنعوت في التعريف والعدد والنوع والإعراب.',
      },
      {
        position: 3, surfaceVocalized: 'حَاضِرٌ', surfaceUnvocalized: 'حاضر', lemma: 'حاضر', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'present',
        explanation: 'The khabar of the whole sentence is حَاضِرٌ, predicated of the entire phrase "the diligent student," not of المجتهد alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'noun_adjective', explanation: 'المجتهد describes الطالب and must agree with it in all four features.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'حاضر is predicated of the whole subject phrase headed by الطالب.' },
    ],
  },
  {
    code: 'nom-06-idafa-basic',
    textVocalized: 'كِتَابُ الطَّالِبِ جَدِيدٌ',
    textUnvocalized: 'كتاب الطالب جديد',
    transliteration: 'kitābu ṭ-ṭālibi jadīdun',
    translationEnglish: "The student's book is new.",
    difficulty: 2,
    notes: 'The classic إضافة (possessive construction): the first noun takes no ال and no tanwīn, the second is genitive and lends its definiteness to the whole phrase.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كِتَابُ', surfaceUnvocalized: 'كتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative',
        role: 'mubtada; مضاف (first term of the idafa)', marker: 'ḍammah, no tanwīn', markerType: 'visible',
        translation: "book (of)",
        explanation: 'As the مضاف, كتاب can never take ال or tanwīn — it borrows its definiteness from الطالب that follows. Its case (nominative here) still comes from its own role as mubtada.',
        traditionalExplanation: 'مبتدأ مرفوع، وهو مضاف.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبِ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'muḍāf ilayh (second term of the idafa)',
        marker: 'kasrah (ـِ)', markerType: 'visible', translation: "the student's",
        explanation: 'المضاف إليه is always genitive — this is a fixed rule, independent of whatever role the whole إضافة phrase plays in the larger sentence.',
        traditionalExplanation: 'مضاف إليه مجرور وعلامة جره الكسرة.',
      },
      {
        position: 3, surfaceVocalized: 'جَدِيدٌ', surfaceUnvocalized: 'جديد', lemma: 'جديد', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'new',
        explanation: 'خبر of the whole إضافة phrase "كتاب الطالب," which behaves as a single definite noun phrase for the purposes of the nominal sentence.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'الطالب is the possessor; its genitive case and its definiteness both flow from this relationship.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'جديد is predicated of the whole idafa phrase.' },
    ],
  },
  {
    code: 'nom-07-idafa-passive-participle-khabar',
    textVocalized: 'بَابُ الْبَيْتِ مَفْتُوحٌ',
    textUnvocalized: 'باب البيت مفتوح',
    transliteration: 'bābu l-bayti maftūḥun',
    translationEnglish: 'The door of the house is open.',
    difficulty: 2,
    tokens: [
      {
        position: 1, surfaceVocalized: 'بَابُ', surfaceUnvocalized: 'باب', lemma: 'باب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative', role: 'mubtada; مضاف',
        marker: 'ḍammah, no tanwīn', markerType: 'visible', translation: 'door (of)',
        explanation: 'مضاف — takes its definiteness from البيت.',
      },
      {
        position: 2, surfaceVocalized: 'الْبَيْتِ', surfaceUnvocalized: 'البيت', lemma: 'بيت', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'muḍāf ilayh', marker: 'kasrah (ـِ)', markerType: 'visible',
        translation: 'the house',
        explanation: 'مضاف إليه, genitive by the fixed idafa rule.',
      },
      {
        position: 3, surfaceVocalized: 'مَفْتُوحٌ', surfaceUnvocalized: 'مفتوح', lemma: 'مفتوح', rootRadicals: 'ف ت ح', patternLabel: 'Passive participle (Form I) — مَفْعُول',
        partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'nominative',
        role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'open',
        explanation: 'A passive participle (اسم مفعول) used as an ordinary adjective — "opened," i.e. "open." Its case comes purely from its syntactic role as khabar, unrelated to its morphological shape.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'البيت possesses باب.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'مفتوح is predicated of the whole idafa phrase باب البيت.' },
    ],
  },
  {
    code: 'nom-08-plural-mubtada-shibh-jumla',
    textVocalized: 'الطُّلَّابُ فِي الْفَصْلِ',
    textUnvocalized: 'الطلاب في الفصل',
    transliteration: 'aṭ-ṭullābu fī l-faṣli',
    translationEnglish: 'The students are in the classroom.',
    difficulty: 2,
    notes: 'الطلاب is a broken plural (جمع تكسير) of الطالب — its shape changes internally rather than by suffix, but it is still grammatically singular in form for agreement purposes elsewhere (contrast with sound plurals).',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'طلاب is a broken plural: an internal vowel-pattern change (فُعَّال) rather than an added suffix. It still takes ordinary singular-noun case endings.',
      },
      {
        position: 2, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'preposition governing the following noun', translation: 'in',
        explanation: 'A preposition of location, governing الفصل into the genitive.',
      },
      {
        position: 3, surfaceVocalized: 'الْفَصْلِ', surfaceUnvocalized: 'الفصل', lemma: 'فصل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the classroom',
        explanation: 'Genitive by government of في.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'في governs الفصل.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The prepositional phrase في الفصل is the khabar of الطلاب.' },
    ],
  },
  {
    code: 'nom-09-pronoun-mubtada-plural-khabar',
    textVocalized: 'نَحْنُ طُلَّابٌ مُجْتَهِدُونَ',
    textUnvocalized: 'نحن طلاب مجتهدون',
    transliteration: 'naḥnu ṭullābun mujtahidūna',
    translationEnglish: 'We are diligent students.',
    difficulty: 2,
    notes: 'A detached (free-standing) personal pronoun as mubtada, with a khabar built from an indefinite noun plus its نعت — the sound masculine plural نعت agrees with طلاب on all four features even though طلاب itself is a broken plural.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'نَحْنُ', surfaceUnvocalized: 'نحن', lemma: 'نحن', partOfSpeech: 'pronoun', person: 'first', number: 'plural',
        grammaticalCase: 'nominative', role: 'mubtada', marker: 'built (مبني), estimated nominative', markerType: 'estimated', translation: 'we',
        explanation: 'Detached personal pronouns like نحن are مبني (built) — they never take a case ending — but a case is still assigned to them by their grammatical role, here مبتدأ.',
      },
      {
        position: 2, surfaceVocalized: 'طُلَّابٌ', surfaceUnvocalized: 'طلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'plural', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar',
        marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'students',
        explanation: 'طلاب (broken plural of طالب) is the head of the khabar phrase — indefinite and nominative, exactly like a single-word khabar.',
      },
      {
        position: 3, surfaceVocalized: 'مُجْتَهِدُونَ', surfaceUnvocalized: 'مجتهدون', lemma: 'مجتهد', rootRadicals: 'ج ه د', suffix: 'ون',
        patternLabel: 'Active participle (Form VIII) — مُفْتَعِل', partOfSpeech: 'adjective', gender: 'masculine', number: 'plural',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'naʿt of طلاب', marker: 'ـُونَ (sound masculine plural nominative)',
        markerType: 'secondary', translation: 'diligent',
        explanation: 'Even though طلاب is a broken plural, its human-referring نعت regularly takes the sound masculine plural shape (مُجْتَهِدُونَ) rather than a broken-plural adjective — the نعت still agrees in gender, number, definiteness, and case, just realized through a different plural mechanism than its noun.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'طلابٌ مجتهدون (the whole noun+adjective phrase) is predicated of نحن.' },
      { headPosition: 2, dependentPosition: 3, relation: 'noun_adjective', explanation: 'مجتهدون describes طلاب and agrees with it in gender, number, definiteness, and case.' },
    ],
  },
  {
    code: 'nom-10-interrogative-khabar-muqaddam',
    textVocalized: 'أَيْنَ الْمُعَلِّمُ؟',
    textUnvocalized: 'أين المعلم؟',
    transliteration: 'ayna l-muʿallimu',
    translationEnglish: 'Where is the teacher?',
    difficulty: 2,
    notes: 'An interrogative adverb of place obligatorily opens its sentence, which forces the khabar (أين) in front of the mubtada (المعلم) — the reverse order from every earlier nominal sentence in this course.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أَيْنَ', surfaceUnvocalized: 'أين', lemma: 'أين', partOfSpeech: 'interrogative',
        grammaticalCase: 'nominative', role: 'khabar muqaddam (fronted predicate — interrogative adverb of place)',
        marker: 'built (مبني), estimated nominative', markerType: 'estimated', translation: 'where',
        explanation: 'أين is a built interrogative word that must open its sentence; grammatically it still functions as the khabar of المعلم, just placed first.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada muʾakhkhar (delayed subject)', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher',
        explanation: 'المعلم is still the مبتدأ, just delayed past its khabar — word order changes, but the underlying roles and their default case (both nominative) do not.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 1, relation: 'mubtada_khabar', explanation: 'أين is the (fronted) khabar of المعلم, the (delayed) mubtada — a question about where the teacher is located.' },
    ],
  },
  {
    code: 'nom-11-dual-teachers-busy',
    textVocalized: 'الْمُعَلِّمَانِ مَشْغُولَانِ',
    textUnvocalized: 'المعلمان مشغولان',
    transliteration: 'al-muʿallimāni mashghūlāni',
    translationEnglish: 'The two teachers are busy.',
    difficulty: 2,
    notes: 'A second dual mubtada/khabar pair (compare case-04), this time with a passive-participle khabar rather than an active-participle one.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْمُعَلِّمَانِ', surfaceUnvocalized: 'المعلمان', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ان',
        partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ـَانِ (dual nominative suffix)', markerType: 'secondary', translation: 'the two teachers',
        explanation: 'Dual nominative suffix replacing the singular\'s ordinary ḍammah, exactly as in case-04.',
      },
      {
        position: 2, surfaceVocalized: 'مَشْغُولَانِ', surfaceUnvocalized: 'مشغولان', lemma: 'مشغول', rootRadicals: 'ش غ ل', suffix: 'ان',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', partOfSpeech: 'adjective', gender: 'masculine', number: 'dual',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـَانِ', markerType: 'secondary', translation: 'busy',
        explanation: 'مشغول is the اسم مفعول (passive participle) of شغل, "to occupy" — literally "occupied," used here as an ordinary predicate adjective meaning "busy." It copies the mubtada\'s dual number because it is a single-word khabar, not a following verb.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مشغولان is predicated of المعلمان and matches its dual number.' },
    ],
  },
  {
    code: 'nom-12-idafa-chain',
    textVocalized: 'بَابُ بَيْتِ الطَّالِبِ مَفْتُوحٌ',
    textUnvocalized: 'باب بيت الطالب مفتوح',
    transliteration: 'bābu bayti ṭ-ṭālibi maftūḥun',
    translationEnglish: "The door of the student's house is open.",
    difficulty: 4,
    notes: 'A three-term idafa chain: بَيْتِ is simultaneously مضاف إليه (of باب) and مضاف (to الطالب) — the hallmark of a chained إضافة. Only the final term (الطالب) can carry ال; every term before the last takes neither ال nor تنوين.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'بَابُ', surfaceUnvocalized: 'باب', lemma: 'باب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative', role: 'mubtada; مضاف (first term of the chain)',
        marker: 'ḍammah, no tanwīn', markerType: 'visible', translation: 'door (of)',
        explanation: 'As the first مضاف in the chain, باب can never take ال or تنوين — its definiteness ultimately comes from الطالب at the very end.',
      },
      {
        position: 2, surfaceVocalized: 'بَيْتِ', surfaceUnvocalized: 'بيت', lemma: 'بيت', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh of باب; simultaneously مضاف (second term, relative to الطالب)',
        marker: 'kasrah, no tanwīn', markerType: 'visible', translation: "house (of)",
        explanation: 'This is the key move in an idafa chain: بيت is genitive because it is مضاف إليه of باب, but it also takes no ال or تنوين of its own because it is itself مضاف to الطالب — every middle term in a chain plays both roles at once.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّالِبِ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh (final term of the chain)', marker: 'kasrah (ـِ)', markerType: 'visible', translation: "the student's",
        explanation: 'The final term of the chain — the only one allowed to carry ال — and the source of definiteness for the entire three-word phrase.',
      },
      {
        position: 4, surfaceVocalized: 'مَفْتُوحٌ', surfaceUnvocalized: 'مفتوح', lemma: 'مفتوح', rootRadicals: 'ف ت ح',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'open',
        explanation: 'Predicated of the entire three-term idafa chain, not just of بيت or الطالب alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'بيت is مضاف إليه of باب, supplying part of its definiteness and forcing its genitive case.' },
      { headPosition: 2, dependentPosition: 3, relation: 'mudaf_mudaf_ilayh', explanation: 'الطالب is مضاف إليه of بيت — بيت is simultaneously مضاف إليه (to باب) and مضاف (to الطالب), the hallmark of an idafa chain.' },
      { headPosition: 1, dependentPosition: 4, relation: 'mubtada_khabar', explanation: 'مفتوح is predicated of the whole three-term idafa chain باب بيت الطالب.' },
    ],
  },
  {
    code: 'nom-13-nominal-with-verbal-khabar',
    textVocalized: 'الْمُعَلِّمُ يَشْرَحُ الدَّرْسَ',
    textUnvocalized: 'المعلم يشرح الدرس',
    transliteration: 'al-muʿallimu yashraḥu d-darsa',
    translationEnglish: 'The teacher explains the lesson.',
    difficulty: 2,
    notes: 'Structurally nominal (opens with a noun) even though its khabar is an entire verbal sentence — a direct illustration that "nominal vs. verbal" is about the opening word, not the content.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', patternLabel: 'Active participle (Form II) — مُفَعِّل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite',
        grammaticalCase: 'nominative', role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher',
        explanation: 'Because this word is a noun, the whole sentence is classified as nominal — regardless of what the rest of the sentence contains.',
      },
      {
        position: 2, surfaceVocalized: 'يَشْرَحُ', surfaceUnvocalized: 'يشرح', lemma: 'شرح', rootRadicals: 'ش ر ح', partOfSpeech: 'verb',
        person: 'third', gender: 'masculine', number: 'singular', mood: 'indicative', role: 'verb of the khabar clause (fiʿl)',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'explains',
        explanation: 'يشرح has its own hidden subject pronoun (هو, referring back to المعلم) and forms, together with الدرس, a complete verbal sentence that serves as the khabar.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi of يشرح', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson',
        explanation: 'The direct object of the embedded verb, not of anything the mubtada does directly.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is what is explained.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The whole verbal sentence يشرح الدرس (with its own hidden subject) is predicated of المعلم — a جملة فعلية في محل رفع خبر.' },
    ],
  },
  {
    code: 'nom-14-mubtada-khabar-feminine',
    textVocalized: 'الْبِنْتُ ذَكِيَّةٌ',
    textUnvocalized: 'البنت ذكية',
    transliteration: 'al-bintu dhakiyyatun',
    translationEnglish: 'The girl is smart.',
    difficulty: 1,
    notes: 'The founding mubtada-khabar pattern with a feminine pair, reinforcing that agreement (not just case) matters even in the simplest nominal sentence.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْبِنْتُ', surfaceUnvocalized: 'البنت', lemma: 'بنت', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the girl',
        explanation: 'بنت is one of the small set of Arabic nouns that are feminine without an ة ending — its gender has to be learned, not read off the spelling.',
      },
      {
        position: 2, surfaceVocalized: 'ذَكِيَّةٌ', surfaceUnvocalized: 'ذكية', lemma: 'ذكي', suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)',
        markerType: 'visible', translation: 'smart',
        explanation: 'ذكية takes the ة suffix to agree with البنت\'s feminine gender — the khabar must match the mubtada in gender as well as case.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'ذكية is predicated of البنت and agrees with it in gender and number.' },
    ],
  },
  {
    code: 'nom-15-khabar-zarf',
    textVocalized: 'الطَّائِرُ فَوْقَ الشَّجَرَةِ',
    textUnvocalized: 'الطائر فوق الشجرة',
    transliteration: 'aṭ-ṭāʾiru fawqa sh-shajarati',
    translationEnglish: 'The bird is above the tree.',
    difficulty: 2,
    notes: 'A third khabar type beyond a single word or a preposition phrase: فوق is a ظرف (adverb of place), itself in construct with الشجرة — a خبر ظرف, built the same way a خبر شبه جملة is.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطَّائِرُ', surfaceUnvocalized: 'الطائر', lemma: 'طائر', rootRadicals: 'ط ي ر', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the bird',
        explanation: 'طائر is itself an active participle ("the one who flies") used as an ordinary noun — the same فاعل pattern seen elsewhere doing double duty as a word for "bird."',
      },
      {
        position: 2, surfaceVocalized: 'فَوْقَ', surfaceUnvocalized: 'فوق', lemma: 'فوق', partOfSpeech: 'adverb', grammaticalCase: 'accusative',
        role: 'ẓarf makān (adverb of place), khabar', marker: 'fatḥah (ـَ), built-in to the ẓarf', markerType: 'visible', translation: 'above',
        explanation: 'فوق is a ظرف مكان — always accusative when functioning as an adverb, and itself the head of an idafa with الشجرة. The whole شبه جملة ظرفية serves as the khabar.',
      },
      {
        position: 3, surfaceVocalized: 'الشَّجَرَةِ', surfaceUnvocalized: 'الشجرة', lemma: 'شجرة', rootRadicals: 'ش ج ر', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh of فوق', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the tree',
        explanation: 'الشجرة is genitive as the second term of the idafa فوق الشجرة, exactly like the object of a preposition would be.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'mudaf_mudaf_ilayh', explanation: 'الشجرة is مضاف إليه of the ẓarf فوق.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'فوق الشجرة as a whole is predicated of الطائر.' },
    ],
  },
  {
    code: 'nom-16-definiteness-via-idafa',
    textVocalized: 'كِتَابُ الْمُعَلِّمِ جَدِيدٌ',
    textUnvocalized: 'كتاب المعلم جديد',
    transliteration: 'kitābu l-muʿallimi jadīdun',
    translationEnglish: "The teacher's book is new.",
    difficulty: 2,
    notes: 'كتاب carries no ال of its own, yet the whole mubtada phrase كتاب المعلم counts as definite — idafa to a definite noun is one of the ways a noun becomes definite without ال.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كِتَابُ', surfaceUnvocalized: 'كتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite (via idafa)', state: 'construct (مضاف)', grammaticalCase: 'nominative',
        role: 'mubtada; مضاف', marker: 'ḍammah, no tanwīn', markerType: 'visible', translation: "book (of)",
        explanation: 'كتاب has no ال and no تنوين — as مضاف, it borrows its definiteness entirely from المعلم, the definite noun that follows it.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمِ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh', marker: 'kasrah (ـِ)', markerType: 'visible', translation: "the teacher's",
        explanation: 'المعلم is the source of definiteness for the whole idafa phrase كتاب المعلم — this is exactly why the two-word phrase can serve as a definite mubtada with no ال ever attaching to كتاب.',
      },
      {
        position: 3, surfaceVocalized: 'جَدِيدٌ', surfaceUnvocalized: 'جديد', lemma: 'جديد', partOfSpeech: 'adjective', gender: 'masculine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)',
        markerType: 'visible', translation: 'new',
        explanation: 'Predicated of the whole idafa phrase كتاب المعلم, not of المعلم alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'المعلم is مضاف إليه of كتاب, and the sole source of the phrase\'s definiteness.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'جديد is predicated of the whole idafa phrase كتاب المعلم.' },
    ],
  },
  {
    code: 'nom-17-attributive-adjective',
    textVocalized: 'الْبِنْتُ الذَّكِيَّةُ نَجَحَتْ',
    textUnvocalized: 'البنت الذكية نجحت',
    transliteration: 'al-bintu dh-dhakiyyatu najaḥat',
    translationEnglish: 'The smart girl succeeded.',
    difficulty: 2,
    notes: 'Contrasts with a predicative adjective (a khabar, as in nom-14): here الذكية is attributive (نعت), fully agreeing with البنت in case, definiteness, gender, and number, then the whole noun phrase becomes the subject of a separate verb.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْبِنْتُ', surfaceUnvocalized: 'البنت', lemma: 'بنت', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada; manʿūt (the noun described)',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the girl',
        explanation: 'The head noun that الذكية will describe.',
      },
      {
        position: 2, surfaceVocalized: 'الذَّكِيَّةُ', surfaceUnvocalized: 'الذكية', lemma: 'ذكي', prefix: 'ال', suffix: 'ة', partOfSpeech: 'adjective',
        gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'naʿt (attributive adjective) of البنت',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'smart',
        explanation: 'Unlike a predicative khabar, an attributive نعت must match its noun in all four features at once: case, definiteness, gender, and number — which is why الذكية also carries ال here, unlike the indefinite خبر ذكية in nom-14.',
      },
      {
        position: 3, surfaceVocalized: 'نَجَحَتْ', surfaceUnvocalized: 'نجحت', lemma: 'نجح', rootRadicals: 'ن ج ح', partOfSpeech: 'verb',
        person: 'third', gender: 'feminine', number: 'singular', role: 'khabar (a verbal sentence, with its own hidden fāʿil referring back to البنت)',
        marker: 'sukūn', markerType: 'visible', translation: 'succeeded',
        explanation: 'نجحت is the actual khabar of the whole sentence — the entire noun phrase البنت الذكية is only the mubtada, described by its نعت, then predicated by this verb.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'noun_adjective', explanation: 'الذكية describes البنت, agreeing with it in case, definiteness, gender, and number.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'نجحت (with its hidden subject) is predicated of البنت الذكية as a whole.' },
    ],
  },
  {
    code: 'nom-18-demonstrative-plural',
    textVocalized: 'أُولَئِكَ الطُّلَّابُ مُجْتَهِدُونَ',
    textUnvocalized: 'أولئك الطلاب مجتهدون',
    transliteration: 'ulāʾika ṭ-ṭullābu mujtahidūna',
    translationEnglish: 'Those students are diligent.',
    difficulty: 2,
    notes: 'أولئك is the plural demonstrative ("those"), used for both masculine and feminine plural referents alike — unlike the singular/dual demonstratives, it does not distinguish gender.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أُولَئِكَ', surfaceUnvocalized: 'أولئك', lemma: 'أولئك', partOfSpeech: 'demonstrative', number: 'plural',
        definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'built (مبني), estimated nominative', markerType: 'estimated',
        translation: 'those',
        explanation: 'أولئك is built (مبني) like every demonstrative — it never changes ending for case — and covers plural referents of either gender, unlike هذا/هذه which split by gender only in the singular and dual.',
      },
      {
        position: 2, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'badal (apposition, restating the demonstrative\'s referent)', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'الطلاب restates exactly who أولئك points at, agreeing with it in case as apposition — the same pattern as هذه المدرسة in nom-03, just pluralized.',
      },
      {
        position: 3, surfaceVocalized: 'مُجْتَهِدُونَ', surfaceUnvocalized: 'مجتهدون', lemma: 'مجتهد', suffix: 'ونَ', partOfSpeech: 'noun', number: 'plural',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'وَاو + نَ (sound masculine plural marker)', markerType: 'secondary',
        translation: 'diligent',
        explanation: 'مجتهدون is a sound masculine plural — its nominative marker is the letter و itself (with ن closing the word), not a vowel, which is why this counts as a secondary rather than a visible-vowel marker.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'الطلاب restates the referent of أولئك (apposition, not predication).' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'مجتهدون is predicated of the whole subject أولئك الطلاب.' },
    ],
  },
  {
    code: 'nom-19-mahall-relative-clause-mubtada',
    textVocalized: 'الَّذِي نَجَحَ سَعِيدٌ',
    textUnvocalized: 'الذي نجح سعيد',
    transliteration: 'alladhī najaḥa saʿīdun',
    translationEnglish: 'The one who succeeded is happy.',
    difficulty: 3,
    notes: 'الذي نجح ("the one who succeeded") is a whole relative clause functioning as the mubtada — a clause, not a single word, holds the case-status (محل رفع) that an ordinary noun would otherwise carry.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الَّذِي', surfaceUnvocalized: 'الذي', lemma: 'الذي', partOfSpeech: 'relative pronoun', number: 'singular',
        gender: 'masculine', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada (heading a relative clause)',
        marker: 'built (مبني), estimated nominative', markerType: 'estimated', translation: 'the one who',
        explanation: 'الذي is itself built and case-less in form, but the entire relative clause it heads (الذي نجح) is estimated to be في محل رفع مبتدأ — holding the nominative "slot" as a unit even though no single word in it visibly shows a nominative ending for that role.',
      },
      {
        position: 2, surfaceVocalized: 'نَجَحَ', surfaceUnvocalized: 'نجح', lemma: 'نجح', rootRadicals: 'ن ج ح', partOfSpeech: 'verb',
        person: 'third', gender: 'masculine', number: 'singular', role: 'ṣilat al-mawṣūl (the relative clause\'s own verb, with a hidden fāʿil referring to الذي)',
        marker: 'sukūn', markerType: 'visible', translation: 'succeeded',
        explanation: 'نجح is the صلة الموصول — the clause that gives الذي its content. This verb has no case of its own to speak of (it is a verb, not a noun), but together with الذي it forms the unit that holds مَحَلّ رفع.',
      },
      {
        position: 3, surfaceVocalized: 'سَعِيدٌ', surfaceUnvocalized: 'سعيد', lemma: 'سعيد', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'happy',
        explanation: 'The ordinary, visibly-marked khabar of the whole sentence — predicated of the entire relative clause الذي نجح, not of نجح alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'relative_clause', explanation: 'نجح is the صلة (content clause) of the relative pronoun الذي — together they form one nominal unit.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'سعيد is predicated of the entire relative-clause unit الذي نجح, which holds مَحَلّ رفع مبتدأ as a whole.' },
    ],
  },
  {
    code: 'nom-20-khabar-types-verbal-sentence',
    textVocalized: 'الطُّلَّابُ يَجْتَهِدُونَ',
    textUnvocalized: 'الطلاب يجتهدون',
    transliteration: 'aṭ-ṭullābu yajtahidūna',
    translationEnglish: 'The students work hard.',
    difficulty: 2,
    notes: 'A fourth khabar type alongside a single word, a preposition phrase, and a ẓarf: an entire verbal sentence (جملة فعلية) can itself be the khabar.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'الطُّلَّابُ is the subject of the nominal sentence.',
      },
      {
        position: 2, surfaceVocalized: 'يَجْتَهِدُونَ', surfaceUnvocalized: 'يجتهدون', lemma: 'اجتهد', rootRadicals: 'ج ه د', partOfSpeech: 'verb',
        person: 'third', number: 'plural', mood: 'indicative', role: 'khabar (a full verbal sentence, with الطلاب itself as its overt fāʿil, referenced through agreement)',
        marker: 'ثبوت النون (retaining the ن, since nothing follows to drop it for)', markerType: 'secondary', translation: 'work hard',
        explanation: 'The khabar here is not just this one word but the whole embedded verbal sentence it represents (يجتهدون الطلاب in underlying structure, with الطلاب fronted as topic) — the plural verb agreeing fully because the subject came first.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'يجتهدون (as a full verbal-sentence khabar) is predicated of الطلاب.' },
    ],
  },
  {
    code: 'nom-21-definiteness-fronted-khabar',
    textVocalized: 'فِي الْحَدِيقَةِ أَزْهَارٌ',
    textUnvocalized: 'في الحديقة أزهار',
    transliteration: 'fī l-ḥadīqati azhārun',
    translationEnglish: 'In the garden there are flowers.',
    difficulty: 3,
    notes: 'أزهار is indefinite, so it cannot open the sentence as an ordinary mubtada — the khabar (شبه جملة) is obligatorily fronted first, which is exactly what makes the indefinite noun acceptable as a delayed mubtada (مبتدأ مؤخر).',
    tokens: [
      {
        position: 1, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'ḥarf jarr (preposition), khabar muqaddam (fronted predicate)',
        marker: 'built (مبني)', markerType: 'positional', translation: 'in',
        explanation: 'A preposition never itself takes a case ending — its whole phrase together carries the syntactic job, here fronted as khabar.',
      },
      {
        position: 2, surfaceVocalized: 'الْحَدِيقَةِ', surfaceUnvocalized: 'الحديقة', lemma: 'حديقة', prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr of في', marker: 'kasrah (ـِ)', markerType: 'visible',
        translation: 'the garden',
        explanation: 'الْحَدِيقَةِ is genitive, governed by the preceding preposition.',
      },
      {
        position: 3, surfaceVocalized: 'أَزْهَارٌ', surfaceUnvocalized: 'أزهار', lemma: 'زهرة', rootRadicals: 'ز ه ر', partOfSpeech: 'noun', number: 'plural',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'mubtada muʾakhkhar (delayed subject)', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'flowers',
        explanation: 'Arabic generally avoids opening a nominal sentence with an indefinite noun as mubtada, because "a flowers is..." reads as too vague to be informative. Fronting the شبه جملة خبر first (في الحديقة) fixes this — the sentence is now understood as answering "what/where," which makes the indefinite subject acceptable.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'preposition_object', explanation: 'الحديقة is majrūr, governed by في.' },
      { headPosition: 3, dependentPosition: 1, relation: 'mubtada_khabar', explanation: 'في الحديقة is predicated of أزهار, but appears first because أزهار is indefinite.' },
    ],
  },
  {
    code: 'nom-22-demonstrative-dual',
    textVocalized: 'هَذَانِ كِتَابَانِ',
    textUnvocalized: 'هذان كتابان',
    transliteration: 'hādhāni kitābāni',
    translationEnglish: 'These two are books.',
    difficulty: 2,
    notes: 'هذان is the masculine dual demonstrative — unlike the singular هذا, it is one of the very few demonstratives that does change its ending (اِعراب by و/ي), because dual forms in general are declined even when almost everything else about the word class is built.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'هَذَانِ', surfaceUnvocalized: 'هذان', lemma: 'هذان', partOfSpeech: 'demonstrative', number: 'dual', gender: 'masculine',
        definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada', marker: 'ا (dual nominative marker)', markerType: 'secondary',
        translation: 'these two',
        explanation: 'Dual demonstratives are the exception to "demonstratives never change ending": هذان (nominative) becomes هذين in the accusative/genitive, exactly paralleling the ان/ين pattern of dual nouns.',
      },
      {
        position: 2, surfaceVocalized: 'كِتَابَانِ', surfaceUnvocalized: 'كتابان', lemma: 'كتاب', rootRadicals: 'ك ت ب', suffix: 'انِ', partOfSpeech: 'noun',
        number: 'dual', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ا (dual nominative marker)', markerType: 'secondary',
        translation: 'two books',
        explanation: 'كتابان agrees with هذان in number (dual) exactly as a singular khabar would agree in a singular sentence.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'كتابان is predicated of هذان and matches its dual number.' },
    ],
  },
  {
    code: 'nom-23-idafa-pronoun',
    textVocalized: 'كِتَابِي جَدِيدٌ',
    textUnvocalized: 'كتابي جديد',
    transliteration: 'kitābī jadīdun',
    translationEnglish: 'My book is new.',
    difficulty: 2,
    notes: 'A second idafa subtype beyond noun-to-noun: the مضاف إليه here is an attached pronoun (ي, "my") rather than another noun — the same construct-state rule still applies, just with a pronoun filling the second slot.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كِتَابِي', surfaceUnvocalized: 'كتابي', lemma: 'كتاب', rootRadicals: 'ك ت ب', suffix: 'ي', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite (via idafa to a pronoun)', state: 'construct (مضاف)', grammaticalCase: 'nominative',
        role: 'mubtada; مضاف', marker: 'estimated ḍammah (blocked by the attached pronoun)', markerType: 'estimated', translation: 'my book',
        explanation: 'The attached pronoun ي ("my") is مضاف إليه, exactly like a following noun would be — كتاب takes no ال and no تنوين here either, for the same reason as كِتَابُ الْمُعَلِّمِ. The case vowel on كتاب is estimated rather than pronounced because a long ī vowel (from ي) blocks a short case vowel from being heard.',
      },
      {
        position: 2, surfaceVocalized: 'جَدِيدٌ', surfaceUnvocalized: 'جديد', lemma: 'جديد', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'new',
        explanation: 'جَدِيدٌ is predicated of the mubtada.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'جديد is predicated of the whole idafa-to-pronoun phrase كتابي.' },
    ],
  },
];
