import type { SentenceSeed } from '../sentenceTypes';

export const nominalSentences: SentenceSeed[] = [
  {
    code: 'nom-01-mubtada-khabar-basic',
    textVocalized: 'الطَّالِبُ مُجْتَهِدٌ',
    textUnvocalized: 'الطالب مجتهد',
    transliteration: 'aṭ-ṭālibu mujtahidun',
    translationEnglish: 'The student is diligent.',
    difficulty: 1,
    notes: 'The founding example of the nominal sentence: definite mubtada, indefinite single-word khabar, both nominative by default.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', stem: 'طالب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite',
        grammaticalCase: 'nominative', role: 'mubtada (subject of the nominal sentence)', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the student',
        explanation: 'The mubtada is the noun the sentence is about. It is definite (marked by ال) and nominative — the default case for a mubtada.',
        traditionalExplanation: 'مبتدأ مرفوع وعلامة رفعه الضمة الظاهرة.',
      },
      {
        position: 2, surfaceVocalized: 'مُجْتَهِدٌ', surfaceUnvocalized: 'مجتهد', lemma: 'مجتهد', rootRadicals: 'ج ه د', patternLabel: undefined,
        stem: 'مجتهد', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite',
        grammaticalCase: 'nominative', role: 'khabar (predicate)', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'diligent',
        explanation: 'The khabar tells us something about the mubtada. Here it is a single indefinite adjective-like noun (a Form VIII active participle from ج ه د, "to strive"), also nominative — khabar matches mubtada in case by default.',
        traditionalExplanation: 'خبر المبتدأ مرفوع وعلامة رفعه الضمة المنونة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مُجْتَهِدٌ is predicated of الطَّالِبُ: the sentence asserts that the diligence applies to the student.' },
    ],
  },
  {
    code: 'nom-02-demonstrative-indefinite-khabar',
    textVocalized: 'هَذَا كِتَابٌ',
    textUnvocalized: 'هذا كتاب',
    transliteration: 'hādhā kitābun',
    translationEnglish: 'This is a book.',
    difficulty: 1,
    notes: 'Arabic has no separate word for "is" here — the nominal sentence structure itself carries that meaning.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'هَذَا', surfaceUnvocalized: 'هذا', lemma: 'هذا', partOfSpeech: 'demonstrative',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'built (مبني), estimated nominative', markerType: 'estimated',
        translation: 'this',
        explanation: 'Demonstratives are built words (مبني) — they never change their ending no matter their grammatical role. Their case is still assigned and estimated even though no vowel changes.',
        traditionalExplanation: 'اسم إشارة مبني في محل رفع مبتدأ.',
      },
      {
        position: 2, surfaceVocalized: 'كِتَابٌ', surfaceUnvocalized: 'كتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب',
        stem: 'كتاب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite',
        grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'a book',
        explanation: 'English inserts "is" here; Arabic needs no linking verb in a present-tense nominal sentence — the juxtaposition of mubtada and khabar itself expresses "is."',
        traditionalExplanation: 'خبر المبتدأ مرفوع وعلامة رفعه الضمة المنونة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'كِتَابٌ identifies what هَذَا refers to.' },
    ],
  },
  {
    code: 'nom-03-demonstrative-feminine-adjective',
    textVocalized: 'هَذِهِ الْمَدْرَسَةُ جَمِيلَةٌ',
    textUnvocalized: 'هذه المدرسة جميلة',
    transliteration: 'hādhihi l-madrasatu jamīlatun',
    translationEnglish: 'This school is beautiful.',
    difficulty: 2,
    notes: 'هَذِهِ + noun functions as a single definite mubtada phrase; adjective agreement here is only in gender/number/definiteness since جميلة is the khabar, not a نعت.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'هَذِهِ', surfaceUnvocalized: 'هذه', lemma: 'هذه', partOfSpeech: 'demonstrative',
        gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'built, estimated nominative', markerType: 'estimated',
        translation: 'this (f.)',
        explanation: 'هَذِهِ is the feminine counterpart of هَذَا, chosen because المدرسة is grammatically feminine.',
      },
      {
        position: 2, surfaceVocalized: 'الْمَدْرَسَةُ', surfaceUnvocalized: 'المدرسة', lemma: 'مدرسة', rootRadicals: 'د ر س', patternLabel: 'Noun of place (feminine) — مَفْعَلة',
        prefix: 'ال', stem: 'مدرسة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite',
        grammaticalCase: 'nominative', role: 'badal (or noun in apposition, restating the demonstrative\'s referent)', marker: 'ḍammah (ـُ)', markerType: 'visible',
        translation: 'the school',
        explanation: 'المدرسة restates exactly what هذه points at, agreeing with it in case (nominative) as apposition (بدل) to the demonstrative mubtada.',
      },
      {
        position: 3, surfaceVocalized: 'جَمِيلَةٌ', surfaceUnvocalized: 'جميلة', lemma: 'جميل', suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'beautiful',
        explanation: 'جَمِيلَةٌ carries the feminine ة to agree with المدرسة. Note this is agreement as a khabar (predicate), not as a نعت (attributive adjective) — the four-feature agreement rule for adjectives only applies inside a noun phrase, not between mubtada and khabar.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'المدرسة is in apposition to هذه, clarifying its referent.' },
      { headPosition: 2, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'جميلة is predicated of المدرسة (and, through it, of هذه).' },
    ],
  },
  {
    code: 'nom-04-khabar-shibh-jumla',
    textVocalized: 'الْكِتَابُ عَلَى الطَّاوِلَةِ',
    textUnvocalized: 'الكتاب على الطاولة',
    transliteration: 'al-kitābu ʿalā ṭ-ṭāwilati',
    translationEnglish: 'The book is on the table.',
    difficulty: 2,
    notes: 'Demonstrates a prepositional-phrase khabar (شبه جملة) rather than a single-word khabar.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْكِتَابُ', surfaceUnvocalized: 'الكتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', prefix: 'ال', stem: 'كتاب',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the book',
        explanation: 'Definite noun in default nominative position as mubtada.',
      },
      {
        position: 2, surfaceVocalized: 'عَلَى', surfaceUnvocalized: 'على', lemma: 'على', partOfSpeech: 'particle', role: 'preposition (حرف جر) governing the following noun',
        translation: 'on', explanation: 'A preposition has no case of its own; it governs the noun that follows, forcing it into the genitive.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّاوِلَةِ', surfaceUnvocalized: 'الطاولة', lemma: 'طاولة', prefix: 'ال', stem: 'طاولة', suffix: 'ة',
        partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'majrūr (object of the preposition)', marker: 'kasrah (ـِ)', markerType: 'visible', governedByPosition: 2,
        translation: 'the table',
        explanation: 'الطاولة is genitive purely because عَلَى governs it — this is grammatical government (العامل) in its simplest form.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'عَلَى governs الطَّاوِلَةِ, assigning it the genitive case.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The whole prepositional phrase عَلَى الطَّاوِلَةِ functions as the khabar of الكتاب.' },
    ],
  },
  {
    code: 'nom-05-adjective-agreement-definite',
    textVocalized: 'الطَّالِبُ الْمُجْتَهِدُ حَاضِرٌ',
    textUnvocalized: 'الطالب المجتهد حاضر',
    transliteration: 'aṭ-ṭālibu l-mujtahidu ḥāḍirun',
    translationEnglish: 'The diligent student is present.',
    difficulty: 2,
    notes: 'Contrast with nom-01: here المجتهد is a نعت (attributive adjective) inside the mubtada phrase, not the khabar — so it must match الطالب in all four agreement features, including definiteness and case.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student',
        explanation: 'Head noun of the mubtada phrase.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُجْتَهِدُ', surfaceUnvocalized: 'المجتهد', lemma: 'مجتهد', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'naʿt (attributive adjective) of الطالب',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the diligent',
        explanation: 'This time المجتهد takes ال and matches الطالب in gender, number, definiteness, and case — all four agreement features required of a نعت, not just case.',
        traditionalExplanation: 'نعت مرفوع وعلامة رفعه الضمة، تابع للمنعوت في التعريف والعدد والنوع والإعراب.',
      },
      {
        position: 3, surfaceVocalized: 'حَاضِرٌ', surfaceUnvocalized: 'حاضر', lemma: 'حاضر', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'present',
        explanation: 'The khabar of the whole sentence is حَاضِرٌ, predicated of the entire phrase "the diligent student," not of المجتهد alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'noun_adjective', explanation: 'المجتهد describes الطالب and must agree with it in all four features.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'حاضر is predicated of the whole subject phrase headed by الطالب.' },
    ],
  },
  {
    code: 'nom-06-idafa-basic',
    textVocalized: 'كِتَابُ الطَّالِبِ جَدِيدٌ',
    textUnvocalized: 'كتاب الطالب جديد',
    transliteration: 'kitābu ṭ-ṭālibi jadīdun',
    translationEnglish: "The student's book is new.",
    difficulty: 2,
    notes: 'The classic إضافة (possessive construction): the first noun takes no ال and no tanwīn, the second is genitive and lends its definiteness to the whole phrase.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كِتَابُ', surfaceUnvocalized: 'كتاب', lemma: 'كتاب', rootRadicals: 'ك ت ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative',
        role: 'mubtada; مضاف (first term of the idafa)', marker: 'ḍammah, no tanwīn', markerType: 'visible',
        translation: "book (of)",
        explanation: 'As the مضاف, كتاب can never take ال or tanwīn — it borrows its definiteness from الطالب that follows. Its case (nominative here) still comes from its own role as mubtada.',
        traditionalExplanation: 'مبتدأ مرفوع، وهو مضاف.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبِ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'muḍāf ilayh (second term of the idafa)',
        marker: 'kasrah (ـِ)', markerType: 'visible', translation: "the student's",
        explanation: 'المضاف إليه is always genitive — this is a fixed rule, independent of whatever role the whole إضافة phrase plays in the larger sentence.',
        traditionalExplanation: 'مضاف إليه مجرور وعلامة جره الكسرة.',
      },
      {
        position: 3, surfaceVocalized: 'جَدِيدٌ', surfaceUnvocalized: 'جديد', lemma: 'جديد', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible',
        translation: 'new',
        explanation: 'خبر of the whole إضافة phrase "كتاب الطالب," which behaves as a single definite noun phrase for the purposes of the nominal sentence.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'الطالب is the possessor; its genitive case and its definiteness both flow from this relationship.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'جديد is predicated of the whole idafa phrase.' },
    ],
  },
  {
    code: 'nom-07-idafa-passive-participle-khabar',
    textVocalized: 'بَابُ الْبَيْتِ مَفْتُوحٌ',
    textUnvocalized: 'باب البيت مفتوح',
    transliteration: 'bābu l-bayti maftūḥun',
    translationEnglish: 'The door of the house is open.',
    difficulty: 2,
    tokens: [
      {
        position: 1, surfaceVocalized: 'بَابُ', surfaceUnvocalized: 'باب', lemma: 'باب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative', role: 'mubtada; مضاف',
        marker: 'ḍammah, no tanwīn', markerType: 'visible', translation: 'door (of)',
        explanation: 'مضاف — takes its definiteness from البيت.',
      },
      {
        position: 2, surfaceVocalized: 'الْبَيْتِ', surfaceUnvocalized: 'البيت', lemma: 'بيت', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive', role: 'muḍāf ilayh', marker: 'kasrah (ـِ)', markerType: 'visible',
        translation: 'the house',
        explanation: 'مضاف إليه, genitive by the fixed idafa rule.',
      },
      {
        position: 3, surfaceVocalized: 'مَفْتُوحٌ', surfaceUnvocalized: 'مفتوح', lemma: 'مفتوح', rootRadicals: 'ف ت ح', patternLabel: 'Passive participle (Form I) — مَفْعُول',
        partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'nominative',
        role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'open',
        explanation: 'A passive participle (اسم مفعول) used as an ordinary adjective — "opened," i.e. "open." Its case comes purely from its syntactic role as khabar, unrelated to its morphological shape.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'البيت possesses باب.' },
      { headPosition: 1, dependentPosition: 3, relation: 'mubtada_khabar', explanation: 'مفتوح is predicated of the whole idafa phrase باب البيت.' },
    ],
  },
  {
    code: 'nom-08-plural-mubtada-shibh-jumla',
    textVocalized: 'الطُّلَّابُ فِي الْفَصْلِ',
    textUnvocalized: 'الطلاب في الفصل',
    transliteration: 'aṭ-ṭullābu fī l-faṣli',
    translationEnglish: 'The students are in the classroom.',
    difficulty: 2,
    notes: 'الطلاب is a broken plural (جمع تكسير) of الطالب — its shape changes internally rather than by suffix, but it is still grammatically singular in form for agreement purposes elsewhere (contrast with sound plurals).',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun',
        gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'طلاب is a broken plural: an internal vowel-pattern change (فُعَّال) rather than an added suffix. It still takes ordinary singular-noun case endings.',
      },
      {
        position: 2, surfaceVocalized: 'فِي', surfaceUnvocalized: 'في', lemma: 'في', partOfSpeech: 'particle', role: 'preposition governing the following noun', translation: 'in',
        explanation: 'A preposition of location, governing الفصل into the genitive.',
      },
      {
        position: 3, surfaceVocalized: 'الْفَصْلِ', surfaceUnvocalized: 'الفصل', lemma: 'فصل', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', grammaticalCase: 'genitive', role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the classroom',
        explanation: 'Genitive by government of في.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 3, relation: 'preposition_object', explanation: 'في governs الفصل.' },
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The prepositional phrase في الفصل is the khabar of الطلاب.' },
    ],
  },
  {
    code: 'nom-09-pronoun-mubtada-plural-khabar',
    textVocalized: 'نَحْنُ طُلَّابٌ مُجْتَهِدُونَ',
    textUnvocalized: 'نحن طلاب مجتهدون',
    transliteration: 'naḥnu ṭullābun mujtahidūna',
    translationEnglish: 'We are diligent students.',
    difficulty: 2,
    notes: 'A detached (free-standing) personal pronoun as mubtada, with a khabar built from an indefinite noun plus its نعت — the sound masculine plural نعت agrees with طلاب on all four features even though طلاب itself is a broken plural.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'نَحْنُ', surfaceUnvocalized: 'نحن', lemma: 'نحن', partOfSpeech: 'pronoun', person: 'first', number: 'plural',
        grammaticalCase: 'nominative', role: 'mubtada', marker: 'built (مبني), estimated nominative', markerType: 'estimated', translation: 'we',
        explanation: 'Detached personal pronouns like نحن are مبني (built) — they never take a case ending — but a case is still assigned to them by their grammatical role, here مبتدأ.',
      },
      {
        position: 2, surfaceVocalized: 'طُلَّابٌ', surfaceUnvocalized: 'طلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', partOfSpeech: 'noun',
        gender: 'masculine', number: 'plural', definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar',
        marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'students',
        explanation: 'طلاب (broken plural of طالب) is the head of the khabar phrase — indefinite and nominative, exactly like a single-word khabar.',
      },
      {
        position: 3, surfaceVocalized: 'مُجْتَهِدُونَ', surfaceUnvocalized: 'مجتهدون', lemma: 'مجتهد', rootRadicals: 'ج ه د', suffix: 'ون',
        patternLabel: 'Active participle (Form VIII) — مُفْتَعِل', partOfSpeech: 'adjective', gender: 'masculine', number: 'plural',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'naʿt of طلاب', marker: 'ـُونَ (sound masculine plural nominative)',
        markerType: 'secondary', translation: 'diligent',
        explanation: 'Even though طلاب is a broken plural, its human-referring نعت regularly takes the sound masculine plural shape (مُجْتَهِدُونَ) rather than a broken-plural adjective — the نعت still agrees in gender, number, definiteness, and case, just realized through a different plural mechanism than its noun.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'طلابٌ مجتهدون (the whole noun+adjective phrase) is predicated of نحن.' },
      { headPosition: 2, dependentPosition: 3, relation: 'noun_adjective', explanation: 'مجتهدون describes طلاب and agrees with it in gender, number, definiteness, and case.' },
    ],
  },
  {
    code: 'nom-10-interrogative-khabar-muqaddam',
    textVocalized: 'أَيْنَ الْمُعَلِّمُ؟',
    textUnvocalized: 'أين المعلم؟',
    transliteration: 'ayna l-muʿallimu',
    translationEnglish: 'Where is the teacher?',
    difficulty: 2,
    notes: 'An interrogative adverb of place obligatorily opens its sentence, which forces the khabar (أين) in front of the mubtada (المعلم) — the reverse order from every earlier nominal sentence in this course.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'أَيْنَ', surfaceUnvocalized: 'أين', lemma: 'أين', partOfSpeech: 'interrogative',
        grammaticalCase: 'nominative', role: 'khabar muqaddam (fronted predicate — interrogative adverb of place)',
        marker: 'built (مبني), estimated nominative', markerType: 'estimated', translation: 'where',
        explanation: 'أين is a built interrogative word that must open its sentence; grammatically it still functions as the khabar of المعلم, just placed first.',
      },
      {
        position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada muʾakhkhar (delayed subject)', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher',
        explanation: 'المعلم is still the مبتدأ, just delayed past its khabar — word order changes, but the underlying roles and their default case (both nominative) do not.',
      },
    ],
    dependencies: [
      { headPosition: 2, dependentPosition: 1, relation: 'mubtada_khabar', explanation: 'أين is the (fronted) khabar of المعلم, the (delayed) mubtada — a question about where the teacher is located.' },
    ],
  },
  {
    code: 'nom-11-dual-teachers-busy',
    textVocalized: 'الْمُعَلِّمَانِ مَشْغُولَانِ',
    textUnvocalized: 'المعلمان مشغولان',
    transliteration: 'al-muʿallimāni mashghūlāni',
    translationEnglish: 'The two teachers are busy.',
    difficulty: 2,
    notes: 'A second dual mubtada/khabar pair (compare case-04), this time with a passive-participle khabar rather than an active-participle one.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الْمُعَلِّمَانِ', surfaceUnvocalized: 'المعلمان', lemma: 'معلم', rootRadicals: 'ع ل م', prefix: 'ال', suffix: 'ان',
        partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'nominative', role: 'mubtada',
        marker: 'ـَانِ (dual nominative suffix)', markerType: 'secondary', translation: 'the two teachers',
        explanation: 'Dual nominative suffix replacing the singular\'s ordinary ḍammah, exactly as in case-04.',
      },
      {
        position: 2, surfaceVocalized: 'مَشْغُولَانِ', surfaceUnvocalized: 'مشغولان', lemma: 'مشغول', rootRadicals: 'ش غ ل', suffix: 'ان',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', partOfSpeech: 'adjective', gender: 'masculine', number: 'dual',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ـَانِ', markerType: 'secondary', translation: 'busy',
        explanation: 'مشغول is the اسم مفعول (passive participle) of شغل, "to occupy" — literally "occupied," used here as an ordinary predicate adjective meaning "busy." It copies the mubtada\'s dual number because it is a single-word khabar, not a following verb.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'مشغولان is predicated of المعلمان and matches its dual number.' },
    ],
  },
  {
    code: 'nom-12-idafa-chain',
    textVocalized: 'بَابُ بَيْتِ الطَّالِبِ مَفْتُوحٌ',
    textUnvocalized: 'باب بيت الطالب مفتوح',
    transliteration: 'bābu bayti ṭ-ṭālibi maftūḥun',
    translationEnglish: "The door of the student's house is open.",
    difficulty: 4,
    notes: 'A three-term idafa chain: بَيْتِ is simultaneously مضاف إليه (of باب) and مضاف (to الطالب) — the hallmark of a chained إضافة. Only the final term (الطالب) can carry ال; every term before the last takes neither ال nor تنوين.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'بَابُ', surfaceUnvocalized: 'باب', lemma: 'باب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'nominative', role: 'mubtada; مضاف (first term of the chain)',
        marker: 'ḍammah, no tanwīn', markerType: 'visible', translation: 'door (of)',
        explanation: 'As the first مضاف in the chain, باب can never take ال or تنوين — its definiteness ultimately comes from الطالب at the very end.',
      },
      {
        position: 2, surfaceVocalized: 'بَيْتِ', surfaceUnvocalized: 'بيت', lemma: 'بيت', partOfSpeech: 'noun', gender: 'masculine', number: 'singular',
        definiteness: 'definite', state: 'construct (مضاف)', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh of باب; simultaneously مضاف (second term, relative to الطالب)',
        marker: 'kasrah, no tanwīn', markerType: 'visible', translation: "house (of)",
        explanation: 'This is the key move in an idafa chain: بيت is genitive because it is مضاف إليه of باب, but it also takes no ال or تنوين of its own because it is itself مضاف to الطالب — every middle term in a chain plays both roles at once.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّالِبِ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'muḍāf ilayh (final term of the chain)', marker: 'kasrah (ـِ)', markerType: 'visible', translation: "the student's",
        explanation: 'The final term of the chain — the only one allowed to carry ال — and the source of definiteness for the entire three-word phrase.',
      },
      {
        position: 4, surfaceVocalized: 'مَفْتُوحٌ', surfaceUnvocalized: 'مفتوح', lemma: 'مفتوح', rootRadicals: 'ف ت ح',
        patternLabel: 'Passive participle (Form I) — مَفْعُول', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular',
        definiteness: 'indefinite', grammaticalCase: 'nominative', role: 'khabar', marker: 'ḍammah + tanwīn (ـٌ)', markerType: 'visible', translation: 'open',
        explanation: 'Predicated of the entire three-term idafa chain, not just of بيت or الطالب alone.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mudaf_mudaf_ilayh', explanation: 'بيت is مضاف إليه of باب, supplying part of its definiteness and forcing its genitive case.' },
      { headPosition: 2, dependentPosition: 3, relation: 'mudaf_mudaf_ilayh', explanation: 'الطالب is مضاف إليه of بيت — بيت is simultaneously مضاف إليه (to باب) and مضاف (to الطالب), the hallmark of an idafa chain.' },
      { headPosition: 1, dependentPosition: 4, relation: 'mubtada_khabar', explanation: 'مفتوح is predicated of the whole three-term idafa chain باب بيت الطالب.' },
    ],
  },
];
