import type { SentenceSeed } from '../sentenceTypes';

export const verbalSentences: SentenceSeed[] = [
  {
    code: 'verb-01-basic-vso',
    textVocalized: 'كَتَبَ الطَّالِبُ الدَّرْسَ',
    textUnvocalized: 'كتب الطالب الدرس',
    transliteration: 'kataba ṭ-ṭālibu d-darsa',
    translationEnglish: 'The student wrote the lesson.',
    difficulty: 1,
    notes: 'The anchor verbal sentence of this course: verb–subject–object order, with the subject nominative and the object accusative purely by role, not by position.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كَتَبَ', surfaceUnvocalized: 'كتب', lemma: 'كتب', rootRadicals: 'ك ت ب', patternLabel: 'Form I — فَعَلَ',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb (فعل)',
        translation: 'wrote', explanation: 'Perfect-tense verb, third person masculine singular by default until a فاعل is confirmed. Arabic sentences normally open with the verb.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', patternLabel: 'Active participle (Form I) — فَاعِل',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil (subject)', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student',
        explanation: 'The doer of the action is always nominative, regardless of the fact that it comes second, after the verb — position in Arabic does not decide grammatical role the way it does in English.',
        traditionalExplanation: 'فاعل مرفوع وعلامة رفعه الضمة الظاهرة.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi (direct object)', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson',
        explanation: 'The thing acted upon is accusative. Note that "the student" — semantically the agent — is nominative, and "the lesson" — semantically the patient — is accusative: case tracks grammatical role exactly, with no exceptions for meaning.',
        traditionalExplanation: 'مفعول به منصوب وعلامة نصبه الفتحة الظاهرة.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the action of كتب.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس receives the action of كتب.' },
    ],
  },
  {
    code: 'verb-02-dual-subject-singular-verb',
    textVocalized: 'كَتَبَ الطَّالِبَانِ الدَّرْسَ',
    textUnvocalized: 'كتب الطالبان الدرس',
    transliteration: 'kataba ṭ-ṭālibāni d-darsa',
    translationEnglish: 'The two students wrote the lesson.',
    difficulty: 2,
    notes: 'Direct contrast with verb-01: the فاعل is now dual, but the verb stays singular (كَتَبَ, not a dual verb form) because the فاعل follows the verb.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كَتَبَ', surfaceUnvocalized: 'كتب', lemma: 'كتب', rootRadicals: 'ك ت ب', patternLabel: 'Form I — فَعَلَ',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb',
        translation: 'wrote', explanation: 'Stays grammatically singular even though its فاعل is dual — this is the default rule for a verb preceding its subject.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبَانِ', surfaceUnvocalized: 'الطالبان', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ان',
        partOfSpeech: 'noun', gender: 'masculine', number: 'dual', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ـَانِ (dual nominative suffix)', markerType: 'secondary', translation: 'the two students',
        explanation: 'The dual nominative suffix ـَانِ replaces the ordinary singular case vowel entirely — a secondary marker, not the usual ḍammah.',
        traditionalExplanation: 'فاعل مرفوع وعلامة رفعه الألف لأنه مثنى.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson',
        explanation: 'Unaffected by the change to the subject — still a straightforward accusative object.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالبان performs the action; the verb does not change to a dual form.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is the object, unaffected by the subject\'s number.' },
    ],
  },
  {
    code: 'verb-03-plural-subject-singular-verb',
    textVocalized: 'كَتَبَ الطُّلَّابُ الدَّرْسَ',
    textUnvocalized: 'كتب الطلاب الدرس',
    transliteration: 'kataba ṭ-ṭullābu d-darsa',
    translationEnglish: 'The students wrote the lesson.',
    difficulty: 2,
    notes: 'Same rule as verb-02, now with a plural فاعل — the verb is still كَتَبَ, not كَتَبُوا.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'كَتَبَ', surfaceUnvocalized: 'كتب', lemma: 'كتب', rootRadicals: 'ك ت ب', patternLabel: 'Form I — فَعَلَ',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'wrote',
        explanation: 'Grammatically singular despite a plural فاعل — the single most-tested rule in this unit.',
      },
      {
        position: 2, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'طلاب is a broken plural, so — unlike a sound plural — it takes an ordinary singular-style ḍammah for the nominative, not a special plural suffix.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object, unaffected.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطلاب performs the action; verb agreement stays singular.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is the object.' },
    ],
  },
  {
    code: 'verb-04-fronted-subject-full-agreement',
    textVocalized: 'الطُّلَّابُ كَتَبُوا الدَّرْسَ',
    textUnvocalized: 'الطلاب كتبوا الدرس',
    transliteration: 'aṭ-ṭullābu katabū d-darsa',
    translationEnglish: 'The students, they wrote the lesson.',
    difficulty: 3,
    notes: 'The sharp contrast case: once الطلاب is fronted (making this technically a nominal sentence whose khabar is a full verbal sentence), the verb fully agrees — كَتَبُوا, plural.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'الطُّلَّابُ', surfaceUnvocalized: 'الطلاب', lemma: 'طلاب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'plural', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'mubtada (with an embedded verbal sentence as its khabar)', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the students',
        explanation: 'Because a noun now opens the sentence, this is structurally a nominal sentence — الطلاب is mubtada, not fāʿil, even though it is still the one doing the writing.',
        alternatives: [
          { description: 'Some grammarians instead treat a fronted noun before a verb whose hidden pronoun refers back to it as still effectively topicalized fāʿil in casual analysis, but the formal traditional analysis is mubtada + verbal-sentence khabar.', isTraditional: true },
        ],
      },
      {
        position: 2, surfaceVocalized: 'كَتَبُوا', surfaceUnvocalized: 'كتبوا', lemma: 'كتب', rootRadicals: 'ك ت ب', patternLabel: 'Form I — فَعَلَ', stem: 'كتب', suffix: 'وا',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'plural', role: 'verb, with its own embedded plural subject pronoun (فاعل)',
        translation: 'they wrote',
        explanation: 'The suffix وا is an attached subject pronoun meaning "they (m.)" — this verb is itself a complete little sentence, agreeing fully because its فاعل (the hidden "they") is not a separate following noun but the attached pronoun referring back to الطلاب.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative',
        role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object of كتبوا.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'mubtada_khabar', explanation: 'The full verbal sentence كَتَبُوا الدَّرْسَ serves as the khabar of الطلاب.' },
      { headPosition: 2, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is the object of the embedded verb.' },
    ],
  },
  {
    code: 'verb-05-feminine-intransitive',
    textVocalized: 'ذَهَبَتِ الطَّالِبَةُ إِلَى الْمَدْرَسَةِ',
    textUnvocalized: 'ذهبت الطالبة إلى المدرسة',
    transliteration: 'dhahabati ṭ-ṭālibatu ilā l-madrasati',
    translationEnglish: 'The (female) student went to school.',
    difficulty: 2,
    notes: 'ذهب is intransitive — it takes no مفعول به, only a prepositional phrase of destination. The verb carries a feminine ت suffix to agree with its فاعل in gender.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'ذَهَبَتِ', surfaceUnvocalized: 'ذهبت', lemma: 'ذهب', rootRadicals: 'ذ ه ب', patternLabel: 'Form I — فَعَلَ', stem: 'ذهب', suffix: 'ت',
        partOfSpeech: 'verb', person: 'third', gender: 'feminine', number: 'singular', role: 'the verb',
        translation: 'went', explanation: 'The ت suffix marks feminine agreement with الطالبة — this happens even though the verb precedes the subject and stays "singular," because gender agreement (unlike number) is required even before the subject.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبَةُ', surfaceUnvocalized: 'الطالبة', lemma: 'طالبة', rootRadicals: 'ط ل ب', prefix: 'ال', suffix: 'ة',
        partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the (female) student', explanation: 'Feminine of طالب, formed by adding ة.',
      },
      {
        position: 3, surfaceVocalized: 'إِلَى', surfaceUnvocalized: 'إلى', lemma: 'إلى', partOfSpeech: 'particle', role: 'preposition (direction)', translation: 'to',
        explanation: 'ذهب is intransitive in the sense that "the school" cannot simply follow it as a direct object — it requires this preposition of direction.',
      },
      {
        position: 4, surfaceVocalized: 'الْمَدْرَسَةِ', surfaceUnvocalized: 'المدرسة', lemma: 'مدرسة', rootRadicals: 'د ر س', patternLabel: 'Noun of place (feminine) — مَفْعَلة',
        prefix: 'ال', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', definiteness: 'definite', grammaticalCase: 'genitive',
        role: 'majrūr', marker: 'kasrah (ـِ)', markerType: 'visible', translation: 'the school',
        explanation: 'Genitive by government of إلى.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالبة performs the going.' },
      { headPosition: 3, dependentPosition: 4, relation: 'preposition_object', explanation: 'إلى governs المدرسة.' },
    ],
  },
  {
    code: 'verb-06-imperfect-indefinite-object',
    textVocalized: 'يَكْتُبُ الطَّالِبُ رِسَالَةً',
    textUnvocalized: 'يكتب الطالب رسالة',
    transliteration: 'yaktubu ṭ-ṭālibu risālatan',
    translationEnglish: 'The student writes / is writing a letter.',
    difficulty: 2,
    notes: 'Introduces the imperfect (المضارع): one Arabic form covers both English simple present and present progressive.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'يَكْتُبُ', surfaceUnvocalized: 'يكتب', lemma: 'كتب', rootRadicals: 'ك ت ب', prefix: 'ي', stem: 'كتب',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', mood: 'indicative', grammaticalCase: undefined,
        role: 'the verb', marker: 'ḍammah on the final letter (indicative)', markerType: 'visible', translation: 'writes / is writing',
        explanation: 'The prefix ي marks third person; unlike the perfect, the imperfect\'s ending itself changes with mood — here ḍammah shows the default indicative mood.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative',
        role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject, nominative as always.',
      },
      {
        position: 3, surfaceVocalized: 'رِسَالَةً', surfaceUnvocalized: 'رسالة', lemma: 'رسالة', suffix: 'ة', partOfSpeech: 'noun', gender: 'feminine',
        number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a letter', explanation: 'Indefinite direct object, accusative.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the writing.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'رسالة is what is written.' },
    ],
  },
  {
    code: 'verb-07-intransitive-no-object',
    textVocalized: 'جَلَسَ الْوَلَدُ',
    textUnvocalized: 'جلس الولد',
    transliteration: 'jalasa l-waladu',
    translationEnglish: 'The boy sat.',
    difficulty: 1,
    notes: 'A minimal, complete verbal sentence: intransitive verb + subject, no object at all.',
    tokens: [
      { position: 1, surfaceVocalized: 'جَلَسَ', surfaceUnvocalized: 'جلس', lemma: 'جلس', rootRadicals: 'ج ل س', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'sat', explanation: 'Intransitive: نص فعل لازم — its meaning is complete without any مفعول به.' },
      { position: 2, surfaceVocalized: 'الْوَلَدُ', surfaceUnvocalized: 'الولد', lemma: 'ولد', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the boy', explanation: 'Subject, nominative.' },
    ],
    dependencies: [{ headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الولد performs the sitting.' }],
  },
  {
    code: 'verb-08-transitive-teacher-door',
    textVocalized: 'فَتَحَ الْمُعَلِّمُ الْبَابَ',
    textUnvocalized: 'فتح المعلم الباب',
    transliteration: 'fataḥa l-muʿallimu l-bāba',
    translationEnglish: 'The teacher opened the door.',
    difficulty: 1,
    tokens: [
      { position: 1, surfaceVocalized: 'فَتَحَ', surfaceUnvocalized: 'فتح', lemma: 'فتح', rootRadicals: 'ف ت ح', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'opened', explanation: 'Transitive Form I verb.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', rootRadicals: 'ع ل م', patternLabel: undefined, prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'From Form II مُعَلِّم, "one who causes learning" — used as an ordinary noun, "teacher." Subject, nominative.' },
      { position: 3, surfaceVocalized: 'الْبَابَ', surfaceUnvocalized: 'الباب', lemma: 'باب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the door', explanation: 'Direct object.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the opening.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الباب is opened.' },
    ],
  },
  {
    code: 'verb-09-object-with-adjective',
    textVocalized: 'سَمِعَ الطَّالِبُ صَوْتًا غَرِيبًا',
    textUnvocalized: 'سمع الطالب صوتا غريبا',
    transliteration: 'samiʿa ṭ-ṭālibu ṣawtan gharīban',
    translationEnglish: 'The student heard a strange sound.',
    difficulty: 3,
    notes: 'The adjective غريبًا must copy every feature of the noun it modifies, including case — here both are indefinite accusative.',
    tokens: [
      { position: 1, surfaceVocalized: 'سَمِعَ', surfaceUnvocalized: 'سمع', lemma: 'سمع', rootRadicals: 'س م ع', patternLabel: 'Form I — فَعَلَ', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'heard', explanation: 'Transitive verb of perception.' },
      { position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'صَوْتًا', surfaceUnvocalized: 'صوتا', lemma: 'صوت', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a sound', explanation: 'Object, indefinite accusative.' },
      { position: 4, surfaceVocalized: 'غَرِيبًا', surfaceUnvocalized: 'غريبا', lemma: 'غريب', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'naʿt of صوتًا', marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'strange', explanation: 'Agrees with صوتًا in all four features: masculine, singular, indefinite, accusative.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the hearing.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'صوتًا is what is heard.' },
      { headPosition: 3, dependentPosition: 4, relation: 'noun_adjective', explanation: 'غريبًا describes صوتًا and matches its case.' },
    ],
  },
  {
    code: 'verb-10-ditransitive',
    textVocalized: 'أَعْطَى الْمُعَلِّمُ الطَّالِبَ كِتَابًا',
    textUnvocalized: 'أعطى المعلم الطالب كتابا',
    transliteration: 'aʿṭā l-muʿallimu ṭ-ṭāliba kitāban',
    translationEnglish: 'The teacher gave the student a book.',
    difficulty: 3,
    notes: 'A verb of giving takes two مفعول به objects, both accusative — the second maps to the English indirect object, but Arabic makes no case distinction between them.',
    tokens: [
      { position: 1, surfaceVocalized: 'أَعْطَى', surfaceUnvocalized: 'أعطى', lemma: 'أعطى', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'gave', explanation: 'A Form IV verb of giving that takes two direct objects.' },
      { position: 2, surfaceVocalized: 'الْمُعَلِّمُ', surfaceUnvocalized: 'المعلم', lemma: 'معلم', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil', marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the teacher', explanation: 'Subject.' },
      { position: 3, surfaceVocalized: 'الطَّالِبَ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'first mafʿūl bihi (the one given to)', marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the student', explanation: 'First object — corresponds to the English indirect object, but is still just accusative مفعول به in Arabic.' },
      { position: 4, surfaceVocalized: 'كِتَابًا', surfaceUnvocalized: 'كتابا', lemma: 'كتاب', rootRadicals: 'ك ت ب', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'indefinite', grammaticalCase: 'accusative', role: 'second mafʿūl bihi (the thing given)', marker: 'fatḥah + tanwīn (ـً)', markerType: 'visible', translation: 'a book', explanation: 'Second object, also accusative — Arabic marks both objects identically.' },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'المعلم performs the giving.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الطالب is the recipient — first object.' },
      { headPosition: 1, dependentPosition: 4, relation: 'verb_object', explanation: 'كتابًا is the thing given — second object.' },
    ],
  },
  {
    code: 'verb-11-imperative',
    textVocalized: 'اِفْتَحِ الْبَابَ',
    textUnvocalized: 'افتح الباب',
    transliteration: 'iftaḥi l-bāba',
    translationEnglish: 'Open the door!',
    difficulty: 2,
    notes: 'The imperative (فعل أمر) is a built (مبني) verb form with no case or mood inflection. The kasrah under the final ح is a purely phonetic helping vowel — inserted to avoid two adjacent silent consonants before البابَ\'s elided hamzat al-waṣl — not a grammatical ending.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'اِفْتَحِ', surfaceUnvocalized: 'افتح', lemma: 'فتح', rootRadicals: 'ف ت ح', patternLabel: 'Form I — اِفْعَلْ (imperative)',
        stem: 'فتح', partOfSpeech: 'verb', person: 'second', gender: 'masculine', number: 'singular', mood: 'imperative',
        role: 'the verb (فعل أمر), with an obligatorily hidden subject pronoun أنتَ',
        marker: 'built (مبني) — no case; the final kasrah here is a helping vowel avoiding two adjacent silent consonants, not a mood marker',
        markerType: 'estimated', translation: 'open!',
        explanation: 'The imperative has no case or mood ending of its own the way the perfect and imperfect do — it is simply built. Its فاعل is the hidden pronoun "you" (أنتَ مستتر وجوبًا), obligatorily unexpressed because the imperative already encodes second person.',
      },
      {
        position: 2, surfaceVocalized: 'الْبَابَ', surfaceUnvocalized: 'الباب', lemma: 'باب', prefix: 'ال', partOfSpeech: 'noun', gender: 'masculine',
        number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi', marker: 'fatḥah (ـَ)', markerType: 'visible',
        translation: 'the door', explanation: 'Ordinary accusative direct object of the command.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_object', explanation: 'البابَ is the object of the implied command "open."' },
    ],
  },
  {
    code: 'verb-12-negation-jussive-lam',
    textVocalized: 'لَمْ يَكْتُبِ الطَّالِبُ الدَّرْسَ',
    textUnvocalized: 'لم يكتب الطالب الدرس',
    transliteration: 'lam yaktubi ṭ-ṭālibu d-darsa',
    translationEnglish: 'The student did not write the lesson.',
    difficulty: 3,
    notes: 'لم negates a perfect-tense meaning but grammatically governs a following imperfect verb into the jussive mood (الجزم). The jussive\'s basic marker is sukūn; here a helping kasrah stands in for it, again to avoid two adjacent silent consonants before الطالبُ.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'لَمْ', surfaceUnvocalized: 'لم', lemma: 'لم', partOfSpeech: 'particle',
        role: 'negating and jussive-governing particle (حرف نفي وجزم)', translation: 'did not',
        explanation: 'لم flips an imperfect verb\'s meaning to past negation while grammatically requiring the jussive mood on that verb.',
      },
      {
        position: 2, surfaceVocalized: 'يَكْتُبِ', surfaceUnvocalized: 'يكتب', lemma: 'كتب', rootRadicals: 'ك ت ب', prefix: 'ي', stem: 'كتب',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', mood: 'jussive', role: 'the verb, jussive after لم',
        marker: 'sukūn (realized here as a helping kasrah before the following hamzat al-waṣl, to avoid two adjacent silent consonants)',
        markerType: 'visible', translation: 'wrote (negated: did not write)',
        explanation: 'Contrast with verb-06\'s يَكْتُبُ (indicative ḍammah): the same verb\'s final vowel changes once لم governs it into the jussive — sukūn is the jussive\'s basic marker, with this kasrah substituting only to avoid a phonetic collision.',
      },
      {
        position: 3, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject, nominative as always.',
      },
      {
        position: 4, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object, unaffected by the negation.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'particle_governed', explanation: 'لم governs يكتب into the jussive mood.' },
      { headPosition: 2, dependentPosition: 3, relation: 'verb_subject', explanation: 'الطالب performs (or here, fails to perform) the writing.' },
      { headPosition: 2, dependentPosition: 4, relation: 'verb_object', explanation: 'الدرس is the object, unaffected by the negation.' },
    ],
  },
  {
    code: 'verb-13-subjunctive-an',
    textVocalized: 'يُرِيدُ الطَّالِبُ أَنْ يَكْتُبَ الدَّرْسَ',
    textUnvocalized: 'يريد الطالب أن يكتب الدرس',
    transliteration: 'yurīdu ṭ-ṭālibu an yaktuba d-darsa',
    translationEnglish: 'The student wants to write the lesson.',
    difficulty: 3,
    notes: 'أنْ introduces a subordinate clause and forces its verb into the subjunctive mood (النصب), marked by fatḥah replacing the indicative ḍammah. The whole clause أن يكتب الدرس is a مصدر مؤول ("interpreted verbal noun") functioning as the مفعول به of يريد.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'يُرِيدُ', surfaceUnvocalized: 'يريد', lemma: 'أراد', rootRadicals: 'ر و د', patternLabel: 'Form IV — يُفْعِلُ',
        prefix: 'ي', partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', mood: 'indicative',
        role: 'the verb', marker: 'ḍammah (indicative)', markerType: 'visible', translation: 'wants',
        explanation: 'Form IV of the hollow root ر و د, "to want."',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject of يريد.',
      },
      {
        position: 3, surfaceVocalized: 'أَنْ', surfaceUnvocalized: 'أن', lemma: 'أن', partOfSpeech: 'particle',
        role: 'subordinating particle governing the following imperfect verb into the subjunctive (حرف مصدري ونصب)', translation: 'to / that',
        explanation: 'أنْ introduces the subordinate clause and, with it, functions together with يكتب الدرس as a single مصدر مؤول standing in for the مفعول به of يريد — "the student wants [the writing of the lesson]."',
      },
      {
        position: 4, surfaceVocalized: 'يَكْتُبَ', surfaceUnvocalized: 'يكتب', lemma: 'كتب', rootRadicals: 'ك ت ب', prefix: 'ي', stem: 'كتب',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', mood: 'subjunctive',
        role: 'verb of the subordinate clause, governed into the subjunctive by أنْ', marker: 'fatḥah (subjunctive)', markerType: 'visible',
        translation: 'write', explanation: 'Fatḥah replaces the indicative ḍammah once أنْ governs the verb — the clear surface signal of the subjunctive mood.',
      },
      {
        position: 5, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Direct object of the embedded يكتب.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the wanting.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'The whole subordinate clause أن يكتب الدرس (a مصدر مؤول) functions as the مفعول به of يريد.' },
      { headPosition: 3, dependentPosition: 4, relation: 'particle_governed', explanation: 'أنْ governs يكتب into the subjunctive mood.' },
      { headPosition: 4, dependentPosition: 5, relation: 'verb_object', explanation: 'الدرس is the object of the embedded verb يكتب.' },
    ],
  },
  {
    code: 'verb-14-attached-object-pronoun',
    textVocalized: 'فَهِمَ الطَّالِبُ الدَّرْسَ ثُمَّ كَتَبَهُ',
    textUnvocalized: 'فهم الطالب الدرس ثم كتبه',
    transliteration: 'fahima ṭ-ṭālibu d-darsa thumma katabahu',
    translationEnglish: 'The student understood the lesson, then wrote it.',
    difficulty: 3,
    notes: 'The attached pronoun ـهُ on كَتَبَهُ is a مفعول به referring back to الدرس. Attached pronouns are مبني and carry no visible case ending — they are said to be "في محل نصب" (in the position of an accusative), since only free-standing declinable words show vowel case marks.',
    tokens: [
      {
        position: 1, surfaceVocalized: 'فَهِمَ', surfaceUnvocalized: 'فهم', lemma: 'فهم', rootRadicals: 'ف ه م', patternLabel: 'Form I — فَعِلَ',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular', role: 'the verb', translation: 'understood',
        explanation: 'Transitive Form I verb.',
      },
      {
        position: 2, surfaceVocalized: 'الطَّالِبُ', surfaceUnvocalized: 'الطالب', lemma: 'طالب', rootRadicals: 'ط ل ب', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'nominative', role: 'fāʿil',
        marker: 'ḍammah (ـُ)', markerType: 'visible', translation: 'the student', explanation: 'Subject of both verbs in this sentence.',
      },
      {
        position: 3, surfaceVocalized: 'الدَّرْسَ', surfaceUnvocalized: 'الدرس', lemma: 'درس', rootRadicals: 'د ر س', prefix: 'ال',
        partOfSpeech: 'noun', gender: 'masculine', number: 'singular', definiteness: 'definite', grammaticalCase: 'accusative', role: 'mafʿūl bihi of فهم',
        marker: 'fatḥah (ـَ)', markerType: 'visible', translation: 'the lesson', explanation: 'Object of the first verb.',
      },
      {
        position: 4, surfaceVocalized: 'ثُمَّ', surfaceUnvocalized: 'ثم', lemma: 'ثم', partOfSpeech: 'particle',
        role: 'coordinating conjunction linking the two clauses, implying a pause or delay (حرف عطف)', translation: 'then',
        explanation: 'ثُمَّ (unlike و) implies a gap or sequence between the two actions, not mere simultaneity.',
      },
      {
        position: 5, surfaceVocalized: 'كَتَبَهُ', surfaceUnvocalized: 'كتبه', lemma: 'كتب', rootRadicals: 'ك ت ب', stem: 'كتب', suffix: 'هُ',
        partOfSpeech: 'verb', person: 'third', gender: 'masculine', number: 'singular',
        role: 'the verb, with an attached third-person object pronoun referring back to الدرس', translation: 'wrote it',
        explanation: 'The attached pronoun ـهُ is the مفعول به of كتب, standing in for الدرس. It is built (مبني) and shows no vowel case ending of its own — grammarians describe it as "في محل نصب مفعول به" (in the position of an accusative object) even without a visible mark.',
      },
    ],
    dependencies: [
      { headPosition: 1, dependentPosition: 2, relation: 'verb_subject', explanation: 'الطالب performs the understanding.' },
      { headPosition: 1, dependentPosition: 3, relation: 'verb_object', explanation: 'الدرس is what is understood.' },
      { headPosition: 5, dependentPosition: 2, relation: 'verb_subject', explanation: 'The hidden subject pronoun built into كتبه refers back to الطالب, who also performs the writing.' },
      { headPosition: 5, dependentPosition: 3, relation: 'verb_object', explanation: 'The attached pronoun ـهُ on كتبه refers back to الدرس, functioning as its مفعول به even though no separate word carries this role here.' },
    ],
  },
];
